### ISSUE TITLE
Question/Weid Behavior on IClientStore with WSFederationPlugin

### ISSUE THREAD

**Issue by DanielHabenicht** [DuendeSoftware/Support#1008]
**Which version of Duende IdentityServer are you using?**
```
<PackageReference Include="Duende.IdentityServer" Version="6.3.6" />
<PackageReference Include="Duende.IdentityServer.EntityFramework" Version="6.3.6" />
<PackageReference Include="Rsk.WsFederation.DuendeIdentityServer" Version="7.0.1" />
```
**Which version of .NET are you using?**
6.0.403

**Describe the bug**
More of a question...

We implemented a custom `IClientStore` which fetches the clients from a database. 
According to the [description of the interface](https://docs.duendesoftware.com/identityserver/v6/reference/stores/client_store/) the store should return `null` if the id of the requested client is not found. 
If we now Authenticate with the WsFederationPlugin and use a non existing client id which lead to returning null from this function we do get some weird behavior. 

Have a look at the WSFederation Logs below in comparison to what I would have expected (example is from a saml endpoint)
The `Request validation failed` error is shown twice. 
The (I suspect) Client object is displayed `{}`, but empty (not helpful). 

Questions: 
1. I assumed that the `IClientStoreFindClientByIdAsync` should not throw an error and just return `null` if no Client is found (with Identity Server handling this case). Is this the case or should we throw a custom Exception and handle it?

    a. When throwing a custom Exception the Endpoint simply returns `WS-Federation endpoint failed for unknown reason` even with the following IdentityServer Configuration: 
    ```csharp
    options.UserInteraction.ErrorUrl = Constants.DefaultErrorUrl;
    options.UserInteraction.ErrorIdParameter = "Duende.IdentityServer";
    ```
    How would I redirect the user on such an error, as this does not seem to have any effect on the WsFederationEndpoint?

**Expected behavior**

Behave in a similar way as other Plugins. 

**Log output/exception with stacktrace**

WsFederation LogOutput:
```
14:59:02 INF] Request starting HTTP/2 GET https://localhost:44310/wsfederation?wtrealm=urn%3Atestclient_wsfed_lokal_nicht_existent&wa=wsignin1.0&wreply=https%3A%2F%2Flocalhost%3A57950%2Fsignin-wsfed&wctx=CfDJ8PajCRRixNFEi8gcE_mR
-YKuSJUXEBFKqFt4rCt5tRdWvjcx_QioQwi6DyW9G16Y8V4zzKchhnwcRAm628ld1nAkD9ev2MLSTb8HFRITDikXaQWlzlJmZm2h1IGzCY8X7x5IWtYBMlAK-Hx4vhAngGmzuEP3RKWXquVKtO_tWEpR4UiWsqryMQ90js63BGnMihmXLRK0xQd9hG-GVwgvKyYcD-DbX2t7yOr1_gONgoXE70nyXmhnW_U6H
vdAvFHCaw - -
[14:59:02 INF] Creating sql server database context
[14:59:02 DBG] Login Url: /Account/Login
[14:59:02 DBG] Login Return Url Parameter: ReturnUrl
[14:59:02 DBG] Logout Url: /Account/Logout
[14:59:02 DBG] ConsentUrl Url: /consent
[14:59:02 DBG] Consent Return Url Parameter: returnUrl
[14:59:02 DBG] Error Url: /Home/Error
[14:59:02 DBG] Error Id Parameter: Duende.IdentityServer
[14:59:02 DBG] Request path /wsfederation matched to endpoint type WsFed
[14:59:02 DBG] Mapping found for endpoint: WsFed, creating handler: Rsk.WsFederation.Endpoints.WsFederationEndpoint
[14:59:02 INF] Invoking IdentityServer endpoint: Rsk.WsFederation.Endpoints.WsFederationEndpoint for /wsfederation
[14:59:02 DBG] Starting WS-Federation request. URL: https://localhost:44310/wsfederation?wtrealm=urn%3Atestclient_wsfed_lokal_nicht_existent&wa=wsignin1.0&wreply=https%3A%2F%2Flocalhost%3A57950%2Fsignin-wsfed&wctx=CfDJ8PajCRRixNF
Ei8gcE_mR-YKuSJUXEBFKqFt4rCt5tRdWvjcx_QioQwi6DyW9G16Y8V4zzKchhnwcRAm628ld1nAkD9ev2MLSTb8HFRITDikXaQWlzlJmZm2h1IGzCY8X7x5IWtYBMlAK-Hx4vhAngGmzuEP3RKWXquVKtO_tWEpR4UiWsqryMQ90js63BGnMihmXLRK0xQd9hG-GVwgvKyYcD-DbX2t7yOr1_gONgoXE70ny
XmhnW_U6HvdAvFHCaw
[14:59:02 DBG] No user present in WS-Federation sign in request
[14:59:02 DBG] Starting WS-Federation sign in request validation
[14:59:07 ERR] Request validation failed
[14:59:07 ERR] Request validation failed
{}
[14:59:07 INF] Request starting HTTP/2 GET https://localhost:44310/Home/Error?Duende.IdentityServer=CfDJ8PajCRRixNFEi8gcE_mR-YKKtEgyPxjxs3EJpX4ANHgPP07sxZoqVG8BFd9y7Iggt5SqRsc1yBphzbuw3x87PqDaIff0VFlac6Va24zrxSG5Eb_pQoadudbYl6P0C
EFZVtbxOl5vJCocvgojGXTFdW9Q2e2wc4nG2i4ZKEm-IZcKx_aEEYmsEfsNcpLhqWkjHLYwkkm5Xj388g8J02VJS7N9bL9djhgsPWZoXfS14OgKhUfUVKfF4Yy3bA3cJoojVI_xw2VPCFrdoSSWB4cVW1okUCwesIoanf2ozU_ywFz9eT-heI62TiOTSTIBPxoZhAhmON4z1zSEix0MPpt_D8Io7tb4SgYKlw
55WmiDpFtqnvs0Q3iDhy1CS173ZxIPhg - -
[14:59:07 INF] Creating sql server database context
[14:59:07 INF] Request finished HTTP/2 GET https://localhost:44310/wsfederation?wtrealm=urn%3Atestclient_wsfed_lokal_nicht_existent&wa=wsignin1.0&wreply=https%3A%2F%2Flocalhost%3A57950%2Fsignin-wsfed&wctx=CfDJ8PajCRRixNFEi8gcE_mR
-YKuSJUXEBFKqFt4rCt5tRdWvjcx_QioQwi6DyW9G16Y8V4zzKchhnwcRAm628ld1nAkD9ev2MLSTb8HFRITDikXaQWlzlJmZm2h1IGzCY8X7x5IWtYBMlAK-Hx4vhAngGmzuEP3RKWXquVKtO_tWEpR4UiWsqryMQ90js63BGnMihmXLRK0xQd9hG-GVwgvKyYcD-DbX2t7yOr1_gONgoXE70nyXmhnW_U6H
vdAvFHCaw - - - 302 0 - 4991.5738ms
[14:59:07 INF] Executing endpoint 'Project.Controllers.HomeController.Error (Project)'
```

Saml LogOutput:
Example of unsuccessful login with a non existing client ID via SAML (returning `null` from `FindServiceProviderByEntityId`
```
[14:51:00 INF] Request starting HTTP/1.1 GET https://localhost:44310/saml/metadata - -
[14:51:00 INF] Creating sql server database context
[14:51:00 DBG] Request path /saml/metadata matched to endpoint type Metadata
[14:51:00 DBG] Mapping found for endpoint: Metadata, creating handler: Rsk.Saml.Endpoints.SamlMetadataEndpoint
[14:51:00 INF] Invoking SAML endpoint: Rsk.Saml.Endpoints.SamlMetadataEndpoint for /saml/metadata
[14:51:00 DBG] Start metadata request
[14:51:00 INF] Request finished HTTP/1.1 GET https://localhost:44310/saml/metadata - - - 200 - application/samlmetadata+xml 31.2742ms
[14:51:01 INF] Request starting HTTP/2 POST https://localhost:44310/saml/sso application/x-www-form-urlencoded 694
[14:51:01 DBG] CORS request made for path: /saml/sso from origin: https://localhost:57950 but was ignored because path was not for an allowed IdentityServer CORS endpoint
[14:51:01 INF] No CORS policy found for the specified request.
[14:51:01 INF] Creating sql server database context
[14:51:01 DBG] Request path /saml/sso matched to endpoint type Sso
[14:51:01 DBG] Mapping found for endpoint: Sso, creating handler: Rsk.Saml.Endpoints.SamlSingleSignOnEndpoint
[14:51:01 INF] Invoking SAML endpoint: Rsk.Saml.Endpoints.SamlSingleSignOnEndpoint for /saml/sso
[14:51:01 DBG] Start SAML SSO request
[14:51:01 DBG] No user present in SAML SSO request
[14:51:01 DBG] Starting SAML SSO request validation
[14:51:01 INF] Checking if 24.11.2023 13:51:00 is greater than current time of 24.11.2023 13:51:01. Allowing values 150 seconds in the future to continue.
[14:51:01 INF] Checking if 24.11.2023 13:56:00 is less than current time of 24.11.2023 13:51:01. Allowing values 150 seconds in the past to continue.
[14:51:01 ERR] Unrecognized SAML service provider - cannot find SP configuration
{
  "Issuer": "urn:testclient_saml_lokal_nicht_existent",
  "BindingType": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
  "RelayState": "sr1Pn13085rg2qsLRMVOFy6z"
}
[14:51:01 DBG] Message issued by 'urn:testclient_saml_lokal_nicht_existent'. No ServiceProvider with this EntityId has been registered
[14:51:01 ERR] Request validation failed
[14:51:01 ERR] Request validation failed
{
  "Issuer": "urn:testclient_saml_lokal_nicht_existent",
  "BindingType": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
  "RelayState": "sr1Pn13085rg2qsLRMVOFy6z"
}
[14:51:01 INF] Request finished HTTP/2 POST https://localhost:44310/saml/sso application/x-www-form-urlencoded 694 - 302 0 - 64.4853ms
```

**Additional context**

Example of throwing an error in `FindClientByIdAsync`, resulting only a `WS-Federation endpoint failed for unknown reason` message returned to the HTTP Request. 
```
[15:14:37 INF] Request starting HTTP/2 GET https://localhost:44310/wsfederation?wtrealm=urn%3Atestclient_wsfed_lokal_nicht_existent&wa=wsignin1.0&wreply=https%3A%2F%2Flocalhost%3A57950%2Fsignin-wsfed&wctx=CfDJ8PajCRRixNFEi8gcE_mR
-YLqKIxle1VLuXIuYwsX1m72LLU8m7Ra3sj9RqeNllSfik7ISweZ1Kjj3-qPjfjlulAdSt6WsqJAS-FOZDjz8XB5fEbJZO_TpL_VG61XAwBpLhxX2SM4fFGxBo-o56VXKNDTM3tcoHOH0oMSzfj6qO63F83PVJevDsYyPOOdab1OCc1Zer-nfpuiqeF-ExZDJvkf6Hd1yT62G3E0JcK2BX7g6VQiNcTRzEenY
xyo-Mw8yQ - -
[15:14:37 INF] Creating sql server database context
[15:14:37 DBG] Request path /wsfederation matched to endpoint type WsFed
[15:14:37 DBG] Mapping found for endpoint: WsFed, creating handler: Rsk.WsFederation.Endpoints.WsFederationEndpoint
[15:14:37 INF] Invoking IdentityServer endpoint: Rsk.WsFederation.Endpoints.WsFederationEndpoint for /wsfederation
[15:14:37 DBG] Starting WS-Federation request. URL: https://localhost:44310/wsfederation?wtrealm=urn%3Atestclient_wsfed_lokal_nicht_existent&wa=wsignin1.0&wreply=https%3A%2F%2Flocalhost%3A57950%2Fsignin-wsfed&wctx=CfDJ8PajCRRixNF
Ei8gcE_mR-YLqKIxle1VLuXIuYwsX1m72LLU8m7Ra3sj9RqeNllSfik7ISweZ1Kjj3-qPjfjlulAdSt6WsqJAS-FOZDjz8XB5fEbJZO_TpL_VG61XAwBpLhxX2SM4fFGxBo-o56VXKNDTM3tcoHOH0oMSzfj6qO63F83PVJevDsYyPOOdab1OCc1Zer-nfpuiqeF-ExZDJvkf6Hd1yT62G3E0JcK2BX7g6VQi
NcTRzEenYxyo-Mw8yQ
[15:14:37 DBG] No user present in WS-Federation sign in request
[15:14:37 DBG] Starting WS-Federation sign in request validation
[15:14:37 WRN] Client Realm 'urn:testclient_wsfed_lokal_nicht_existent' was not found.
[15:14:37 FTL] Unhandled exception: System.Exception: Client Realm 'urn:testclient_wsfed_lokal_nicht_existent' was not found.
   at Project.Stores.DbClientStore.FindClientByIdAsync(String clientId) in C:\Path\To\Project\Stores\DbClientStore.cs:line 52
   at Duende.IdentityServer.Stores.ValidatingClientStore`1.FindClientByIdAsync(String clientId) in /_/src/IdentityServer/Stores/ValidatingClientStore.cs:line 54
   at Duende.IdentityServer.Stores.IClientStoreExtensions.FindEnabledClientByIdAsync(IClientStore store, String clientId) in /_/src/IdentityServer/Extensions/IClientStoreExtensions.cs:line 23
   at Rsk.WsFederation.DuendeIdentityServer.Stores.WsFederationClientStore.FindClientById(String clientId)
   at Rsk.WsFederation.Validation.WsFederationSignInRequestValidator.Validate(Uri requestUri, ClaimsPrincipal user)
   at Rsk.WsFederation.Endpoints.WsFederationEndpoint.ProcessSignIn(HttpContext context)
   at Rsk.WsFederation.Hosting.IdentityServerWsFederationMiddleware.Invoke(HttpContext context, IWsFederationEndpointRouter router, IMemoryCache cache, WsFederationOptions options)
[15:14:37 INF] Request finished HTTP/2 GET https://localhost:44310/wsfederation?wtrealm=urn%3Atestclient_wsfed_lokal_nicht_existent&wa=wsignin1.0&wreply=https%3A%2F%2Flocalhost%3A57950%2Fsignin-wsfed&wctx=CfDJ8PajCRRixNFEi8gcE_mR
-YLqKIxle1VLuXIuYwsX1m72LLU8m7Ra3sj9RqeNllSfik7ISweZ1Kjj3-qPjfjlulAdSt6WsqJAS-FOZDjz8XB5fEbJZO_TpL_VG61XAwBpLhxX2SM4fFGxBo-o56VXKNDTM3tcoHOH0oMSzfj6qO63F83PVJevDsYyPOOdab1OCc1Zer-nfpuiqeF-ExZDJvkf6Hd1yT62G3E0JcK2BX7g6VQiNcTRzEenY
xyo-Mw8yQ - - - 500 - - 184.2528ms
```

If needed I can also provide our license key to get support.

**Comment by AndersAbel** [comment]
The WS-Federation plugin is provided and supported by our partner Rock Solid Knowledge. Please contact them for questions about the WS-Federation plugin.

**Comment by DanielHabenicht** [comment]
Alright, will do thanks anyway.
