### ISSUE TITLE
ArgumentNullException: Value cannot be null. (Parameter 'redirectUrl')

### ISSUE THREAD

**Issue by DKANomad** [DuendeSoftware/Support#1010]
**Which version of Duende IdentityServer are you using?**
6.3.5
**Which version of .NET are you using?**
.NET 7.0.14
**Describe the bug**
When attempting to use well oidc-client-ts I am getting this excpetion: `ArgumentNullException: Value cannot be null. (Parameter 'redirectUrl')`

**To Reproduce**
Add a client that will be used for OIDC
```
new Client
{
    ClientId = "client",
    ClientName = "Web Client",
    ClientSecrets = new List<Secret> { new Secret("secret".Sha256()) },
    AllowedGrantTypes = GrantTypes.Code,
    RequireClientSecret = false,
    RedirectUris = { "http://localhost:5173/login-callback" },
    PostLogoutRedirectUris = { "http://localhost:5173/logout-callback" },
    AllowedCorsOrigins = {"http://localhost:5173"},
    AllowedScopes =
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        IdentityServerConstants.StandardScopes.Email,
        "api"
    },
    AllowAccessTokensViaBrowser = true,
    RequireConsent = false,
    AccessTokenLifetime = 3600,
    IdentityTokenLifetime = 3600,
    AuthorizationCodeLifetime = 3600,
    RefreshTokenExpiration = TokenExpiration.Sliding,
    AllowOfflineAccess = true,
},
```
implement a basic config in the react app using oidc-client-ts
```
this.userMgr = new UserManager({
        authority: 'https://localhost:7091',
        client_id: 'client',
        redirect_uri: 'http://localhost:5173/login-callback',
        response_type: 'code',
        scope: 'openid profile email offline_access api',
        post_logout_redirect_uri: 'http://localhost:5173/logout-callback',
        userStore: new WebStorageStateStore({ store: window.localStorage }),
    });
```
Call signinRedirect via frontend
```
  async login() {
    return await this.userMgr.signinRedirect();
  }
```

**Expected behavior**
Redirects to my defined login page which will handle login and redirect

**Log output/exception with stacktrace**

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: Value cannot be null. (Parameter 'redirectUrl')
         at Duende.IdentityServer.Endpoints.Results.AuthorizeInteractionPageResult..ctor(ValidatedAuthorizeRequest request, String redirectUrl, String returnUrlParameterName) in /_/src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs:line 40
         at Duende.IdentityServer.Endpoints.Results.LoginPageResult..ctor(ValidatedAuthorizeRequest request, IdentityServerOptions options) in /_/src/IdentityServer/Endpoints/Results/LoginPageResult.cs:line 22
         at Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 130
         at Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 158
         at Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 63
         at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 101
         at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 117
         at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 50
         at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Additional context**

I have validated that the issue is caused by the casing of `IdentityServer` and `oidc-client-ts` being different. I have used these libraries together in the past as part of older .NET react templates, wondering why this is now an issue. Is there a way to override the casing used by IdentityServer or a workaround?

**Comment by DKANomad** [comment]
Not entirely sure why/how but it is now working.
