### ISSUE TITLE
FileNotFoundException: Microsoft.Extensions.Identity.Core after Windows Update

### ISSUE THREAD

**Issue by bram96** [DuendeSoftware/Support#1022]
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
.NET 6
**Describe the bug**

After the past two Windows Updates our Identity Server site hosted in IIS stopped functioning correctly. The login works as expected but the userinfo request fails wit a 500 error due to `Microsoft.Extensions.Identity.Core` not being found.

This has happened after the Windows updates in October and November and I'm not sure how to work around this. Do you have any suggestion?

**To Reproduce**

Haven't been able to structurally reproduce this (seems to be happening after Windows Update)

**Expected behavior**

I would expect the app to not fail with a not found exception but just work.

**Log output/exception with stacktrace**

```
[04:48:29 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware - Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.UserInfoEndpoint for /connect/userinfo
[04:48:29 Information] Duende.IdentityServer.Events.DefaultEventService - {"Details":"System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Identity.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.\r\nFile name: 'Microsoft.Extensions.Identity.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'\r\n   at Duende.IdentityServer.Validation.TokenValidator.ValidateAccessTokenAsync(String token, String expectedScope)\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Duende.IdentityServer.Validation.TokenValidator.ValidateAccessTokenAsync(String token, String expectedScope)\r\n   at Duende.IdentityServer.Validation.UserInfoRequestValidator.ValidateRequestAsync(String accessToken) in /_/src/IdentityServer/Validation/Default/UserInfoRequestValidator.cs:line 52\r\n   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessUserInfoRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 81\r\n   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 62\r\n   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121","Category":"Error","Name":"Unhandled Exception","EventType":"Error","Id":3000,"Message":"Could not load file or assembly 'Microsoft.Extensions.Identity.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.","ActivityId":"80002a9d-0000-b300-b63f-84710c7967bb","TimeStamp":"2023-12-01T04:48:29.6593040Z","ProcessId":8660,"LocalIpAddress":"172.28.1.135:443","RemoteIpAddress":"172.28.129.222","$type":"UnhandledExceptionEvent"}
[04:48:29 Fatal] Duende.IdentityServer.Hosting.IdentityServerMiddleware - Unhandled exception: Could not load file or assembly 'Microsoft.Extensions.Identity.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Identity.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Identity.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Duende.IdentityServer.Validation.TokenValidator.ValidateAccessTokenAsync(String token, String expectedScope)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Duende.IdentityServer.Validation.TokenValidator.ValidateAccessTokenAsync(String token, String expectedScope)
   at Duende.IdentityServer.Validation.UserInfoRequestValidator.ValidateRequestAsync(String accessToken) in /_/src/IdentityServer/Validation/Default/UserInfoRequestValidator.cs:line 52
   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessUserInfoRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 81
   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 62
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
```

**Additional context**

**Comment by josephdecock** [comment]
This is a pretty unusual issue, but a few things I would try:

1. Ensure you are on the same version of all the Microsoft.IdentityModel.* nuget packages, and update them all to the latest version under the 6.x.x major version (6.33.0)
2. Do the same for all the ASP.NET authentication handlers (e.g., Microsoft.AspNetCore.Authentication.OpenIdConnect), and ASP.NET Identity (Microsoft.Extensions.Identity.*) Their latest 6.x release is 6.0.25.
3. Look for other packages you're using that depend on those libraries, and make sure they are not pulling in other versions
4. Explicitly install the ASP.NET Identity packages Microsoft.Extensions.Identity.Core (I would take version 6.0.25) and possibly Microsoft.Extensions.Identity.Stores (same version). 

If none of that works, I would start thinking about taking larger action. OS Updates aren't supposed to cause issues like this, but since that's what seems to be happening, I would start thinking about trying to prevent changes to the OS from leaking into the running application. One option would be to explore using containerization - there are windows containers for Docker these days, so you could in theory ship your IdentityServer as a windows container image.

**Comment by AndersAbel** [comment]
@bram96 Did you have any success in solving this? Are there any more questions or can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
