### ISSUE TITLE
Key Management folder access

### ISSUE THREAD

**Issue by bjschnell** [DuendeSoftware/Support#1027]
**Which version of Duende IdentityServer are you using?**
6.3.6

**Which version of .NET are you using?**
.Net 8 (previously 7.0)

**Describe the bug**
With key management disabled, our deployment of IdentityServer6 still attempts to write to the folder /keys on a Linux deployment, and as a result, FileSystemKeyStore.cs throws an error trying to write to a folder that it does not have access to. When run on Windows, the /keys folder is not generated and the error never appears.

**To Reproduce**

Run ASP server with IS6 deployed on a Linux device (potentially containerized via docker). Permit-only read operations on the deployment parent folder. 

**Expected behavior**

Since Automatic key management is disabled, no keys folder should be generated and no attempt to write to the keys folder should occur.

**Log output/exception with stacktrace**

```
at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
--
at Duende.IdentityServer.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs:line 68
at Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri) in /_/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs:line 415
at Duende.IdentityServer.Services.DefaultKeyMaterialService.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/DefaultKeyMaterialService.cs:line 128
at Duende.IdentityServer.Services.KeyManagement.AutomaticKeyManagerKeyStore.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/AutomaticKeyManagerKeyStore.cs:line 112
at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 98
at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysInternalAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 210
at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysFromStoreAsync(Boolean cache) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 496
at Duende.IdentityServer.Services.KeyManagement.FileSystemKeyStore.LoadKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/FileSystemKeyStore.cs:line 80
System.IO.IOException: Read-only file system : '/home/test/services/main/keys'
```

**Additional context**

**Comment by josephdecock** [comment]
Thanks for getting in touch with this bug report. I'm not sure how it is possible for the behavior that you're describing to happen though. Here's the GetValidationKeysAsync method that is being invoked in the middle of that call stack:

```cs
    public async Task<IEnumerable<SecurityKeyInfo>> GetValidationKeysAsync()
    {
        if (!_options.Enabled)
        {
            return Enumerable.Empty<SecurityKeyInfo>();
        }
            
        var containers = await _keyManager.GetAllKeysAsync();
        var keys = containers.Select(x => new SecurityKeyInfo
        {
            Key = x.ToSecurityKey(),
            SigningAlgorithm = x.Algorithm
        });
        return keys.ToArray();
    }
```

We should be bailing out and returning no records when we see that the option is disabled, and never getting into the key manager call which ultimately tries to read and write to disk. It seems like somehow the automatic key management option flag isn't actually disabled.

**Comment by bjschnell** [comment]
Interestingly, as of right now, we might have had a bad build that didn't contain disabling key management that was flagged as having the appropriate changes. If we can repro this issue I will reopen it if it does occur. Sorry!
