### ISSUE TITLE
Angular & ASP.NET Core 8 Azure AD Authentication not working.

### ISSUE THREAD

**Issue by nikunj231991** [DuendeSoftware/Support#1035]
**Which version of Duende IdentityServer are you using?**
6.3.6
**Which version of .NET are you using?**
.Net Core 8
**Describe the bug**
We are implementing Duende Identity Server and we have issue in Azure AD Authnetication. We are getting /signin-microsoft not found error.

And we have followed below article.

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-8.0

**To Reproduce**

Steps to reproduce the behavior.

I have create Angular & ASP.Net Core template project from Visual Studio 2022. And then have tried to integrate Microsoft Account with below code
 
builder.Services.AddDefaultIdentity<ApplicationUser>(options => {
        options.SignIn.RequireConfirmedAccount = true;
    })
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>();

builder.Services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
builder.Services.AddAuthentication(options =>
{
    //options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
    .AddIdentityServerJwt()
.AddMicrosoftAccount(microsoftOptions =>
{
    microsoftOptions.ClientId = builder.Configuration["Authentication:Microsoft:ClientId"];
    microsoftOptions.ClientSecret = builder.Configuration["Authentication:Microsoft:ClientSecret"];
    microsoftOptions.AuthorizationEndpoint = "https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/oauth2/v2.0/authorize";
    microsoftOptions.TokenEndpoint = "https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/oauth2/v2.0/token";
});

and then after login getting below error in console

main.ts:19 ERROR Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'signin-microsoft'
Error: NG04002: Cannot match any routes. URL Segment: 'signin-microsoft'
    at ApplyRedirects.noMatchError (router.mjs:3656:16)
    at router.mjs:3638:28
    at catchError.js:10:39
    at OperatorSubscriber._error (OperatorSubscriber.js:23:21)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:23896:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23896:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:24197:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)

**Expected behavior**

It should login with Azure AD account

**Comment by nikunj231991** [comment]
its working after setting below code under AddMicrosoftAccount

microsoftOptions.CallbackPath = "/Identity/Account/ExternalLogin?handler=Callback";
