### ISSUE TITLE
/connect/token returns a 500 if client_secret contains invalid form characters

### ISSUE THREAD

**Issue by roemba** [DuendeSoftware/Support#110]
**Which version of Duende IdentityServer are you using?**
6.1.1

**Which version of .NET are you using?**
6.0.301

**Describe the bug**

If the `/connect/token` endpoint receives a POST request with Content-Type = `application/x-www-form-urlencoded` and body `grant_type=client_credentials&client_id=test&client_secret=%00`, the endpoint throws an `InvalidDataException` and returns a 500.

**To Reproduce**

Easiest is to use `curl` to reproduce:
`curl -d "grant_type=client_credentials&client_id=test&client_secret=%00" -H "Content-Type: application/x-www-form-urlencoded" -X POST https://<identityserver_url>/connect/token`

**Expected behavior**

The `/connect/token` endpoint should return a 400, because this problem only occurs if there is a `%00` character in the `client_secret`, and is therefore not a fault of the server but of the client.

**Log output/exception with stacktrace**

```
 [FTL] Unhandled exception: The form value contains invalid characters. <Duende.IdentityServer.Hosting.IdentityServerMiddleware>
System.IO.InvalidDataException: The form value contains invalid characters.
 ---> System.InvalidOperationException: The path contains null characters.
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeCore(Int32& sourceIndex, Int32& destinationIndex, Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeInPlace(Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.GetDecodedString(ReadOnlySpan`1 readOnlySpan)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.GetDecodedString(ReadOnlySpan`1 readOnlySpan)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValuesFast(ReadOnlySpan`1 span, KeyValueAccumulator& accumulator, Boolean isFinalBlock, Int32& consumed)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValues(ReadOnlySequence`1& buffer, KeyValueAccumulator& accumulator, Boolean isFinalBlock)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Duende.IdentityServer.Validation.PostBodySecretParser.ParseAsync(HttpContext context) in /_/src/IdentityServer/Validation/Default/PostBodySecretParser.cs:line 60
   at Duende.IdentityServer.Validation.SecretParser.ParseAsync(HttpContext context) in /_/src/IdentityServer/Validation/Default/SecretParser.cs:line 45
   at Duende.IdentityServer.Validation.ClientSecretValidator.ValidateAsync(HttpContext context) in /_/src/IdentityServer/Validation/Default/ClientSecretValidator.cs:line 59
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 80
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 72
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 98
```

**Additional context**

The problem seems to occur in [PostBodySecretParser](https://github.com/DuendeSoftware/IdentityServer/blob/ffa4da997b44dcb32103bb26a919fb14cd1cf0f5/src/IdentityServer/Validation/Default/PostBodySecretParser.cs), line 60:

```csharp
var body = await context.Request.ReadFormAsync();
```

`ReadFormAsync` can throw an `InvalidDataException` if the form data contains invalid characters, but this is not caught anywhere in `PostBodySecretParser` or any of the methods calling it, causing it to bubble up and result in a 500. A simple fix would be to add a try/catch around this `ReadFormAsync` call and probably log an error and return `null` if the `InvalidDataException` occurs.

This bug seems similar to https://github.com/IdentityServer/IdentityServer4/issues/5128, but that bug was thought to be fixed on the ASP.NET side. However, the ASP.NET developers only changed the exception from an `InvalidOperationException` to an `InvalidDataException` such that it can be caught by the MVC body parsing middleware. It seems that this middleware is not in effect for the IdentityServer endpoints since the body is parsed by IdentityServer itself in `PostBodySecretParser`. Therefore, the bug still persists in the `/connect/token` IdentityServer endpoint, and perhaps also in other IdentityServer endpoints.

**Comment by brockallen** [comment]
PR submitted. Thanks.

**Comment by roemba** [comment]
Thanks for the quick investigation and PR 😄
