### ISSUE TITLE
Refresh token not valid when moving to Docker Container

### ISSUE THREAD

**Issue by remonlucassen** [DuendeSoftware/Support#1115]
Hi all,

<PackageReference Include="Duende.IdentityServer" Version="6.0.0" />

<TargetFramework>net7.0</TargetFramework>

We just moved the identity server to a docker container.
now the refresh token can't be found.

we store the data protection keys in redis

and both load the same keys on startup

when validating against a IIS hosted identityServer the token validates
When validating against a DockerHosted identityserver it failes

the token was requiested at the IIS hosted one.

2024-02-14 19:45:55 DBG [Duende.IdentityServer.EntityFramework.Stores.PersistedGrantStore] "***C0B7D4C4FA4C79041614D0E5464085D1E21732768A67135607EE4F7CD9A2E" found in database: True
2024-02-14 19:45:55 VRB [Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector] Performing unprotect operation to key {13aeaac1-bc81-46da-9785-f379b02f5108} with purposes "('/app/', 'PersistentGrantSerializer')".
2024-02-14 19:45:55 ERR [Duende.IdentityServer.Stores.DefaultRefreshTokenStore] Failed to deserialize JSON from grant store.
System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize[T](String json) in /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:line 111
   at Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemByHashedKeyAsync(String hashedKey) in /_/src/IdentityServer/Stores/Default/DefaultGrantStore.cs:line 137
2024-02-14 19:45:55 DBG [Duende.IdentityServer.Stores.DefaultRefreshTokenStore] "refresh_token" grant with value: "***06CDA1EA6EE589AE9833C588B4C42EB2C8EA6B7D6893B87603A8C292B71BF-1" not found in store.

We can't figure out what is causing this.

**Comment by remonlucassen** [comment]
Hi Roland Thanx This fixed our issue.
