### ISSUE TITLE
How to implement dynamic providers in Identity Server 7?

### ISSUE THREAD

**Issue by laki889** [DuendeSoftware/Support#1138]
Hi everyone!

I'm using Identity Server 7 and .NET 8 in my project (I migrated from an older setup - IS4 and .NET Core 3 to a newer version).
I'm having issues when implementing dynamic providers. This is probably not a bug - I just don't know how to move forward, so any help would be appreciated.

So, I followed both [Duende](https://docs.duendesoftware.com/identityserver/v7/ui/login/dynamicproviders/) and [Rsk ](https://www.identityserver.com/documentation/dynamic-authentication-providers/) docs related to dynamic identity providers.

I successfully implemented dynamic providers using JSON storage.
But, for my project, I need to utilize DB and I need help with that part.
I added and applied migrations for ConfigurationDbContext, then added this context to Startup.cs and did all other required steps.
Furthermore, I manually added 2 rows in the "IdentityProviders" table (based on JSON I used when working with JSON storage) - those are 2 external providers used on the project.

However, when all changes are deployed, the "well-know configuration" endpoint returns 503.
Also, I get this exception:
`Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Schemes'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Rsk.DynamicAuthenticationProviders.EntityFramework.Stores.AuthenticationSchemeStore.GetAllSchemes()
   at Rsk.DynamicAuthenticationProviders.DynamicAuthenticationSchemeProvider.GetRequestHandlerSchemesAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 51
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at YoMingo.Identity.Startup.<>c.<<Configure>b__5_1>d.MoveNext() in /src/Startup.cs:line 270
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
   at YoMingo.Identity.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in /src/Startup.cs:line 248
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
ClientConnectionId:b914ad3a-4ed7-4d26-ad51-68331c2a1683
Error Number:208,State:1,Class:16
ClientConnectionId before routing:1e95f0ec-ff16-49d3-98e6-ae305cc0c9e9
Routing Destination:b98aa65775e7.tr13302.centralus1-a.worker.database.windows.net,11053`

**Comment by laki889** [comment]
I didn’t resolve this issue, but I changed the implementation, making this issue obsolete (from my perspective).
To save everyone's time, I’ll close the ticket.
