### ISSUE TITLE
AddLocalApiAuthentication does not return 401

### ISSUE THREAD

**Issue by velcrowx** [DuendeSoftware/Support#1166]
**Which version of Duende IdentityServer are you using?**
6.3.7

**Which version of .NET are you using?**
6

I’m having a small issue getting the “services.AddLocalApiAuthentication()” to work as expected. I can see from the logs (see below) that it is doing validation on the JWT but it only logs it as INFORMATION. I was expecting that the request would be returned as a 401 UNAUTHORIZED. That does not happen, and the logic runs as if no auth was run at all. How do I configure the handler to reject the request instead of passing through?

```
2024-03-11 23:35:36.104 -04:00 [INF] JWT token validation error: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateTokenPayload(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters)
2024-03-11 23:35:36.120 -04:00 [INF] IdentityServerAccessToken was not authenticated. Failure message: expired_token
```

Thanks,
Courtney

**Comment by RolandGuijt** [comment]
Can you please check if you protected the endpoint that is being called with the Authorize attribute and the correct policy?

`[Authorize(IdentityServerConstants.LocalApi.PolicyName)]`
                
Also, your log indicates that the token is expired. Was that intentional to see if token validation is occurring?

**Comment by RolandGuijt** [comment]
Closing this issue for now, but feel free to re-open when there's something else to ask/report.
