### ISSUE TITLE
Exception: "A suitable constructor for type 'Duende.Bff.BffAuthenticationService' could not be located" when running on Kubernetes (.Net8)

### ISSUE THREAD

**Issue by phamtung1** [DuendeSoftware/Support#1188]
**Which version of Duende BFF are you using?**
2.2.0

**Which version of .NET are you using?**
net8.0

**Describe the bug**
We have a simple BFF app that previously functioned well with .NET 6 and Duende.BFF 1.2.3. Now, we're attempting to migrate it to .NET 8. 
After the upgrade, it works well during local testing with Visual Studio. However, when deployed to Kubernetes, it fails to access any of the URLs. It always throws this error "A suitable constructor for type 'Duende.Bff.BffAuthenticationService' could not be located". 
I've reviewed all the configurations but couldn't identify the problem.
```
 System.InvalidOperationException: A suitable constructor for type 'Duende.Bff.BffAuthenticationService' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, ServiceIdentifier, Type , CallSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor, ServiceIdentifier, CallSiteChain, Int32)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier, CallSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier, CallSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider )
         at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.GetAuthenticationService(HttpContext)
         at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.AuthenticateAsync(HttpContext, String )
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1)
```

**To Reproduce**
This is the current configuration.
```
builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();

builder.Services
	.AddBff(options =>
	{
		options.ManagementBasePath = "sample_text";
		options.EnableSessionCleanup = true;
		options.SessionCleanupInterval = TimeSpan.FromMinutes(5);
	})
	.AddEntityFrameworkServerSideSessions(options =>
                options.UseSqlServer("sample_text";));


builder.Services.AddAuthentication(options =>
	{
		options.DefaultScheme = "cookie";
		options.DefaultChallengeScheme = "oidc";
		options.DefaultSignOutScheme = "oidc";
	})
	.AddCookie("cookie", options =>
	{
		// rest omitted
	})
	.AddOpenIdConnect("oidc", options =>
	{
		options.Authority = "sample_text";

		options.ClientId = "sample_text";
		options.ClientSecret = "sample_text"
		options.ResponseType = "code";
		options.ResponseMode = "query";

		options.CallbackPath = "sample_text";
		options.SignedOutCallbackPath = "sample_text";
		options.RemoteSignOutPath = "sample_text";

		options.Scope.Clear();
		options.Scope.Add("openid");
		options.Scope.Add("profile");
		options.Scope.Add("offline_access");

		options.MapInboundClaims = false;
		options.GetClaimsFromUserInfoEndpoint = true;
		options.SaveTokens = true;

		options.NonceCookie.SecurePolicy = CookieSecurePolicy.Always;
		options.CorrelationCookie.SecurePolicy = CookieSecurePolicy.Always;
	});

// ...
app.UseHttpsRedirection();

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.UseRouting();
app.UseCookiePolicy(new CookiePolicyOptions
{
	Secure = CookieSecurePolicy.Always,
	MinimumSameSitePolicy = SameSiteMode.None,
	HttpOnly = HttpOnlyPolicy.Always
});

app.MapHealthChecks("sample_text");
app.UseAuthentication();
app.UseBff();
app.UseAuthorization();

app.MapBffManagementEndpoints();
app.MapRazorPages();

app.MapControllers();

app.MapFallbackToFile("index.html");

```

**Expected behavior**

I expect it to function error-free.

**Additional context**

If you have any advice please let me know. Thanks!

**Comment by josephdecock** [comment]
My first thought is that this is probably not specifically a kubernetes issue, but rather an issue with the image that k8s is managing. Maybe you need to update your docker image to make sure you have all the .net 8 dependencies.

**Comment by phamtung1** [comment]
Thanks, but we've already updated our dockerfile to .NET 8. The dockerfile is straightforward and includes only the essential dependencies, the .NET SDK, and ASP.NET. We also updated all dependencies in the web project. 

Could there be other potential causes for the issue?

**Comment by josephdecock** [comment]
The next thing I would do to troubleshoot this would be to try running in a linux environment, perhaps a vm or WSL. If you are able to reproduce the issue outside the container, that will help narrow down what is going wrong, and hopefully make it easier to iterate on possible solutions. And if doesn't reproduce outside the container, then that points to this being a container issue (despite your dockerfile being quite straightforward).

**Comment by phamtung1** [comment]
Thanks for your help! After futher investigation, I realised that issue really lies in our Dockerfile. In the dotnet publish command, the parameter **-p:PublishTrimmed=true** seems to have removed the Duende package. So removing this parameter fixed the issue, and everything's working well now. We haven't encountered any issues with this parameter before. Anyway, this gives me a good experience for troubleshooting the issue. Hopefully, it will be helpful for others who face similar problems.
