### ISSUE TITLE
RSA iqmp not inverse of q error when signing tokens

### ISSUE THREAD

**Issue by etneodeck** [DuendeSoftware/Support#1194]
Which version of Duende IdentityServer are you using?
6.3.8
Which version of .NET are you using?
.NET 7
Describe the bug
Hello, we are almost done with the process of upgrading IdentityServer 4 to Duende IdentityServer 6. The Identity App is running and opens as expected, however, we are having an issue with Signing Credentials
In our previous version of the app that uses IdentityServer4, we sign our credentials using the RsaSecurityKey approach, using the keyId and the following parameters: D, DP, DQ, Exponent, InverseQ, Modulus, P and Q. 
These all get stored into an RsaSecurityKey object and pass it to the builder as shown here:
```
// Get rsa security keys
var rsaSecurityKey = rsaSecurityService.GetSecurityKeys();
 
 
logger.LogInformation(rsaSecurityKey.KeyId);
 
// Add security key to identity server configuration
builder.AddSigningCredential(new SigningCredentials(rsaSecurityKey, SecurityAlgorithms.RsaSha256));
```
 
After upgrading the app to Duende IdentityServer 6, everytime a client tries to get a token from the identity server with the /token endpoint, we get the following error on our logs from the server:
 
We couldn’t find a lot of information related to this problem, so we were hoping if you could help us out with this error? Is there a new parameter or setting that we need to enter after the upgrade? Or is this signing method no longer supported?

To Reproduce
We simply just use the angular oidc client and try to login. The error occurs when trying to get the token, using the /token endpoint

Expected behavior
Receive the signed token from Identity Server

Log output/exception
```
[20:40:40 FTL] Unhandled exception: error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q
Interop+Crypto+OpenSslCryptographicException: error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q
   at Interop.Crypto.DecodePkcs8PrivateKey(ReadOnlySpan`1 source, EvpAlgorithmId algorithmId)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.ImportParameters(RSAParameters parameters)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.InitializeUsingRsaSecurityKey(RsaSecurityKey rsaSecurityKey, String algorithm)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter..ctor(SecurityKey key, String algorithm, HashAlgorithm hashAlgorithm, Boolean requirePrivateKey)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter..ctor(SecurityKey key, String algorithm, HashAlgorithm hashAlgorithm, HashAlgorithmName hashAlgorithmName, Boolean requirePrivateKey)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.CreateAsymmetricAdapter()
   at Microsoft.IdentityModel.Tokens.DisposableObjectPool`1.Allocate()
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Sign(Byte[] input)
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.CreateTokenPrivate(JObject payload, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, String compressionAlgorithm, IDictionary`2 additionalHeaderClaims, String tokenType)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.CreateToken(String payload, SigningCredentials signingCredentials, IDictionary`2 additionalHeaderClaims)
   at Duende.IdentityServer.Services.DefaultTokenCreationService.CreateJwtAsync(Token token, String payload, Dictionary`2 headerElements) in /_/src/IdentityServer/Services/Default/DefaultTokenCreationService.cs:line 139


```

**Comment by josephdecock** [comment]
This isn't a common error that we see, but my thought is that you you might need to update any Microsoft.IdentityModel.* dependencies in your IdentityServer. Do you have an explicit or transitive dependency on any of those packages?

**Comment by etneodeck** [comment]
Forgot to mention that the server is running in a Linux container, hosted in Kubernetes.

**Comment by etneodeck** [comment]
Installed version 6.10.0 of:

- Microsoft.IdentityModel.Tokens
- Microsoft.IdentityModel.Protocols
- Microsoft.IdentityModel.Protocols.OpenIdConnect

but still getting the same error message.

**Comment by leastprivilege** [comment]
This seems to be a problem within the Microsoft IdentityModel library. Could you open an issue with them here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues

**Comment by etneodeck** [comment]
[Ticket #2554 ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2554) was opened as you recommended.

**Comment by AndersAbel** [comment]
This could also indicate a problem with your key. Previous versions of OpenSsl would recompute the iqmp parameter if it was incorrect while current versions of OpenSsl blocks those keys.

I would recommend validating your key material using OpenSsl as outlined here: https://cloud.google.com/load-balancing/docs/ssl-certificates/troubleshooting#private_key_cannot_be_parsed

**Comment by etneodeck** [comment]
Please, proceed to close this ticket since we solved the issue by creating a new key and use Json Web Tokens instead.

Thank you.
.


Respectfully,



 [cid:807d1299-4605-4bd8-8244-58fcc15cec24]

This E-mail and any files transmitted with it are confidential, may contain sensitive information, and are intended solely for the use of the individual or entity to whom they are addressed. If you have received this E-mail in error, please notify the sender by reply E-mail immediately and destroy all copies of the E-mail and any attachments.

________________________________
