### ISSUE TITLE
PersistedGrantsDbContext database not properly created

### ISSUE THREAD

**Issue by nicolas-garcia** [DuendeSoftware/Support#122]
**Which version of Duende IdentityServer are you using?**

6.1.2 (I tried with version 6.0.0 too)

**Which version of .NET are you using?**

6.0.x

**Describe the bug**

We are currently in the process of migrating our backend from .netcore 3.1 to .net6.
We were using IdentityServer4 4.1.x until now, and moving to Duende.IdentityServer for .net6 support, with a license.
We are using EntityFramework.

After following your [migration procedure](https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v4_to_dis_v6/), we are now struggling with an issue regarding the `PersistedGrandDbContext`.

When the project start, we are calling some code to ensure the database is created and/or migrated to the latest migration.
When we were using IdentityServer4 4.1, the code would create or migrate the `PersistedGrants` database and all the required tables.
After upgrading to Duende.IdentityServer 6.x, the database is created, but none of the table are created in the database.

Relevant code
```cs

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        // ...
       services.AddIdentityServer()
               .AddOperationalStore<PersistedGrantDbContext>(cfg => 
               {
                    cfg.ConfigureDbContext = builder =>
                    {
                        // sqlInfo is a custom object built against the appsettings
                        builder.UseSqlServer($"{sqlInfo.ToConnectionString()};Database=PersistedGrants",
                                            opts =>
                                            {
                                                opts.EnableRetryOnFailure(3);
                                                opts.MigrationsAssembly(GetType().Assembly.GetName().Name);
                                            });
                    };
               });
    }
}

// The following code is called by the host once the IWebHost is built
public class DatabaseHelper
{
    public async Task EnsureCreatedAsync(PersistedGrantDbContext context)
    {
        await context.Database.CanConnectAsync();
        await databaseFacade.MigrateAsync();
    }
}

```

**To Reproduce**

Starting our project, a database with tables is expected to be found.

**Expected behavior**

The database `PersistedGrants` and all the tables are supposed to be created.

**Log output/exception with stacktrace**

Log output from our project
```
info: Duende.IdentityServer.Startup[0]
      Starting Duende IdentityServer version 6.1.2+0222403973d77e72087ead9adc5806053d0b45fa (.NET 6.0.7)
warn: Duende.License[0]
      You do not have a valid license key for the Duende software. This is allowed for development and testing scenarios. If you are running in production you are required to have a licensed version. Please start a conversation with us: https://duendesoftware.com/contact
dbug: Duende.IdentityServer.Startup[0]
      Custom IssuerUri set to http://localhost:4000
info: Duende.IdentityServer.Startup[0]
      Using the default authentication scheme Cookies for IdentityServer
dbug: Duende.IdentityServer.Startup[0]
      Using Cookies as default ASP.NET Core scheme for authentication
dbug: Duende.IdentityServer.Startup[0]
      Using Identity.External as default ASP.NET Core scheme for sign-in
dbug: Duende.IdentityServer.Startup[0]
      Using Cookies as default ASP.NET Core scheme for sign-out
dbug: Duende.IdentityServer.Startup[0]
      Using **** as default ASP.NET Core scheme for challenge
dbug: Duende.IdentityServer.Startup[0]
      Using **** as default ASP.NET Core scheme for forbid
Hosting environment: DevelopmentOSX
Content root path: ****
Now listening on: http://localhost:4000
Application started. Press Ctrl+C to shut down.
```

As you can seen no error so far.

<details>
   <summary>When I try to access the discovery url, of course I have an error. Here is the log (basically showing that the table 'Keys' is not found in the database)</summary>

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:4000/.well-known/openid-configuration - -
dbug: Duende.IdentityServer.Startup[0]
      Login Url: /Account/Login
dbug: Duende.IdentityServer.Startup[0]
      Login Return Url Parameter: ReturnUrl
dbug: Duende.IdentityServer.Startup[0]
      Logout Url: /Account/Logout
dbug: Duende.IdentityServer.Startup[0]
      ConsentUrl Url: /consent
dbug: Duende.IdentityServer.Startup[0]
      Consent Return Url Parameter: returnUrl
dbug: Duende.IdentityServer.Startup[0]
      Error Url: /home/error
dbug: Duende.IdentityServer.Startup[0]
      Error Id Parameter: errorId
dbug: Duende.IdentityServer.Hosting.EndpointRouter[0]
      Request path /.well-known/openid-configuration matched to endpoint type Discovery
dbug: Duende.IdentityServer.Hosting.EndpointRouter[0]
      Endpoint enabled: Discovery, successfully created handler: Duende.IdentityServer.Endpoints.DiscoveryEndpoint
info: Duende.IdentityServer.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
dbug: Duende.IdentityServer.Endpoints.DiscoveryEndpoint[0]
      Start discovery request
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [k].[Id], [k].[Algorithm], [k].[Created], [k].[Data], [k].[DataProtected], [k].[IsX509Certificate], [k].[Use], [k].[Version]
      FROM [Keys] AS [k]
      WHERE [k].[Use] = N'signing'
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Keys'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      ClientConnectionId:2f71d357-de90-4482-a68c-bcca5e0f8784
      Error Number:208,State:1,Class:16
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Keys'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      ClientConnectionId:2f71d357-de90-4482-a68c-bcca5e0f8784
      Error Number:208,State:1,Class:16
info: Duende.IdentityServer.Events.DefaultEventService[0]
      {
        "Details": "Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name \u0027Keys\u0027.\n   at Microsoft.Data.SqlClient.SqlCommand.\u003C\u003Ec.\u003CExecuteDbDataReaderAsync\u003Eb__207_0(Task\u00601 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask\u00602.InnerInvoke()\n   at System.Threading.Tasks.Task.\u003C\u003Ec.\u003C.cctor\u003Eb__272_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task\u0026 currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location ---\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable\u00601.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.\u003C\u003Ec__DisplayClass33_0\u00602.\u003C\u003CExecuteAsync\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func\u00604 operation, Func\u00604 verifySucceeded, TState state, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func\u00604 operation, Func\u00604 verifySucceeded, TState state, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func\u00604 operation, Func\u00604 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable\u00601.AsyncEnumerator.MoveNextAsync()\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable\u00601 source, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable\u00601 source, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable\u00601 source, CancellationToken cancellationToken)\n   at Duende.IdentityServer.EntityFramework.Stores.SigningKeyStore.LoadKeysAsync() in /_/src/EntityFramework.Storage/Stores/SigningKeyStore.cs:line 64\n   at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetKeysFromStoreAsync(Boolean cache) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 428\n   at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysInternalAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 108\n   at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 95\n   at Duende.IdentityServer.Services.KeyManagement.AutomaticKeyManagerKeyStore.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/AutomaticKeyManagerKeyStore.cs:line 105\n   at Duende.IdentityServer.Services.DefaultKeyMaterialService.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/DefaultKeyMaterialService.cs:line 112\n   at Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri) in /_/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs:line 109\n   at Duende.IdentityServer.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs:line 65\n   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 98\nClientConnectionId:2f71d357-de90-4482-a68c-bcca5e0f8784\nError Number:208,State:1,Class:16",
        "Category": "Error",
        "Name": "Unhandled Exception",
        "EventType": "Error",
        "Id": 3000,
        "Message": "Invalid object name \u0027Keys\u0027.",
        "ActivityId": "0HMJ4M70PRDUD:00000002",
        "TimeStamp": "2022-07-13T09:26:25.159657Z",
        "ProcessId": 23820,
        "LocalIpAddress": "127.0.0.1:4000",
        "RemoteIpAddress": "127.0.0.1"
      }
crit: Duende.IdentityServer.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: Invalid object name 'Keys'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Keys'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Duende.IdentityServer.EntityFramework.Stores.SigningKeyStore.LoadKeysAsync() in /_/src/EntityFramework.Storage/Stores/SigningKeyStore.cs:line 64
         at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetKeysFromStoreAsync(Boolean cache) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 428
         at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysInternalAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 108
         at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 95
         at Duende.IdentityServer.Services.KeyManagement.AutomaticKeyManagerKeyStore.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/AutomaticKeyManagerKeyStore.cs:line 105
         at Duende.IdentityServer.Services.DefaultKeyMaterialService.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/DefaultKeyMaterialService.cs:line 112
         at Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri) in /_/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs:line 109
         at Duende.IdentityServer.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs:line 65
         at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 98
      ClientConnectionId:2f71d357-de90-4482-a68c-bcca5e0f8784
      Error Number:208,State:1,Class:16
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Keys'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Duende.IdentityServer.EntityFramework.Stores.SigningKeyStore.LoadKeysAsync() in /_/src/EntityFramework.Storage/Stores/SigningKeyStore.cs:line 64
         at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetKeysFromStoreAsync(Boolean cache) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 428
         at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysInternalAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 108
         at Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 95
         at Duende.IdentityServer.Services.KeyManagement.AutomaticKeyManagerKeyStore.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/KeyManagement/AutomaticKeyManagerKeyStore.cs:line 105
         at Duende.IdentityServer.Services.DefaultKeyMaterialService.GetValidationKeysAsync() in /_/src/IdentityServer/Services/Default/DefaultKeyMaterialService.cs:line 112
         at Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri) in /_/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs:line 109
         at Duende.IdentityServer.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs:line 65
         at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 98
         at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 113
         at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
         at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
         at ***.Backend.Identity.MultiTenant.Middlewares.TenantResolverMiddleware.InvokeAsync(HttpContext context, ITenantAccessor tenantAccessor) in /Users/***/Sources/***/Sources/***.Backend.Identity/MultiTenant/Middlewares/TenantResolverMiddleware.cs:line 20
         at ***.Backend.RobotsTxt.RobotsTxtMiddleware.InvokeAsync(HttpContext context) in /Users/***/Sources/***/Sources/***.Backend.RobotsTxt/RobotsTxtMiddleware.cs:line 37
         at ***.IdentityProvider.Gateway.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /Users/***/Sources/***/Sources/***.IdentityProvider.Gateway/Startup.cs:line 170
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
      ClientConnectionId:2f71d357-de90-4482-a68c-bcca5e0f8784
      Error Number:208,State:1,Class:16
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:4000/.well-known/openid-configuration - - - 500 - text/html;+charset=utf-8 741.5399ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:4000/favicon.ico - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.ico'. Physical path: '/Users/***/Sources/***/Sources/***.IdentityProvider.Gateway/wwwroot/favicon.ico'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:4000/favicon.ico - - - 0 16958 image/x-icon 9.2921ms

```
</details>

Since our code doesn't want to properly create the database, I tried with EF tools:

`dotnet ef database update -c PersistedGrantDbContext --verbose`

<details>
    <summary>Here is the result</summary>

```
Using assembly '***.IdentityProvider.Public'.
Using startup assembly '***.IdentityProvider.Public'.
Using application base '/Users/***/Sources/***/Sources/***.IdentityProvider.Public/bin/Debug/net6.0'.
Using working directory '/Users/***/Sources/***/Sources/***.IdentityProvider.Public'.
Using root namespace '***.IdentityProvider.Public'.
Using project directory '/Users/***/Sources/***/Sources/***.IdentityProvider.Public/'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'PersistedGrantDbContextFactory'.
Found DbContext 'PersistedGrantDbContext'.
Found IDesignTimeDbContextFactory implementation 'DesignTimeMultiTenantUserDbContextFactory'.
Found DbContext 'MultiTenantUserDbContext'.
Finding application service provider in assembly '***.IdentityProvider.Public'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'PersistedGrantDbContextFactory'.
Using context 'PersistedGrantDbContext'.
Finding design-time services referenced by assembly '***.IdentityProvider.Public'...
Finding design-time services referenced by assembly '***.IdentityProvider.Public'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly '***.IdentityProvider.Public'...
No design-time services were found.
Executed DbCommand (16ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
No migrations were applied. The database is already up to date.
Done.
```

</details>

I checked all your GitHub repo for a similar issue but found nothing, so I guess I am doing something wrong here, maybe you can help me to figure it out?

Thank you very much!

**Comment by nicolas-garcia** [comment]
Thank you for the quick reply.

So I found the issue, and of course it was on my side.
Your demo project helped me to figure what was the issue.

The following line in my startup :
```cs
opts.MigrationsAssembly(GetType().Assembly.GetName().Name);
```

Actually, we use a specific design for our projects, where the startup project is different from the one having all the migrations, and the Startup.cs.

```
Solution
|
| - MyProject // Project between ConsoleHost and ServiceFabricHost
|    L Startup.cs
|    L Migrations/
| - MyProject.ConsoleHost // Startup project
|    L ConsoleHostStartup.cs // inherit from MyProject.Startup
| - MyProject.ServiceFabricHost
|    L ServiceFabricHostStartup.cs
```

So the actual type resolve at runtime for the `GetType()` is not the one holding all the migrations.
Replacing this line with fixed my issue:
```cs
opts.MigrationsAssembly(typeof(Startup).Assembly.GetName().Name);
```

Anyway, thank you for helping me out, have a nice day.
