### ISSUE TITLE
Value cannot be null. (Parameter 'subject') error when validating refresh token

### ISSUE THREAD

**Issue by justintoth** [DuendeSoftware/Support#1225]
**Which version of Duende IdentityServer are you using?**
7.0.0

**Which version of .NET are you using?**
8

**Describe the bug**

After upgrading from Identity Server4 to Duende Identity Server 7, I'm seeing a lot of "Value cannot be null. (Parameter 'subject')" errors in the logs when our mobile apps call the connect/token endpoint. As this is Duende code that is erroring, I'm not sure how to proceed with troubleshooting this one.

```
var isActiveCtx = new IsActiveContext(
            refreshToken.Subject,
            client,
            IdentityServerConstants.ProfileIsActiveCallers.RefreshTokenValidation);
```

However, I'm not seeing anyone else reporting this issue, which makes me think it's probably some sort of configuration issue that I'm missing after the upgrade. I'd appreciate some guidance on how to properly set the subject of the refresh token.

**To Reproduce**

I'm unsure of the exact steps, but it's related to validating the refresh token when the connect/token endpoint is called.

**Expected behavior**

No errors are thrown when validating refresh tokens.

**Log output/exception with stacktrace**

```
Source:Duende.IdentityServer
Stack Trace:
System.ArgumentNullException: Value cannot be null. (Parameter 'subject')
   at Duende.IdentityServer.Models.IsActiveContext..ctor(ClaimsPrincipal subject, Client client, String caller) in /_/src/IdentityServer/Models/Contexts/IsActiveContext.cs:line 23
   at Duende.IdentityServer.Services.DefaultRefreshTokenService.ValidateRefreshTokenAsync(String tokenHandle, Client client) in /_/src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs:line 138
   at Duende.IdentityServer.Validation.TokenRequestValidator.ValidateRefreshTokenRequestAsync(NameValueCollection parameters) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 677
   at Duende.IdentityServer.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 273
   at Duende.IdentityServer.Validation.TokenRequestValidator.ValidateRequestAsync(TokenRequestValidationContext context) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 196
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 120
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 81
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 106
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 128
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 51
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Rpr.Web.ExceptionLoggingMiddleware.InvokeAsync(HttpContext httpContext) in C:\agent1\_work\1\s\Libraries\Web\Middleware\ExceptionLoggingMiddleware.cs:line 25
Authorization:Basic bW9iaWxlX2NsaWVudDo5OUUyQTk2MC1DRkFDLTRGMDEtQjU0OC0wQjU1NUFCMUVBQUE=
Body:grant_type=refresh_token&scope=openid+email+rpr_contact+rpr_current_user+rpr_permissions+rpr_roles+rpr_mobile_device+mobile_api_access+auth_api_access+offline_access&refresh_token=DA63BCE7BA8C2F64DD4572153078762D69F48E2E02AC177F5C327062CC967131-1&device_id=789DDBA0-6A07-4BB4-BC0A-766FF95EE09D
Device:OS: ios 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "ios_arm64", Device: iPhone15,2, App Version: 3.17.5
Method:POST
Path:/connect/token
```

**Comment by justintoth** [comment]
I was able to get this resolved. We have a custom refresh token service and we weren't setting the Subject on the RefreshToken instance from the request.
