### ISSUE TITLE
System.Security.Cryptography.CryptographicException: The payload was invalid.  - Azure Entra ID Logout failure

### ISSUE THREAD

**Issue by gizmohd** [DuendeSoftware/Support#1311]
**Which version of Duende IdentityServer are you using?** 
7.0.5

**Which version of .NET are you using?**
8.0

**Describe the bug**
When using Azure Entra ID, as the upstream authentication, login works fine but when a user attempts to log out, the identity server throws an error 
 
`System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning`

**Expected behavior**

User should be logged out successfully and without error... 

**Log output/exception with stacktrace**

```

System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect(String protectedText, String purpose) in /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:line 100
   at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect(String protectedText) in /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:line 83
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleSignOutCallbackAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 51
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)


```
 Oidc Settings configuration for EntraID:
```
 auth.AddOpenIdConnect("oidc-adfs", "Corporate", options =>
 {
   options.RemoteAuthenticationTimeout = TimeSpan.FromMinutes(3);
   options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
   options.SignOutScheme = IdentityServerConstants.SignoutScheme;
   options.CallbackPath = "/signin-oidc-adfs";
   options.Authority = $"https://login.microsoftonline.com/{Configuration["Authentication:ADFS:TenantId"]}";

   options.ClientId = Configuration["Authentication:ADFS:ApplicationId"];
   options.Scope.Add("adfs");
   options.Scope.Add("email");
   options.Scope.Add("phone");
   options.Scope.Add("groups");
   options.Scope.Add("address");
   options.Scope.Add("profile");
   options.Scope.Add("openid");
   options.Scope.Add("groups.read");
   options.Scope.Add("user.read");
   options.GetClaimsFromUserInfoEndpoint = true;

 });
```

**Comment by RolandGuijt** [comment]
@gizmohd Did the hints help you out? If so I would like to close this issue.

**Comment by RolandGuijt** [comment]
Additionally: since there are issues around data protection in your stack trace, you could check our [data protection guide](https://docs.duendesoftware.com/identityserver/v7/deployment/data_protection/) against your setup.

**Comment by gizmohd** [comment]
Thank you for your response... I did attempt to migrate over to the 'new'
process you mentioned and ended up with a different error... (an
incompatibility with WSFED plugin from identityserver.com).   So i ended up
rolling that back...

**Comment by gizmohd** [comment]
That was the first thing I checked and didnt do anything different.  as It
was already configured per the setup recommended in the guide.

**Comment by jaycostales** [comment]
I'm starting to get a lot of these for the last 2 weeks. I have also lost my previous ability to run multiple instances of Duende.

System.Security.Cryptography.CryptographicException:
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore (Microsoft.AspNetCore.DataProtection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect (Microsoft.AspNetCore.DataProtection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize (Duende.IdentityServer.Storage, Version=7.0.5.0, Culture=neutral, PublicKeyToken=null: /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:98)
   at Duende.IdentityServer.Stores.DefaultGrantStore`1+<GetItemByHashedKeyAsync>d__21.MoveNext (Duende.IdentityServer, Version=7.0.5.0, Culture=neutral, PublicKeyToken=null)

**Comment by RolandGuijt** [comment]
@jaycostales Please read our [data protection guide](https://docs.duendesoftware.com/identityserver/v7/deployment/data_protection/) and apply the suggestions there. That should help. If not feel free to open an issue with your specific issue.

**Comment by gizmohd** [comment]
> OK. Can you please try my suggestion using an ASP.NET Core client and let me know how that turned out?

we area configured exactly as laid out in the guide... and am still getting the errors above...

**Comment by jaycostales** [comment]
It worked perfectly.

I’m still trying to understand why the exact same set of API calls will sometimes return CORS errors when they normally do not. I’m running 7.0.6.

Jay

**Comment by jaycostales** [comment]
> @jaycostales Please read our [data protection guide](https://docs.duendesoftware.com/identityserver/v7/deployment/data_protection/) and apply the suggestions there. That should help. If not feel free to open an issue with your specific issue.

Yes, following the instructions in the documentation link allowed me to fix this problem.

**Comment by RolandGuijt** [comment]
@gizmohd I'm sorry but it's not clear to me whether or not you tried my suggestion with an ASP.NET Core client and what the results were if you did try it.
Additionally: If the WSFed plugin from identityServer.com prevents you from upgrading, my recommendation is to post an issue there. Allthough the domain name might suggest otherwise it is not maintained by Duende.

**Comment by gizmohd** [comment]
Yes.. I’ve tried your solutions.. even went through and double checked my
configuration against the documentation you sent.. all lines up… still
getting the exception I originally brought up,..

**Comment by gizmohd** [comment]
For the record.. per the 'recommendations' here is our config:

```
builder.Services.AddDataProtection(options => options.ApplicationDiscriminator = APPLICATION_NAME)
    .SetDefaultKeyLifetime(TimeSpan.FromDays(7))
    .SetApplicationName(APPLICATION_NAME)
    .ProtectKeysWithCertificate(certificate)
    .PersistKeysToDbContext<ApplicationDbContext>()
    .UseCryptographicAlgorithms(new AuthenticatedEncryptorConfiguration
    {
      EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
      ValidationAlgorithm = ValidationAlgorithm.HMACSHA256,
    });
```

Here's my question.. why is it throwing an error here:
```
at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect(String protectedText, String purpose) in /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:line 100
   at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect(String protectedText) in /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:line 83
```
   
when I'm not using DistributedCache for keys... (using dbContext)?

**Comment by gizmohd** [comment]
Ok.. think I'm on to something here.... I have multiple authentication schemes... our AD scheme is oidc-adfs so it uses that for protecting the key....   

Adding the parameter:  
`options.SignedOutCallbackPath = "/signout-callback-oidc-adfs";`

seems to have resolved this issue... as it was defaulting to /signout-callback-oidc (the other authentication scheme we have)

**Comment by brockallen** [comment]
Yes, if you have multiple external providers then all the various paths (callback, logout, etc) need to be unique within your app. Much like we mention here for our dynamic provider feature: https://docs.duendesoftware.com/identityserver/v7/ui/login/dynamicproviders/#callback-paths

@RolandGuijt perhaps we should add a note about this [here](https://docs.duendesoftware.com/identityserver/v7/ui/login/external/)?

**Comment by gizmohd** [comment]
Strangely this worked without issue before we migrated to .net 8… so I
agree having it in the documentation would help others in the future…
