### ISSUE TITLE
Possible bug in AddResourceStoreCache<ResourceStore>()

### ISSUE THREAD

**Issue by FullStackIndie** [DuendeSoftware/Support#137]
**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer.AspNetIdentity   --version 6.1.2
Duende.IdentityServer.EntityFramework --version 6.1.2

**Which version of .NET are you using?**
 Version:   6.0.302

**Describe the bug**
I get an error when using  services.AddIdentityServer.AddResourceStoreCache<ResourceStore>() when using a custom implementation of ICache<T>

**To Reproduce**
Code to Configure Db Context -- Added for Clarity
`            void ConfigureDbContext(DbContextOptionsBuilder builder)
            {
                builder.UseNpgsql(GetPostgresConnectionString(),
                    options =>
                    {
                        options.MigrationsAssembly(migrationAssembly);
                        options.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
                    });
            }`

**Register custom ICache<T> and Configure IdentityServer**

`        
            services.TryAddTransient(typeof(ICache<>), typeof(IdentityCacheService<>));
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            services.AddIdentityServer(options =>
            {
                options.Caching.ClientStoreExpiration = TimeSpan.FromMinutes(10);
                options.Caching.ResourceStoreExpiration = TimeSpan.FromMinutes(10);
                options.Caching.CorsExpiration = TimeSpan.FromMinutes(10);
                options.Caching.IdentityProviderCacheDuration = TimeSpan.FromMinutes(10);
                options.Authentication.CookieSlidingExpiration = false;
                options.Authentication.CookieAuthenticationScheme = IdentityConstants.ApplicationScheme;
                options.Authentication.CookieLifetime = TimeSpan.FromHours(1);
            })
                .AddConfigurationStore(options => { options.ConfigureDbContext = ConfigureDbContext; })
                .AddOperationalStore(options =>
                {
                    options.RemoveConsumedTokens = true;
                    options.EnableTokenCleanup = true;
                    options.ConfigureDbContext = ConfigureDbContext;
                    options.EnablePooling = true;
                })
                .AddKeyManagement()

                .AddClientStore<ClientStore>()
                .AddResourceStore<ResourceStore>()
                .AddCorsPolicyService<DefaultCorsPolicyService>()
                .AddIdentityProviderStore<IdentityProviderStore>()

                .AddClientStoreCache<ClientStore>()
                .AddResourceStoreCache<ResourceStore>()
                .AddCorsPolicyCache<DefaultCorsPolicyService>()
                .AddIdentityProviderStoreCache<IdentityProviderStore>()

                .AddAspNetIdentity<ApplicationUser>()
                .AddProfileService<ProfileService>()
                .AddExtensionGrantValidator<DelegationHandler>(); `

**Create A Custom ICache<T> implementation**

`
    using Ardalis.GuardClauses;
    using Duende.IdentityServer.Services;
    using FullStackIdentity.Utilities;
    using Microsoft.Extensions.Caching.Distributed;
    using Microsoft.Extensions.Logging;
    using System;
    using System.Text;
    using System.Text.Json;
    using System.Threading.Tasks;

namespace FullStackIdentity.Services
{
    public class IdentityCacheService<T> : ICache<T> where T : class
    {
        private readonly IDistributedCache _cache;
        private readonly ICancellationTokenProvider _tokenProvider;
        private readonly JsonSerializerOptions _jsonOptions;
        private readonly ILogger<IdentityCacheService<T>> _logger;

        public IdentityCacheService(IDistributedCache cache,
            ICancellationTokenProvider tokenProvider,
            JsonSerializerOptions jsonOptions,
            ILogger<IdentityCacheService<T>> logger)
        {
            _cache = Guard.Against.Null(cache);
            _tokenProvider = Guard.Against.Null(tokenProvider);
            _jsonOptions = Guard.Against.Null(jsonOptions);
            _logger = Guard.Against.Null(logger);
        }

        public async Task<T> GetAsync(string key)
        {
            using var getSpan = Telemetry.ActivitySource.StartActivity($"{nameof(IdentityCacheService<T>)}.{nameof(GetAsync)}");
            var json = await _cache.GetStringAsync(key, _tokenProvider.CancellationToken);
            if (json is null)
            {
                return null;
            }
            return JsonSerializer.Deserialize<T>(json, _jsonOptions);
        }

        public async Task<T> GetOrAddAsync(string key, TimeSpan duration, Func<Task<T>> get)
        {
            using var getOrAddSpan = Telemetry.ActivitySource.StartActivity($"{nameof(IdentityCacheService<T>)}.{nameof(GetOrAddAsync)}");
            var model = await GetAsync(key);
            if (model is null)
            {
                model = await get();
                if (model is not null)
                {
                    await SetAsync(key, model, duration);
                }
                else
                {
                    _logger.LogError("Could not Get or Add type {@Type} to the cache", typeof(T).Name);
                }
            }
            return model;
        }

        public async Task RemoveAsync(string key)
        {
            using var removeSpan = Telemetry.ActivitySource.StartActivity($"{nameof(IdentityCacheService<T>)}.{nameof(RemoveAsync)}");
            await _cache.RemoveAsync(key, _tokenProvider.CancellationToken);
        }

        public async Task SetAsync(string key, T item, TimeSpan expiration)
        {
            using var setSpan = Telemetry.ActivitySource.StartActivity($"{nameof(IdentityCacheService<T>)}.{nameof(SetAsync)}");
            var json = JsonSerializer.Serialize<T>(item, _jsonOptions);
            var cacheOptions = new DistributedCacheEntryOptions()
            {
                AbsoluteExpiration = DateTimeOffset.UtcNow.Add(expiration),
            };
            await _cache.SetAsync(key, Encoding.UTF8.GetBytes(json), cacheOptions, _tokenProvider.CancellationToken);
        }
    }
}
`

**Expected behavior**

I expect my custom implmentation of ICache<T> to work with the ResourceStore provided by Duende.IdentityServer. All the other registered caches for IdentityServer work fine and actually show up in my Redis instance, but as soon as I add the **.AddResourceStoreCache<ResourceStore>()** I get an error. I tried deleting my seeded data in the database and re-seeding just to make sure all the IdentityResources, ApiResources and ApiScopes where present but this didnt solve the problem. Any help would be appreciated, thanks!

**Log output/exception with stacktrace**

```
[00:46:50 FTL] Unhandled exception: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duende.IdentityServer.Stores.CachingResourceStore`1.FindApiResourcesByScopeNameAsync(IEnumerable`1 scopeNames) in /_/src/IdentityServer/Stores/Caching/CachingResourceStore.cs:line 107
   at Duende.IdentityServer.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 27
   at Duende.IdentityServer.Stores.IResourceStoreExtensions.FindEnabledResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 98
   at Duende.IdentityServer.Validation.DefaultResourceValidator.ValidateRequestedResourcesAsync(ResourceValidationRequest request) in /_/src/IdentityServer/Validation/Default/DefaultResourceValidator.cs:line 62
   at Duende.IdentityServer.Validation.AuthorizeRequestValidator.ValidateScopeAndResourceAsync(ValidatedAuthorizeRequest request) in /_/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs:line 631
   at Duende.IdentityServer.Validation.AuthorizeRequestValidator.ValidateAsync(NameValueCollection parameters, ClaimsPrincipal subject) in /_/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs:line 113
   at Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 88
   at Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 63
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 98
[00:46:51 ERR] Http GET /connect/authorize responded 500 in 1177.5531ms
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duende.IdentityServer.Stores.CachingResourceStore`1.FindApiResourcesByScopeNameAsync(IEnumerable`1 scopeNames) in /_/src/IdentityServer/Stores/Caching/CachingResourceStore.cs:line 107
   at Duende.IdentityServer.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 27
   at Duende.IdentityServer.Stores.IResourceStoreExtensions.FindEnabledResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 98
   at Duende.IdentityServer.Validation.DefaultResourceValidator.ValidateRequestedResourcesAsync(ResourceValidationRequest request) in /_/src/IdentityServer/Validation/Default/DefaultResourceValidator.cs:line 62
   at Duende.IdentityServer.Validation.AuthorizeRequestValidator.ValidateScopeAndResourceAsync(ValidatedAuthorizeRequest request) in /_/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs:line 631
   at Duende.IdentityServer.Validation.AuthorizeRequestValidator.ValidateAsync(NameValueCollection parameters, ClaimsPrincipal subject) in /_/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs:line 113
   at Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 88
   at Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 63
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 98
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 113
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at FullStackIdentity.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /src/FullStackIdentity/Startup.cs:line 261
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
[00:46:51 ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duende.IdentityServer.Stores.CachingResourceStore`1.FindApiResourcesByScopeNameAsync(IEnumerable`1 scopeNames) in /_/src/IdentityServer/Stores/Caching/CachingResourceStore.cs:line 107
   at Duende.IdentityServer.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 27
   at Duende.IdentityServer.Stores.IResourceStoreExtensions.FindEnabledResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 98
   at Duende.IdentityServer.Validation.DefaultResourceValidator.ValidateRequestedResourcesAsync(ResourceValidationRequest request) in /_/src/IdentityServer/Validation/Default/DefaultResourceValidator.cs:line 62
   at Duende.IdentityServer.Validation.AuthorizeRequestValidator.ValidateScopeAndResourceAsync(ValidatedAuthorizeRequest request) in /_/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs:line 631
   at Duende.IdentityServer.Validation.AuthorizeRequestValidator.ValidateAsync(NameValueCollection parameters, ClaimsPrincipal subject) in /_/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs:line 113
   at Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 88
   at Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 63
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 98
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 113
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at FullStackIdentity.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /src/FullStackIdentity/Startup.cs:line 261
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by brockallen** [comment]
The NRE happens on this line in our caching code:

`var apiResourceName = await _apiResourceNames.GetAsync(scope);`

and that calls into your caching service. I can't tell if the `_apiResourceNames` is null or something odd is returned from `GetAsync`.

Are you able to but a break point in your `public async Task<T> GetAsync(string key)` and see what it returns?

**Comment by brockallen** [comment]
Any update on this issue?

**Comment by brockallen** [comment]
I tried to repro the issue with some tests here: https://github.com/DuendeSoftware/IdentityServer/pull/1002

But AFAICT my tests are working. Have a look and see if mines doesn't match yours for some reason, please. Thx.

**Comment by FullStackIndie** [comment]
Hey thanks for responding, been meaning to get back to you after testing my app again.I use docker containers but the way I setup my project I cant debug it using the vs 2022 or Vs Code debugging tools. I will switch back to no docker setup and test it by this weekend hopefully. I will update you with what I find.
Worst case I realized that my Identity Server Config information rarely changes so the default in Memory Cache yall provide is more than enough.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by FullStackIndie** [comment]
Yes I will close although I didnt get to debug/test it yet, but deciding to use InMemoryStore instead. Your tests passed so I will close.  Thanks for the help
