### ISSUE TITLE
Passing a RSA key to AddSigningCredential

### ISSUE THREAD

**Issue by thatdotnetguy** [DuendeSoftware/Support#1480]
**Which version of Duende IdentityServer are you using?**
7.0.8

**Which version of .NET are you using?**
8

**Describe the bug**
Using RSA key for AddSigningCredential

"We recommend using raw RSA or EC keys." - I read this from @leastprivilege which sounds simpler/better than a X509Certificate2 which I can't get to work anyway.

I have created the RSA Key in Azure Key Vault --> Keys and then retrieving using the KeyClient.

Key Creation

![Image](https://github.com/user-attachments/assets/e33a2f80-b635-4166-b251-0a49c5e8b5f8)

```
client = new KeyClient(new Uri(keyVaultUrl), new DefaultAzureCredential());

KeyVaultKey keyVaultKey = client.GetKey(keyName);

// Ensure the key is an RSA key
if (keyVaultKey.KeyType != KeyType.Rsa && keyVaultKey.KeyType != KeyType.RsaHsm)
{
	throw new InvalidOperationException("The key retrieved from Key Vault is not an RSA key.");
}

// Convert KeyVault's RSA key to RsaSecurityKey
var rsa = new RSAParameters
{
	Modulus = keyVaultKey.Key.N,
	Exponent = keyVaultKey.Key.E
};

var rsaCryptoServiceProvider = RSA.Create();
rsaCryptoServiceProvider.ImportParameters(rsa);

RsaSecurityKey key = new(rsaCryptoServiceProvider);
identityServiceBuild.AddSigningCredential(key, IdentityServerConstants.RsaSigningAlgorithm.RS256);
```

**Exception I get**
```
[01:51:18 Information] UnhandledExceptionEvent { Details: "System.Security.Cryptography.CryptographicException: Unknown error (0xc100000d)
   at System.Security.Cryptography.RSABCrypt.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten)
   at System.Security.Cryptography.RSA.TrySignData(ReadOnlySpan`1 data, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.SignUsingSpanRsa(ReadOnlySpan`1 data, Span`1 destination, Int32& bytesWritten)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.SignUsingSpan(ReadOnlySpan`1 data, Span`1 destination, Int32& bytesWritten)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Sign(ReadOnlySpan`1 input, Span`1 signature, Int32& bytesWritten)
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateSignature(ReadOnlySpan`1 data, Span`1 destination, SigningCredentials signingCredentials, Int32& bytesWritten)
```

**Comment by RolandGuijt** [comment]
IdentityServer also needs a private key. It looks like you're now only providing a public one. Please refer to [this](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-security-cryptography-rsaparameters) documentation and provide a value for the private exponent.

**Comment by RolandGuijt** [comment]
@thatdotnetguy Did you figure this out? If so I'd like to close the issue.

**Comment by RolandGuijt** [comment]
Closing this issue for now but please feel free to add to it if needed.
