### ISSUE TITLE
DuendeAccessTokenManagement not working correctly, when using AzureSignalR service in blazor server sample app

### ISSUE THREAD

**Issue by kamil-gorny** [DuendeSoftware/Support#1500]
**Which version of Duende.AccessTokenManagement are you using?**
Latest version pulled directly from the repository.

**Which version of .NET are you using?**
.NET 8 

**Describe the bug**
When attempting to connect a Blazor Server sample app to Azure SignalR and use Duende AccessTokenManagement, the application throws a NullReferenceException. The issue seems to originate from the BlazorServerUserAccessor, where dependencies like CircuitServicesAccessor and IHttpContextAccessor are null.

**To Reproduce**

1. Pull the latest version of Duende.AccessTokenManagement from the repository.
2. Set up a sample Blazor Server app.
3. Add Azure SignalR to the app:
```csharp
builder.Services.AddSignalR().AddAzureSignalR(options =>
{
    options.ServerStickyMode = ServerStickyMode.Required;
    options.ConnectionString = "insert your connection string here";
});
```

**Expected behavior**

The application should successfully retrieve the access token and make API calls without throwing exceptions. Dependencies like CircuitServicesAccessor and IHttpContextAccessor should be properly injected.

**Log output/exception with stacktrace**

```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer
Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService.GetAccessTokenAsync(ClaimsPrincipal user, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement.OpenIdConnect/UserAccessTokenManagementService.cs:line 62
   at Duende.AccessTokenManagement.OpenIdConnect.OpenIdConnectUserAccessTokenHandler.GetAccessTokenAsync(Boolean forceRenewal, CancellationToken cancellationToken) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement.OpenIdConnect/OpenIdConnectUserAccessTokenHandler.cs:line 56
   at Duende.AccessTokenManagement.AccessTokenHandler.SetTokenAsync(HttpRequestMessage request, Boolean forceRenewal, CancellationToken cancellationToken, String dpopNonce) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement/AccessTokenHandler.cs:line 87
   at Duende.AccessTokenManagement.AccessTokenHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement/AccessTokenHandler.cs:line 49
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BlazorServer.Services.RemoteApiService.GetData() in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/samples/BlazorServer/Services/RemoteApiService.cs:line 25
   at BlazorServer.Pages.FetchRemoteData.OnInitializedAsync() in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/samples/BlazorServer/Pages/FetchRemoteData.razor:line 32
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

```

**Additional context**

I’ve tried various debugging approaches but haven’t been able to resolve this. I'm reaching out here because perhaps the creators or others in the community might have insights or ideas on what could be causing this issue and how to fix it

**Comment by josephdecock** [comment]
Thanks for this bug report! I've reproduced this locally, so I'm transferring it into AccessTokenManagement's repo. As soon as we have a fix, we can push out a new preview of 3.1.
