### ISSUE TITLE
Question: Sample project using MS SQL Server database

### ISSUE THREAD

**Issue by bijub114** [DuendeSoftware/Support#163]
**Which version of Duende IdentityServer are you using?** I'm currently using IdentityServer3.1, trying to upgrade to Duende IdentityServer6 with license.

**Which version of .NET are you using?** .net6

**Describe the bug**

This is just a question (not a bug). Do you have a sample project that uses MS SQL Server for Configuration and Operational data? I looked at the GitHub QuickStarts ([GitHub - DuendeSoftware/Samples: Samples for our Products](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Quickstarts)), but couldn’t find one. “[4_EntityFramework](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Quickstarts/4_EntityFramework)” is the closest one I could find, which uses Sqlite database. I tried changing the Sqlite to SqlServer connection using extension but the migrations failed due to datatype issues (see below). I know, I could try changing the datatypes one by one manually in migrations, but wondering if this is already existing somewhere.

Thanks for your help.
Biju

`Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Column 'UserCode' in table 'DeviceCodes' is of a type that is invalid for use as a key column in an index.
Could not create constraint or index. See previous errors.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at IdentityServer.HostingExtensions.InitializeDatabase(IApplicationBuilder app) in C:\Users\bbaby\Downloads\Samples-main\Samples-main\IdentityServer\v6\Quickstarts\4_EntityFramework\src\IdentityServer\HostingExtensions.cs:line 18
   at IdentityServer.HostingExtensions.ConfigurePipeline(WebApplication app) in C:\Users\bbaby\Downloads\Samples-main\Samples-main\IdentityServer\v6\Quickstarts\4_EntityFramework\src\IdentityServer\HostingExtensions.cs:line 109
   at Program.<Main>$(String[] args) in C:\Users\bbaby\Downloads\Samples-main\Samples-main\IdentityServer\v6\Quickstarts\4_EntityFramework\src\IdentityServer\Program.cs:line 19

  This exception was originally thrown at this call stack:
    [External Code]
    IdentityServer.HostingExtensions.InitializeDatabase(Microsoft.AspNetCore.Builder.IApplicationBuilder) in HostingExtensions.cs
    IdentityServer.HostingExtensions.ConfigurePipeline(Microsoft.AspNetCore.Builder.WebApplication) in HostingExtensions.cs
    Program.<Main>$(string[]) in Program.cs`

**To Reproduce**

n/a

**Expected behavior**

A sample quickstarts project that uses MS SQL Server database to store configuration and operational data for IdentityServer6.

**Log output/exception with stacktrace**

n/a

**Additional context**

None

**Comment by brockallen** [comment]
> Do you have a sample project that uses MS SQL Server for Configuration and Operational data?

All of our samples are here: https://docs.duendesoftware.com/identityserver/v6/samples/

We don't specifically have one for SqlServer, as it's pretty mechanical to switch between the different EF Core DB providers -- that's really just a .NET/EF tooling or configuration feature.

To do so you'd just need to change the connection string, change the "UseSqlite" to "UseSqlServer" in the right places, and finally, yes, you will need to run your EF migrations (because those always produce provider specific SQL). See here for more info on that:

https://docs.duendesoftware.com/identityserver/v6/data/ef/

and specifically: 

https://docs.duendesoftware.com/identityserver/v6/data/ef/#database-creation-and-schema-changes-across-different-versions-of-identityserver

**Comment by bijub114** [comment]
Great. Thanks Brock! I was missing the EF migration run for SQL Server. It works now.
