### ISSUE TITLE
"Error unprotecting key"

### ISSUE THREAD

**Issue by martyt** [DuendeSoftware/Support#164]
**Which version of Duende IdentityServer are you using?**
6.1.3
**Which version of .NET are you using?**
.NET 6.0.1
**Describe the bug**

We've configured IdentityServer to use an EF OperationalStore, with the default configuration to manage signing keys via the `Keys` table. 

I'm seeing repeated errors (from our test environment) indicating that a key couldn't be unprotected, but the KID given in the error *does* exist in the `Keys` table.  I haven't seen the same errors when testing locally. Our test environment consists of multiple instances of our Authentication server running under Kubernetes.

```
Error unprotecting key with kid 1CDBE52EC5AC7D6819247D7F871890B2.
Stack Trace:
System.Security.Cryptography.CryptographicException: The key {4d595a31-64cf-41c4-a234-1333fb02cfb1} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```
The Keys table definitely contains that ID
![image](https://user-images.githubusercontent.com/3867474/185479761-e5aa86ae-cd0f-4a8a-8958-4e9c78cb240e.png)

IdentityServer configuration: 
```
        services
            .AddIdentityServer(options =>
            {
                options.KeyManagement.Enabled = true;

                options.LicenseKey = CustomSettings.DuendeIdentityServerLicenseKey;

                options.IssuerUri = CustomSettings.AuthenticationBaseUrl;

                options.Events.RaiseSuccessEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;

                options.UserInteraction.LoginUrl = "/app/account/login";
                options.UserInteraction.LogoutUrl = "/app/account/logout";

                options.AccessTokenJwtType = "JWT";
                options.EmitStaticAudienceClaim = true;

                options.Authentication.CookieLifetime = TimeSpan.FromMinutes(CustomSettings.SessionTimeoutMinutes);
                options.Authentication.CookieSlidingExpiration = true;
            })
            // cookie-based user session management with our custom hooks to manage the [UserSession] table
            .AddUserSession<CustomIdentityUserSession>()
            .AddAspNetIdentity<User>()
            .AddResourceOwnerValidator<IdentityResourceOwnerPasswordValidator>()
            .AddProfileService<IdentityProfileService>()
            .AddCustomTokenRequestValidator<IdentityCustomTokenRequestValidator>()
            // we use an in-memory store for identity server configuration because it (almost) never changes. No reason to store in the database.
            .AddInMemoryIdentityResources(AuthConfig.GetIdentityResources())
            .AddInMemoryApiScopes(AuthConfig.GetApiScopes())
            .AddInMemoryApiResources(AuthConfig.GetApiResources(customSettings.AuthenticationSecret, AuthConfig.GetApiScopes().Select(s => s.Name).ToList()))
            .AddInMemoryClients(AuthConfig.GetClients(UIBaseUrl, legacyUIBaseUrl, dashboardBaseUrl, customSettings.AuthenticationSecret, customSettings.SessionTimeoutMinutes))
            // Store persisted grants and signing keys in the database (Authentication.PersistedGrants / Authentication.Keys)
            .AddOperationalStore(options =>
            {
                options.DefaultSchema = Schema;
                options.EnableTokenCleanup = true;
                options.RemoveConsumedTokens = true;

                options.ConfigureDbContext = builder =>
                {
                    builder.UseSqlServer(CustomSettings.OmniusConnectionString, optionsBuilder =>
                    {
                        optionsBuilder.ExecutionStrategy(dependencies => new CustomEfCoreSqlExecutionStrategy(dependencies, 3, TimeSpan.FromSeconds(30), null));
                    });

                    builder.ConfigureWarnings(warningsConfigurationBuilder =>
                    {
                        // make the transient retry message log at Warning level (defaults to Information)
                        warningsConfigurationBuilder.Log((CoreEventId.ExecutionStrategyRetrying, LogLevel.Warning));
                    });

                    builder.EnableSensitiveDataLogging(Env.IsDevelopment());
                    builder.EnableDetailedErrors(Env.IsDevelopment());
                };
            });
```

We also have DataProtection configured to store keys in Redis - I don't know if there's some unexpected interaction there or not
```
        services
            .AddDataProtection()
            .SetApplicationName("Foo")
            .PersistKeysToStackExchangeRedis(redis);
```

Any suggestions on how to proceed would be appreciated.

**Comment by brockallen** [comment]
That does sounds like a data protection problem, but you do have it configured. So the only thing I can think of is that you have records in the keys table created with some other data protection keys -- perhaps you rolled the data over from a database from a different environment? Or some other server that's using some other redis data protection store is also connecting to your IdentityServer database and populating signing keys?

**Comment by martyt** [comment]
I guess we could flush the redis cache and delete everything from the `Keys` table and see what happens.

**Comment by brockallen** [comment]
> I guess we could flush the redis cache and delete everything from the Keys table and see what happens.

Yep, that would work.

**Comment by martyt** [comment]
That seems to have fixed the problem. Thanks for the help!
