### ISSUE TITLE
Entity Mapping Error

### ISSUE THREAD

**Issue by Julien-Marpault** [DuendeSoftware/Support#189]
**Which version of Duende IdentityServer are you using?**
6.1.5
**Which version of .NET are you using?**
7.0 preview 7
**Describe the bug**
Entity Mapper for IdentityResource throw an exception

**To Reproduce**
```csharp
public static class DbInitializer
{
    public static void InitializeDbContexts(this IApplicationBuilder app)
    {
        using IServiceScope serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>()?.CreateScope()
            ?? throw new NullReferenceException("serviceScope is null");

        serviceScope.ServiceProvider.GetRequiredService<ApplicationDbContext>().Database.Migrate();
        serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();

        ConfigurationDbContext context = serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
        context.Database.Migrate();

        if (!context.IdentityResources.Any())
        {
            foreach (IdentityResource resource in IdentityResources)
            {
                Duende.IdentityServer.EntityFramework.Entities.IdentityResource entity = resource.ToEntity(); // throw here
                context.IdentityResources.Add(entity);
            }
            context.SaveChanges();
        }
    }

private static IdentityResource[] IdentityResources => new IdentityResource[]
    {
        new IdentityResource{
            Name=IdentityServerConstants.StandardScopes.OpenId,
            DisplayName=IdentityServerConstants.StandardScopes.OpenId,
            Required=true
        },
        new IdentityResource{
            Name=IdentityServerConstants.StandardScopes.Profile,
            DisplayName=IdentityServerConstants.StandardScopes.Profile,
        },
        new IdentityResource{
            Name=IdentityServerConstants.StandardScopes.Email,
            DisplayName=IdentityServerConstants.StandardScopes.Email,
        },
        new IdentityResource{
            Name=IdentityServerConstants.StandardScopes.Address,
            DisplayName=IdentityServerConstants.StandardScopes.Address,
        },
        new IdentityResource{
            Name=IdentityServerConstants.StandardScopes.Phone,
            DisplayName=IdentityServerConstants.StandardScopes.Phone,
        },
        new IdentityResource{
            Name="roles",
            DisplayName="roles",
        }
    };
}
```

Thanks

**Comment by brockallen** [comment]
Do you have the call stack for the exception, please?

**Comment by brockallen** [comment]
I'll close this for the same reason as here: https://github.com/DuendeSoftware/Support/issues/203#issuecomment-1256452822

**Comment by Julien-Marpault** [comment]
Not much informations in the call stack:

at Duende.IdentityServer.EntityFramework.Mappers.IdentityResourceMappers.ToEntity(IdentityResource model)
at Authentication.Data.Migrations.DbInitializer.InitializeDbContexts(IApplicationBuilder app) in C:\Azure DevOps\Graphene\Authentication\Authentication.Library\Data\Migrations\DbInitializer.cs:line 28
