### ISSUE TITLE
Is IdentityServer 6.1.* version compatible with Net7.0?

### ISSUE THREAD

**Issue by kooshan** [DuendeSoftware/Support#203]
IdentityServer Version: 6.1.5
.Net SDK Version: 7.0.100-preview.7.22377.5
.Net Runtime Version: 7.0.0-preview.7.22375.6

Tried current latest stable version of IdentityServer with the latest preview version of Net7.0 and this is what happens:
```
System.TypeInitializationException: The type initializer for 'Duende.IdentityServer.EntityFramework.Mappers.ApiResourceMappers' threw an exception.
 ---> System.ArgumentException: GenericArguments[0], 'System.Char', on 'T MaxFloat[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
 ---> System.Security.VerificationException: Method System.Linq.Enumerable.MaxFloat: type argument 'System.Char' violates the constraint of type parameter 'T'.
   at RuntimeMethodHandleInternal RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
   at MethodInfo System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   --- End of inner exception stack trace ---
   at void RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at MethodInfo System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at IEnumerable<MethodInfo> AutoMapper.Internal.TypeDetails.GetPublicNoArgExtensionMethods(IEnumerable<MethodInfo> sourceExtensionMethodSearch)+(MethodInfo extensionMethod) => { }
   at bool System.Linq.Enumerable+WhereSelectArrayIterator<TSource, TResult>.MoveNext()
   at bool System.Linq.Enumerable+ConcatIterator<TSource>.MoveNext()
   at IEnumerable<TResult> System.Linq.Enumerable.SelectManyIterator<TSource, TCollection, TResult>(IEnumerable<TSource> source, Func<TSource, IEnumerable<TCollection>> collectionSelector, Func<TSource, TCollection, TResult> resultSelector)+MoveNext()
   at bool System.Linq.Enumerable+WhereSelectEnumerableIterator<TSource, TResult>.MoveNext()
   at bool System.Linq.Enumerable+UnionIterator<TSource>.GetNext()
   at bool System.Linq.Enumerable+UnionIterator<TSource>.MoveNext()
   at bool System.Linq.Enumerable+ConcatIterator<TSource>.MoveNext()
   at Dictionary<string, MemberInfo> AutoMapper.Internal.TypeDetails.PossibleNames()
   at MemberInfo AutoMapper.Internal.TypeDetails.GetMember(string name)
   at MemberInfo AutoMapper.Configuration.Conventions.DefaultName.GetMatchingMemberInfo(TypeDetails sourceTypeDetails, Type destType, Type destMemberType, string nameToSearch)
   at MemberInfo AutoMapper.Configuration.Conventions.ParentSourceToDestinationNameMapper.GetMatchingMemberInfo(TypeDetails sourceTypeDetails, Type destType, Type destMemberType, string nameToSearch)
   at bool AutoMapper.Configuration.Conventions.DefaultMember.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceTypeDetails, Type destType, Type destMemberType, string nameToSearch, List<MemberInfo> resolvers, IMemberConfiguration parent, bool isReverseMap)
   at bool AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, string nameToSearch, List<MemberInfo> resolvers, bool isReverseMap)
   at bool AutoMapper.ProfileMap.MapDestinationPropertyToSource(TypeDetails sourceTypeDetails, Type destType, Type destMemberType, string destMemberName, List<MemberInfo> members, bool reverseNamingConventions)
   at new AutoMapper.TypeMap(Type sourceType, Type destinationType, ProfileMap profile, bool isReverseMap)
   at void AutoMapper.ProfileMap.BuildTypeMap(IGlobalConfiguration configurationProvider, ITypeMapConfiguration config)
   at void AutoMapper.ProfileMap.Register(IGlobalConfiguration configurationProvider)
   at void AutoMapper.MapperConfiguration.Seal()
   at new AutoMapper.MapperConfiguration(MapperConfigurationExpression configurationExpression)
   at new AutoMapper.MapperConfiguration(Action<IMapperConfigurationExpression> configure)
   at static Duende.IdentityServer.EntityFramework.Mappers.ApiResourceMappers() in /_/src/EntityFramework.Storage/Mappers/ApiResourceMappers.cs:line 17
   --- End of inner exception stack trace ---
   at ApiResource Duende.IdentityServer.EntityFramework.Mappers.ApiResourceMappers.ToModel(ApiResource entity) in /_/src/EntityFramework.Storage/Mappers/ApiResourceMappers.cs:line 30
   at Task<IEnumerable<ApiResource>> Duende.IdentityServer.EntityFramework.Stores.ResourceStore.FindApiResourcesByScopeNameAsync(IEnumerable<string> scopeNames)+(ApiResource x) => { } in /_/src/EntityFramework.Storage/Stores/ResourceStore.cs:line 121
   at TResult[] System.Linq.Enumerable+WhereSelectArrayIterator<TSource, TResult>.ToArray()
   at async Task<IEnumerable<ApiResource>> Duende.IdentityServer.EntityFramework.Stores.ResourceStore.FindApiResourcesByScopeNameAsync(IEnumerable<string> scopeNames) in /_/src/EntityFramework.Storage/Stores/ResourceStore.cs:line 121
   at void Duende.IdentityServer.Stores.CachingResourceStore<T>+<>c__DisplayClass12_0+<<FindApiResourcesByScopeNameAsync>b__0>d.MoveNext() in /_/src/IdentityServer/Stores/Caching/CachingResourceStore.cs:line 136
   at async Task<T> IME.IdentityExtensions.CacheStore.Cache.RedisCache<T>.GetOrAddAsync(string key, TimeSpan duration, Func<Task<T>> get) in D:/Repositories/IME.SSO/IME.SSO.Server/src/IdentityExtensions/CacheStore/Cache/RedisCache.cs:line 102
   at async Task<IEnumerable<ApiResource>> Duende.IdentityServer.Stores.CachingResourceStore<T>.FindApiResourcesByScopeNameAsync(IEnumerable<string> scopeNames) in /_/src/IdentityServer/Stores/Caching/CachingResourceStore.cs:line 164
   at async Task<Resources> Duende.IdentityServer.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable<string> scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 38
   at async Task<Resources> Duende.IdentityServer.Stores.IResourceStoreExtensions.FindEnabledResourcesByScopeAsync(IResourceStore store, IEnumerable<string> scopeNames) in /_/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 98
   at async Task<ResourceValidationResult> Duende.IdentityServer.Validation.DefaultResourceValidator.ValidateRequestedResourcesAsync(ResourceValidationRequest request) in /_/src/IdentityServer/Validation/Default/DefaultResourceValidator.cs:line 62
   at async Task<TokenRequestValidationResult> Duende.IdentityServer.Validation.TokenRequestValidator.ValidateAuthorizationCodeRequestAsync(NameValueCollection parameters) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 402
   at async Task<TokenRequestValidationResult> Duende.IdentityServer.Validation.TokenRequestValidator.RunValidationAsync(Func<NameValueCollection, Task<TokenRequestValidationResult>> validationFunc, NameValueCollection parameters) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 189
   at async Task<TokenRequestValidationResult> Duende.IdentityServer.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 170
   at async Task<IEndpointResult> Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 117
   at async Task<IEndpointResult> Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 76
   at async Task Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 117
   at async Task Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 117
   at async Task Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
   at async Task Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at async Task Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48
   at async Task Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context, ICorsPolicyProvider corsPolicyProvider)+InvokeCoreAwaited(?)
   at async Task Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 28
```
To be fair, seems like an AutoMapper issue with some constrained API. Is there any preview version or nuget channel for Idsrv which I could use with Net7.0 preview?

**Comment by kooshan** [comment]
Maybe also related to this one?? 
[https://github.com/DuendeSoftware/Support/issues/189](https://github.com/DuendeSoftware/Support/issues/189 )

**Comment by brockallen** [comment]
We've not yet started our testing for .NET 7, but it's on our radar and we will support it.

**Comment by Julien-Marpault** [comment]
I still get the issue with .Net 7 RC1:

Here's the CallStack:

```
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart> parts, Microsoft.AspNetCore.Mvc.Controllers.ControllerFeature feature)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<Microsoft.AspNetCore.Mvc.Controllers.ControllerFeature>(Microsoft.AspNetCore.Mvc.Controllers.ControllerFeature feature)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.Abstractions.ActionDescriptorProviderContext context)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()	Unknown
Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()	Unknown 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()	Unknown 	Microsoft.Extensions.Primitives.dll!Microsoft.Extensions.Primitives.ChangeToken.OnChange(System.Func<Microsoft.Extensions.Primitives.IChangeToken> changeTokenProducer, System.Action changeTokenConsumer)	Unknown 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()	Unknown
Microsoft.AspNetCore.Mvc.RazorPages.dll!Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.GetOrCreateDataSource(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)	Unknown 	Microsoft.AspNetCore.Mvc.RazorPages.dll!Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.MapRazorPages(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)	Unknown
>	BookStarter.Api.dll!Program.<Main>$.AnonymousMethod__0_10(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints) Line 186	C#
Microsoft.AspNetCore.Routing.dll!Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(Microsoft.AspNetCore.Builder.IApplicationBuilder builder, System.Action<Microsoft.AspNetCore.Routing.IEndpointRouteBuilder> configure)	Unknown
 BookStarter.Api.dll!Program.<Main>$(string[] args) Line 183	C#
```

and exception details.

```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Method 'get_ServerSideSessions' in type 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationDbContext`1' from assembly 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
```

**Comment by brockallen** [comment]
@kooshan -- I just had a very quick look and I can see the error you show above. So something in EF? or LINQ? changed in .NET 7, so it doesn't look like our binary will just easily run on the updated runtime. At least, that's all I can say now -- we will be doing more investigation.

**Comment by brockallen** [comment]
@Julien-Marpault that sounds more like a DB update/migration might have been missed? Not sure exactly.

**Comment by brockallen** [comment]
I'm going to close this issue, as there's nothing to add here really. We've started our work for .NET 7 and from what we've seen it's not binary compatible (unfortunately).

**Comment by hi-diego** [comment]
I found a Solution for it! here[https://github.com/dotnet/aspnetcore/issues/44990](url)
