### ISSUE TITLE
Error unprotecting key with kid ...

### ISSUE THREAD

**Issue by StackOverflow64** [DuendeSoftware/Support#224]
**Versions**
Duende IdentityServer version 6.1.4.
.NET version 6.0 (runtime version 6.0.8)

**Licensee**
SaskEnergy Incorporated
(Starter edition + 9 clients)

**Problem Description**
After upgrading from IdentityServer4 to Duende IdentityServer 6 we have been getting an error like the following when IdentityServer starts.
`Error unprotecting key with kid 927F86E89E378F4D6186F676301722B5.`

**Exception**
```
System.Security.Cryptography.CryptographicException: The key {
   297aff6e-cc9c-4626-a14f-bc7a99bd5d2a
} was not found in the key ring. For more information go to http: //aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```

**Keys Table Data**
| Id                               | Version | Created             | Use     | Algorithm | IsX509Certificate | DataProtected |
| :-------------------------------- | :------ | :------------------- | :------ | :-------- | :---------------- | :------------ |
| 927F86E89E378F4D6186F676301722B5 | 1       | 2022-09-19 15:46:40 | signing | RS256     | FALSE             | TRUE          |
| B8EB48AEBC31DEC5F753AC316F4B6E49 | 1       | 2022-09-19 20:55:07 | signing | RS256     | FALSE             | TRUE          |

**Additional Context**

Note that we run two instances of IdentityServer and these are load-balanced.  Both instances use the same SQL Server database.
I believe each IdentityServer instance had created one key, and the error occurs when one instance attempts to unprotect the key generated by the other instance.
If my assessment is correct, what is the proper configuration us?  (Using separate databases is not an option.)

**Comment by brockallen** [comment]
> If my assessment is correct, what is the proper configuration us? (Using separate databases is not an option.)

Have you configured Data Protection for these servers?

https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/

**Comment by StackOverflow64** [comment]
Thanks for pointing me in the right direction.

**Comment by brockallen** [comment]
Once you have DP configured, then then old signing keys in the IS DB can be deleted (assuming you then reboot all the apps).
