### ISSUE TITLE
Access token is rejected by API

### ISSUE THREAD

**Issue by nhumby** [DuendeSoftware/Support#302]
I'm using the Identity Server 6 Quickstart as an IDP. I've secured an MVC and a Web Forms app with it (IdentityServer is .Net Core but no other sites are). I've also secured an API (wirtten in MVC/WebApi). None of my bearer tokens are being accepted though. I've tried the access token issued during logging into the secured MVC site, or from the userinfo endpoint, and also directly requesting an access token using Postman. Using any of these I get {"Message":"Authorization has been denied for this request."} both in my app and in Postman. I've examined the tokens in jwt.io and cannot see any obvious problems with them. If I modify the token string to aaa then I get the below in the API's katana log:

Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Error: 0 : Authentication failed
System.ArgumentException: IDX12709: CanReadToken() returned false. JWT is not well formed: 'aaa'.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ReadJwtToken(String token) in C:\agent2\_work\56\s\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 630
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText) in /_/src/Microsoft.Owin.Security.Jwt/JwtFormat.cs:line 181
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__3.MoveNext() in /_/src/Microsoft.Owin.Security.OAuth/OAuthBearerAuthenticationHandler.cs:line 56
    ProcessId=52436
    DateTime=2022-11-02T09:47:30.3695017Z

If I use the original tokens provided by Identity Server there's no mention of any problems in the katana logs, I just get authorisation is denied messages. If I create a simple little dotnet Core API and secure it in the same way it works with my tokens, so I know the IdentityServer and its tokens are ok. Is there any way of getting more logged details from Identity Server on why the access token has been rejected? Or what else may be wrong with my requests?

My IdentityServer's client and scopes declaration:

    public static IEnumerable<ApiScope> ApiScopes =>
        new List<ApiScope>
        {
            new ApiScope(name: "api1", displayName: "MyAPI"),
            new ApiScope(name: "CWebServices", displayName: "C Web Services"),
        };
...
            new Client
            {
                ClientId = "SPAPI",

                // no interactive user, use the clientid/secret for authentication
                AllowedGrantTypes = GrantTypes.ClientCredentials,

                // secret for authentication
                ClientSecrets =
                {
                    new Secret("secret".Sha256())
                },

                // scopes that client has access to
                AllowedScopes = new List<string>
                {
                    "CWebServices",
                }
            },

My API has the following in its OWIN startup class:

    public class Startup_OpenIdConnect_IS4_API
    {
        public void Configuration(IAppBuilder app)
        {
            IdentityModelEventSource.ShowPII = true;
            app.UseJwtBearerAuthentication(new JwtBearerAuthenticationOptions
            {
                AuthenticationType = "jwt",
                AuthenticationMode = AuthenticationMode.Active,
                TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = OpenIdAuthenticator.Authority,
                    ValidAudience = OpenIdAuthenticator.Authority + "/resources",
                    IssuerSigningKeyResolver = LoadKeys,
                    NameClaimType = "name",
                    ValidateAudience = false,
                },
            });

            if (OpenIdAuthenticator.UseWebApiRoute)
            {
                var apiRouting = new ApiRouting();
                apiRouting.ConfigureRouting(app);
                _logger.Debug($"Routing configured");
            }
        }

        internal static DiscoveryCache _discoveryCache = new DiscoveryCache(OpenIdAuthenticator.Authority);

        private IEnumerable<SecurityKey> LoadKeys(string token, SecurityToken securityToken, string kid, TokenValidationParameters validationParameters)
        {
            var disco = _discoveryCache.GetAsync().ConfigureAwait(false).GetAwaiter().GetResult();

            var keys = disco.KeySet.Keys
                .Where(x => x.N != null && x.E != null)
                .Select(x => {
                    var rsa = new RSAParameters
                    {
                        Exponent = Base64UrlEncoder.DecodeBytes(x.E),
                        Modulus = Base64UrlEncoder.DecodeBytes(x.N),
                    };

                    return new RsaSecurityKey(rsa)
                    {
                        KeyId = x.Kid
                    };
                });

            return keys;
        }
    }

**Comment by josephdecock** [comment]
IdentityServer isn't rejecting your token - JWT access tokens are validated entirely within the API. And as you say, you know that IdentityServer is running properly and generating tokens properly. Instead, the problem is within the API where the token is being sent.

I don't see anything obviously wrong in your API's configuration. I don't quite remember what happens if you both specify a `ValidAudience` but also say `ValidateAudience = false`. I think the flag takes precedence, but you could try removing the `ValidAudience` just to double check.

Another possibility is that authentication is succeeding, but the authorization rules you have in place are not satisfied. You can test that quickly by creating an api endpoint that has the `[AllowAnonymous]` attribute on it. Debug into that endpoint, get the OwinContext, and look at its Authentication.User property. If you see a user with the claims from your token, then you know you have an authorization problem, rather than an authentication problem.

Hope that helps - we also have a sample that uses .NET Framework for the APIs and Clients [here](https://github.com/DuendeSoftware/Samples/tree/main/various/clients/Owin).

**Comment by nhumby** [comment]
Hi Joe. Thank you for the explanation and suggestions! I removed the ValidAudience property but no luck. I debugged into an unsecured endpoint as suggested and used Request.GetOwinContext() to retrieve the OwinContext object. The Authentication.User property had no claims or any information identifying a user at all. Does that provide any further clue to what may be wrong?

Thanks for the link, I used the structure of the SimpleApi.csproj framework sample's Startup.cs to secure my own API. Is there anything else in the project involved that I might have missed? The only other difference is the SimpleApi is a console application while mine is an old school MVC WebApi one (with museum pieces like global.asax etc).  Is there a reason SimpleApi is a console app?

**Comment by josephdecock** [comment]
Try adding [this config](https://github.com/DuendeSoftware/Samples/blob/main/various/clients/Owin/SimpleOwinApi/App.config#L22-L40) to get more verbose logging from your API. Hopefully that will tell us the problem.

**Comment by nhumby** [comment]
Yeah I tried using the katana logging with that config but the only time I got anything from it was if I replaced the bearer token with "aaa" to make the structure invalid, it's logging nothing otherwise. I've created a simple dummy API from the VS template and secured it with the same startup class (marking one endpoint with [Authorize]). I can reach the unsecured endpoint (https://localhost/DummyAPI/api/Dummy/5) but I can't access the secured endpoint (https://localhost/DummyAPI/api/Dummy) despite setting up the OWIN startup as I think it should be. Could you take a look at the attached project? I hosted it as an application in IIS. I used the following access token generated from my IdentityServer /connect/token endpoint:

eyJhbGciOiJSUzI1NiIsImtpZCI6IjFBQjhFNzA4Qzg0OEREQkVEOUY4OTI5REYxNUMyM0JEIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdC9pZGVudGl0eXNlcnZlcmFzcG5ldGlkZW50aXR5IiwibmJmIjoxNjY3NDEzMzExLCJpYXQiOjE2Njc0MTMzMTEsImV4cCI6MTY2NzQxNjkxMSwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3QvaWRlbnRpdHlzZXJ2ZXJhc3BuZXRpZGVudGl0eS9yZXNvdXJjZXMiLCJzY29wZSI6WyJDUFFXZWJTZXJ2aWNlcyJdLCJjbGllbnRfaWQiOiJTYWxlc1BvcnRhbEFQSSIsImp0aSI6Ijc1OTU1QzY0NTEwRUM5QzNEQkRCRTIxMjczMTEyRDUwIn0.ENwx87sPBMI0RBkdd9RPM2YBtYIhhIef3F74hdEXEIPMlz4RqJMGBDthne-7sH0FnmStllpyTCKCmYq9K-jnHjym1POW_03hCTnksrMxLlcYEtZulcmnWLm4WOkzw28HToGCLSsNW-9B4Wv5hjpgfrmVwsl7DupMxcA0LAUd4ngsDbRo9Yis293NhjTgFJJ5aL2b-qJOw3D9039h8hof67k4PvH5Q9XNTbfb7JAduZIEIVdyRx1kaqOLhsQXpcADlGm4oPQb2OioST1BD1Akj1jtIbopDEUr5SAWo6xEno0t5A57tU0qIAOwvU68F3N7inp3OI7wqF4LzRcqe5hYBQ

[DummyAPI.zip](https://github.com/DuendeSoftware/Support/files/9923147/DummyAPI.zip)

**Comment by josephdecock** [comment]
Your api needs to install the `Microsoft.Owin.Host.SystemWeb` nuget package to host in IIS. Our example doesn't need that because it is a self-hosted console app. See [microsoft's docs](https://learn.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/getting-started-with-owin-and-katana#host-owin-in-iis).


I think you will also have some odd things going on with routes, because routes to your apis are defined in both startup.cs and WebApiConfig.cs.

**Comment by nhumby** [comment]
Hi Joe. Yes you're correct, and removing them helped me figure out what's going wrong. In the API I'm protecting there is no central routing table setup call, instead each controller is decorated with [RoutePrefix] and each endpoint with [Route]. While it's valid I don't think it works with OWIN, perhaps because routing doesn't fall into the pipeline. Anyway, I added in:

            HttpConfiguration config = new HttpConfiguration();
            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "rest/{controller}/{action}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
            app.UseWebApi(config);

to my Startup class and removed the [RoutePrefix] and [Route] attributes on the controllers and it's now inspecting my access token and acting accordingly. I'm also getting katana log entries if the token is malformed. Thank you so much for your assistance!
