### ISSUE TITLE
www-authenticate: Bearer error="invalid_token",error_description="The signature is invalid" 

### ISSUE THREAD

**Issue by pan15jain** [DuendeSoftware/Support#339]
Hi All,

I am using Identity server 6.0 and getting the "The signature is invalid" error while accessing the API end points after it has been successfully authenticated
 
Identity server code:
builder.Services.AddIdentityServer(x =>
{
    x.IssuerUri = "https://identityserver:7000";    
})
.AddAspNetIdentity<TrimarkUser>()
.AddConfigurationStore(configurationStoreOptions =>
{
    configurationStoreOptions.ResolveDbContextOptions = ResolveDbContextOptions;
})
.AddOperationalStore(operationalStoreOptions =>
{
    operationalStoreOptions.ResolveDbContextOptions = ResolveDbContextOptions;
});

void NpgsqlOptionsAction(NpgsqlDbContextOptionsBuilder npgsqlDbContextOptionsBuilder)
{
    npgsqlDbContextOptionsBuilder.MigrationsAssembly(typeof(Program).GetTypeInfo().Assembly.GetName().Name);
}

void ResolveDbContextOptions(IServiceProvider serviceProvider, DbContextOptionsBuilder dbContextOptionsBuilder)
{
    dbContextOptionsBuilder.UseNpgsql(
        serviceProvider.GetRequiredService<IConfiguration>().GetConnectionString("IdentityServer"),
        NpgsqlOptionsAction);
}

API code:
uilder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.Authority = builder.Configuration["Authentication:Authority"];
        options.Audience= builder.Configuration["Authentication:Audience"];

        //options.SaveToken = true;
        //options.TokenValidationParameters.ValidateAudience = true;
        //options.TokenValidationParameters.ValidateIssuer = true;
        //options.TokenValidationParameters.ValidateIssuerSigningKey = true;
        options.Configuration = new OpenIdConnectConfiguration();
        //options.TokenValidationParameters = new TokenValidationParameters
        //{
        //    ValidateAudience = false,
        //    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Authentication:Audience"]))
        //};    

    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("ApiScope", policyBuilder =>
    {
        policyBuilder.RequireAuthenticatedUser().RequireClaim("scope", "https://www.trimark.com/api");
    });
});

Thanks
Pankaj

**Comment by josephdecock** [comment]
I don't think you want to do this: `options.Configuration = new OpenIdConnectConfiguration();` Try removing that. Also, what are your Authentication:Audience and Authentication:Authority configs?

**Comment by pan15jain** [comment]
> u want to do this: `options.Configuration = new OpenIdConnectConfiguration();` Try removing that. Also, what are your Authentication:Audience and Authentication:Authority configs?

Hi,
Thanks for the response

If I remove this I am getting 500 error:
ystem.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.Net.Http.HttpRequestException: Connection refused (identityserver:7000)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

Also Please find the configuration code snippet from dockercompose

services:
  api:
    build:
      context: .
      dockerfile: ./API/Dockerfile
    #networks: 
    #  - identserv
    depends_on:
      - identityserver
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet API.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - AUTHENTICATION__AUTHORITY=https://identityserver:7000
      - AUTHENTICATION__AUDIENCE=9fc33c2e-dbc1-4d0a-b212-68b9e07b3ba0
    ports:
      - "7001:7001"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro

**Comment by josephdecock** [comment]
That exception means that the jwt authentication handler isn't able to make network requests to your identity server project. Are you able to make requests to your identity server outside your api? Try going to https://identityserver:7000/.well-known/openid-configuration in your browser to check.

**Comment by pan15jain** [comment]
> That exception means that the jwt authentication handler isn't able to make network requests to your identity server host. Are you able to make requests to your identity server outside your api? Try going to https://identityserver:7000/.well-known/openid-configuration in your browser to check.

Yes .. I can access it and gotthe response.

{"issuer":"https://identityserver:7000","jwks_uri":"https://identityserver:7000/.well-known/openid-configuration/jwks","authorization_endpoint":"https://identityserver:7000/connect/authorize","token_endpoint":"https://identityserver:7000/connect/token","userinfo_endpoint":"https://identityserver:7000/connect/userinfo","end_session_endpoint":"https://identityserver:7000/connect/endsession","check_session_iframe":"https://identityserver:7000/connect/checksession","revocation_endpoint":"https://identityserver:7000/connect/revocation","introspection_endpoint":"https://identityserver:7000/connect/introspect","device_authorization_endpoint":"https://identityserver:7000/connect/deviceauthorization","backchannel_authentication_endpoint":"https://identityserver:7000/connect/ciba","frontchannel_logout_supported":true,"frontchannel_logout_session_supported":true,"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"scopes_supported":["openid","profile","email","https://www.trimark.com/api","offline_access"],"claims_supported":["sub","name","family_name","given_name","middle_name","nickname","preferred_username","profile","picture","website","gender","birthdate","zoneinfo","locale","updated_at","email","email_verified"],"grant_types_supported":["authorization_code","client_credentials","refresh_token","implicit","password","urn:ietf:params:oauth:grant-type:device_code","urn:openid:params:grant-type:ciba"],"response_types_supported":["code","token","id_token","id_token token","code id_token","code token","code id_token token"],"response_modes_supported":["form_post","query","fragment"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"id_token_signing_alg_values_supported":["RS256"],"subject_types_supported":["public"],"code_challenge_methods_supported":["plain","S256"],"request_parameter_supported":true,"request_object_signing_alg_values_supported":["RS256","RS384","RS512","PS256","PS384","PS512","ES256","ES384","ES512","HS256","HS384","HS512"],"authorization_response_iss_parameter_supported":true,"backchannel_token_delivery_modes_supported":["poll"],"backchannel_user_code_parameter_supported":true}

**Comment by brockallen** [comment]
Hi @pan15jain -- any update here?
