### ISSUE TITLE
Value cannot be null. (Parameter 'connectionString')

### ISSUE THREAD

**Issue by williambuchanan2** [DuendeSoftware/Support#363]
**Which version of Duende IdentityServer are you using?**
6.1.7
**Which version of .NET are you using?**
7.0
**Describe the bug**
When running the migrations I get an error "Value cannot be null. (Parameter 'connectionString')":

C:\xxx\xxxx.API>dotnet ef migrations add IdentityServerMigration_"6_1_7" -c PersistedGrantDbContext --output-dir "Data/Migrations" --namespace "xxxx.Data.Migrations.IdS.PersistedGrant" --project "C:\xxxx\xxx.Infrastructure\xxx.Infrastructure.csproj"
Build started...
Build succeeded.
AUTHENTICATION AUTHORITY: https://192.168.1.7:7012
System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)

**To Reproduce**
Run the migration command:

C:\xxx\xxxx.API>dotnet ef migrations add IdentityServerMigration_"6_1_7" -c PersistedGrantDbContext --output-dir "Data/Migrations" --namespace "xxxx.Data.Migrations.IdS.PersistedGrant" --project "C:\xxxx\xxx.Infrastructure\xxx.Infrastructure.csproj"
Steps to reproduce the behavior.

**Expected behavior**
Runs successfully.

Generates updates without error.

**Log output/exception with stacktrace**

```
System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at Auth.Infrastructure.DependencyInjection.<>c__DisplayClass0_0.<AddInfrastructure>b__0(DbContextOptionsBuilder options) in C:\Workspace\TFS\PDS\NetCore\Server\Microservices\Auth\Auth.Infrastructure\DependencyInjection.cs:line 36
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider _, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__17`1.<AddCoreServices>b__17_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'connectionString')

```

**Additional context**
I have done a global search for the word 'connectionString' and have hard coded the actual connection string in all these places, because I assume it isn't able to load the connection string - however this didn't make any difference.

**Comment by williambuchanan2** [comment]
P.S. This seems to have started after I upgraded the solution to .net 7

**Comment by josephdecock** [comment]
How are you configuring the dbcontext? I would expect something along these lines:

```
    builder.Services.AddIdentityServer()
        .AddConfigurationStore(options =>
        {
            options.ConfigureDbContext = b => b.UseSqlite(connectionString,
                sql => sql.MigrationsAssembly(migrationsAssembly));
        })
        .AddOperationalStore(options =>
        {
            options.ConfigureDbContext = b => b.UseSqlite(connectionString,
                sql => sql.MigrationsAssembly(migrationsAssembly));
        })
```

**Comment by williambuchanan2** [comment]
Similar:


            // IdentityServer Pipeline
            var iServerBuilder = services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
            
                // see https://docs.duendesoftware.com/identityserver/v5/basics/resources
                options.EmitStaticAudienceClaim = true;
                options.UserInteraction.LoginUrl = "/Account/Login";
              
                options.Discovery.CustomEntries.Add("Local_ApiUserService_Users", "~/api/v1/UserService/Users");
            });

            // Your telling Duende IdentityServer that ASP.NET Core Identity is the primary authentication
            iServerBuilder.AddAspNetIdentity<PDSIdentityUser>();
            iServerBuilder.AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString, opt => { opt.MigrationsAssembly(assemblyTypeName); });
            });

            iServerBuilder.AddOperationalStore(options =>
            {
                options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString, opt => { opt.MigrationsAssembly(assemblyTypeName); });
                options.EnableTokenCleanup = true;
                options.TokenCleanupInterval = 3600;
            });

And as I mentioned I had tried hard coding the connection strings above in place of the connectionString variable....

**Comment by josephdecock** [comment]
Perhaps you have some incompatible combination of nuget package dependencies. Can you make sure all your entity framework dependencies are updated, and possibly share your csproj file (or at least the nuget packages)?

**Comment by williambuchanan2** [comment]
[CSProj.zip](https://github.com/DuendeSoftware/Support/files/10136556/CSProj.zip)

I checked and all nuget packages are updated. I have attached the csproj files. Auth.API is the executable and Auth.Infrastructure is the data layer.

Thanks

**Comment by williambuchanan2** [comment]
I had originally tried with 6.2 and got the error, so then I rolled back to 6.1 (and still had the error so assumed it was .net 7 related). I have just upgraded again to 6.2 and the error is still there.

Good news that there are no DB changes - in that case I will just stick with 6.2 and hope the problem goes away if I need DB updates with future releases.

All that said, I now get the below error when running with 6.2. It doesn't seem to affect anything from what I can see though... Browsing to the URL in the error doesn't help.



fail: Duende.IdentityServer.Services.KeyManagement.KeyManager[0]
      Error unprotecting key with kid A8C903EA2C326FAC215CE6CE39FDC6CB.
      System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
         at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435

Thanks

**Comment by josephdecock** [comment]
IdentityServer's signing keys get encrypted and decrypted using Microsoft's data protection feature. Data protection manages its own encryption keys separately from the signing keys that IdentityServer uses. The data protection keys can cause problems if you have a signing key stored in your signing key store, but try to decrypt it without the data protection key that encrypted it.

There are several ways that this can occur:

1. In load balanced environments, every instance of IdentityServer needs to share signing keys, and you need to configure data protection to do so. Microsoft has extensive docs [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview).
2. Signing keys could be generated in a (local) development environment and then accidentally included into the build output.
3. Data protection creates keys isolated by application name automatically. If you don't specify a name, the content root path of the application will be used. But, beginning in .NET 6.0 Microsoft changed how they handle the path, which can cause data protection keys to break. Their docs on the problem are [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview#setapplicationname), including a work-around where you de-normalize the path.

**Comment by josephdecock** [comment]
Closing this issue, feel free to opens a new ticket if you have more questions.
