### ISSUE TITLE
Can't use Azure AD

### ISSUE THREAD

**Issue by samuel-utbult-oborgen** [DuendeSoftware/Support#365]
**Which version of Duende IdentityServer are you using?**

6.2.0

**Which version of .NET are you using?**

7.0 is installed but the project uses 6.0.

**Describe the bug**

I am trying to set up Azure AD to be used with an Identity Server instance. Azure AD successfully logs in users but when it calls /signin-oidc, then it just says “Exception: Correlation failed. Unknown location”. The following is printed in the terminal: ”CORS request made for path: /signin-oidc from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint” I have created and registered a ICorsPolicyService that is supposed to decide if an origin is allowed, but it seems like Identity Server completely disregards this service and just blocks the request.

I have a separate OAuth2 client implemented according to the OAuth2 specification and it does not have this problem.

**To Reproduce**

1. Create an ASP.NET project.
2. Add Identity Server to it.
3. Add Azure AD in accordance with these guides: https://docs.duendesoftware.com/identityserver/v6/ui/login/external/ https://www.ashleyhollis.com/how-to-configure-azure-active-directory-with-identityserver4
4. Start the project.
5. On the login page, click on the button corresponding to Azure AD.
6. Log in the user. Azure AD calls the callback.
7. Get "Exception: Correlation failed. Unknown location".
8. (Add a ICorsPolicyService but get the same error).

**Expected behavior**

Identity Server should have logged in the user.

**Log output/exception with stacktrace**

In the browser:

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

In the terminal:

```
[15:19:40 Debug] Duende.IdentityServer.Hosting.CorsPolicyProvider
CORS request made for path: /signin-oidc from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint

[15:19:40 Warning] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
'.AspNetCore.Correlation.M77hy7C3uJi8KaWtYvEHYdFAnRdR3A-Li_wRddxnNkk' cookie not found.

[15:19:40 Information] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
Error from RemoteAuthentication: Correlation failed..

[15:19:40 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

[15:19:40 Error] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP POST /signin-oidc responded 500 in 46.5673 ms
```

**Comment by josephdecock** [comment]
It seems like there are several symptoms here, but I suspect that the correlation failures from the Azure AD handler are the root cause. What I would do first is simplify everything and get a stand alone ASP.NET client (without IdentityServer at all) to authenticate with Azure AD. The azure ad handler is trying to make sure that the request to the callback url corresponds to an actual login request (as opposed to some sort of spoofing). It does that correlation through a cookie. Probably there is some sort of issue with that cookie, so I would look at that first.

**Comment by josephdecock** [comment]
We also have a quickstart tutorial series that [describes how to do federation](https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/#add-support-for-external-authentication). (We federate with google in that tutorial, but it might be helpful for you as well).

**Comment by samuel-utbult-oborgen** [comment]
I can confirm that this problem also exists in a standalone ASP.NET server without Identity Server. I will try to see if a skeleton project also has this problem. Alternatively, I could try using the Microsoft account provider.
