### ISSUE TITLE
Automatic Key Management Question

### ISSUE THREAD

**Issue by chrisrestall** [DuendeSoftware/Support#366]
**Which version of Duende IdentityServer are you using?**
6.1.1 - reports itself as Duende IdentityServer version "6.1.2+0222403973d77e72087ead9adc5806053d0b45fa" (".NET 6.0.9") 

**Which version of .NET are you using?**
.NET 6.0

**Describe the bug**
Seeing a bunch of version 1 keys being created in the Keys table, also seeing a bunch of errors regarding "Error unprotecting key with kid xxxxx" - with each key entry in the database during login routines.  We are using the EF integration for for Duende (6.1.2), Asp net Core Identity  and BFF.  

We are using the OOB default settings (no explicit config) for Automatic key rotation, trying to understand if:
1.  The multiple errors in the logs regarding Error unprotecting key with kid/ The key {someguid} was not found in the key ring are normal for testing on Community edition.
2. Should we have multiple (up to 9 now, in one day) version 1, signing keys in the keys table.

**To Reproduce**
Seems to do it sporadically on login.  Not clear on key generation lifecycle based on documentation and what we are seeing

**Expected behavior**

No errors related to keys in the logs

**Log output/exception with stacktrace**

```
2022-11-29 08:04:47.719 -07:00 [WRN] [Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository] [] Using an in-memory repository. Keys will not be persisted to storage. 
  2022-11-29 08:04:47.779 -07:00 [WRN] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. 
2022-11-29 08:04:49.254 -07:00 [INF] [Duende.IdentityServer.Startup] [] Starting Duende IdentityServer version "6.1.2+0222403973d77e72087ead9adc5806053d0b45fa" (".NET 6.0.9") 
  2022-11-29 08:04:49.266 -07:00 [WRN] [Duende.License] [] You do not have a valid license key for the Duende software. This is allowed for development and testing scenarios. If you are running in production you are required to have a licensed version. Please start a conversation with us: https://duendesoftware.com/contact 
  2022-11-29 08:04:49.272 -07:00 [INF] [Duende.IdentityServer.Startup] [] Using explicitly configured authentication scheme "Identity.Application" for IdentityServer 
  2022-11-29 08:04:49.272 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Using "Identity.Application" as default ASP.NET Core scheme for authentication 
  2022-11-29 08:04:49.273 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Using "Identity.External" as default ASP.NET Core scheme for sign-in 
  2022-11-29 08:04:49.273 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Using "Identity.External" as default ASP.NET Core scheme for sign-out 
  2022-11-29 08:04:49.273 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Using "Identity.Application" as default ASP.NET Core scheme for challenge 
  2022-11-29 08:04:49.273 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Using "Identity.Application" as default ASP.NET Core scheme for forbid 
  2022-11-29 08:04:49.486 -07:00 [WRN] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [] No XML encryptor configured. Key {55f7552c-0d0f-4a91-970b-ff83c25660f4} may be persisted to storage in unencrypted form. 

  2022-11-29 08:04:49.713 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Login Url: "/glaucus" 
  2022-11-29 08:04:49.714 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Login Return Url Parameter: "ReturnUrl" 
  2022-11-29 08:04:49.714 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Logout Url: "/Account/Logout" 
  2022-11-29 08:04:49.715 -07:00 [DBG] [Duende.IdentityServer.Startup] [] ConsentUrl Url: "/consent" 
  2022-11-29 08:04:49.715 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Consent Return Url Parameter: "returnUrl" 
  2022-11-29 08:04:49.715 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Error Url: "/home/error" 
  2022-11-29 08:04:49.715 -07:00 [DBG] [Duende.IdentityServer.Startup] [] Error Id Parameter: "errorId" 
  2022-11-29 08:04:49.732 -07:00 [DBG] [Duende.IdentityServer.Hosting.EndpointRouter] [] Request path "/.well-known/openid-configuration" matched to endpoint type "Discovery" 
  2022-11-29 08:04:49.735 -07:00 [DBG] [Duende.IdentityServer.Hosting.EndpointRouter] [] Endpoint enabled: "Discovery", successfully created handler: "Duende.IdentityServer.Endpoints.DiscoveryEndpoint" 
  2022-11-29 08:04:49.737 -07:00 [INF] [Duende.IdentityServer.Hosting.IdentityServerMiddleware] [] Invoking IdentityServer endpoint: "Duende.IdentityServer.Endpoints.DiscoveryEndpoint" for "/.well-known/openid-configuration" 
  2022-11-29 08:04:49.738 -07:00 [DBG] [Duende.IdentityServer.Endpoints.DiscoveryEndpoint] [] Start discovery request 
  2022-11-29 08:04:49.795 -07:00 [ERR] [Duende.IdentityServer.Services.KeyManagement.KeyManager] [] Error unprotecting key with kid "3BEAFC2E3BC6864A430964B01C1A24BC". 
 System.Security.Cryptography.CryptographicException: . For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
 2022-11-29 08:04:49.887 -07:00 [ERR] [Duende.IdentityServer.Services.KeyManagement.KeyManager] [] Error unprotecting key with kid "7F46A5CB09AF1463867B95180D336B87". 
 System.Security.Cryptography.CryptographicException: The key {ae0210c0-ce54-4880-acf3-b261f8f082d0} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```
   repeats this for each entry in the keys table.
   Subsequent login attempts generate a new key and it allows a login.  The login flow does appear to work

**Additional context**
Had read on a separate thread the automatic key rotation does not work on community edition which we are using in our lower environments.  If that's the case, is the above just expected noise?

**Comment by josephdecock** [comment]
Licensing problems log messages to alert you that they need to be fixed, but don't prevent you from using IdenityServer or any of its features. Also, you don't need a license to use dentity server in a non-production environment. 

The signing keys get encrypted and decrypted using microsoft's data protection feature. Data protection manages its own encryption key separately from the signing key that IdentityServer uses. The data protection keys can cause problems if you have a key stored in your signing key store, but try to decrypt it without the data protection key that encrypted it..

There are several ways that this can occur:
1. In load balanced environments, every instance of IdentityServer needs to share signing keys, and you need to configure data protection to do so. Microsoft has extension docs [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview).
2. Signing keys could be generated in a (local) development environment and then accidentally included into the build output. 
3. Data protection creates keys isolated by application name automatically. If you don't specify a name, the content root path of the application will be used. But, beginning in .NET 6.0 Microsoft changed how they handle the path, which can cause data protection keys to break. Their docs on the problem are [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0#setapplicationname), including a work-around where you de-normalize the path.

**Comment by chrisrestall** [comment]
Thank you joseph, that appears to be the issue
