### ISSUE TITLE
Calls to ToEntity() fails in .net7 during database initialization

### ISSUE THREAD

**Issue by emonney** [DuendeSoftware/Support#380]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
net7.0

**Describe the bug**
Calls to client.ToEntity(), resource.ToEntity(), scope.ToEntity() during database initialization fails in .net7 due to a bug introduced in AutoMapper in .net7 https://github.com/AutoMapper/AutoMapper/pull/3999 

**To Reproduce**
1. Take your sample at https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Quickstarts/4_EntityFramework/src/IdentityServer/IdentityServer.csproj
2. Upgrade it from net6.0 to net7.0 (Optionally upgrade all NuGet packages)
3. Build and run the project

**Expected behavior**
The server should start up without errors. i.e. Display "Now listening on: https://localhost:5001" in  the console

**Log output/exception with stacktrace**

```
[10:26:01 INF] Starting up
[10:26:04 Fatal]
Unhandled exception
System.TypeInitializationException: The type initializer for 'Duende.IdentityServer.EntityFramework.Mappers.ClientMappers' threw an exception.
 ---> System.ArgumentException: GenericArguments[0], 'System.Char', on 'T MaxFloat[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
 ---> System.Security.VerificationException: Method System.Linq.Enumerable.MaxFloat: type argument 'System.Char' violates the constraint of type parameter 'T'.
   at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at AutoMapper.TypeDetails.<>c__DisplayClass30_1.<BuildPublicNoArgExtensionMethods>b__10(MethodInfo extensionMethod)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToArray()
   at AutoMapper.TypeDetails.BuildPublicNoArgExtensionMethods(IEnumerable`1 sourceExtensionMethodSearch)
   at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
   at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
   at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.Internal.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
   at AutoMapper.ProfileMap.CreateTypeDetails(Type type)
   at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options, Boolean isReverseMap)
   at AutoMapper.ProfileMap.BuildTypeMap(IConfigurationProvider configurationProvider, ITypeMapConfiguration config)
   at AutoMapper.ProfileMap.Register(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at Duende.IdentityServer.EntityFramework.Mappers.ClientMappers..cctor() in /_/src/EntityFramework.Storage/Mappers/ClientMappers.cs:line 16
   --- End of inner exception stack trace ---
   at Duende.IdentityServer.EntityFramework.Mappers.ClientMappers.ToEntity(Client model) in /_/src/EntityFramework.Storage/Mappers/ClientMappers.cs:line 39
   at IdentityServer.HostingExtensions.InitializeDatabase(IApplicationBuilder app) in C:\DelMe\Quickstarts\4_EntityFramework\src\IdentityServer\HostingExtensions.cs:line 26
   at IdentityServer.HostingExtensions.ConfigurePipeline(WebApplication app) in C:\DelMe\Quickstarts\4_EntityFramework\src\IdentityServer\HostingExtensions.cs:line 108
   at Program.<Main>$(String[] args) in C:\DelMe\Quickstarts\4_EntityFramework\src\IdentityServer\Program.cs:line 19

[10:26:04 Information]
Shut down complete


C:\DelMe\Quickstarts\4_EntityFramework\src\IdentityServer\bin\Debug\net7.0\IdentityServer.exe (process 16664) exited with code 0.
Press any key to close this window . . .

```

**Additional context**

**Comment by emonney** [comment]
The "Directory.Build.targets" file in a parent directory of the samples project was reverting IdentityServer to an earlier version.
This issue does not occur in version 6.2.0 of IdentityServer
