### ISSUE TITLE
Token Generation using IdentityServerTools exception in logs.

### ISSUE THREAD

**Issue by damikun** [DuendeSoftware/Support#403]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
.Net7

**Describe the bug**
Im manualy generating tokens somethink like Github do to allow you long lifetime tokens access your API...

Some question for this topic:

1) ~~When i manualy generate token using `IdentityServerTools` i get the token (its working) but console also log the exception... Im not sure why this is happening in back... (I tried Enable/Disable keymanagment and turn off dataprotection...~~)

2) Also i woud like to ask if this generated token is stored by ID Server.. If yes Where? Can i query list of tokens or Ids of this tokens? Or shoud i store list by myself (for revocation reason)...

3) Plan to extend `IdentityServerTools` to support `Revocation` from code without hitting endpoint?

4) Can i even revocat the token created uding `IdentityServerTools` i have no success yet... With message `No matching token found` Is this generated token Reference Type? The client is configured to provide  reference `AccessTokenType = AccessTokenType.Reference,` but does this tool look on this?

Thx...

```c#
var result = await tool.IssueClientJwtAsync(
  "api_client",
  3600,
 new string[] { "read", "write" });
```

In the logs i see this, but token is generated...
```
System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```

**Additional context**

Im using Identity server with ASPNetIdentitiy....

**Comment by josephdecock** [comment]
We have a sample for Personal Access Tokens which is probably doing what you are looking for:
https://docs.duendesoftware.com/identityserver/v6/samples/tokens/#personal-access-tokens-pat

The IdentityServerTools only issues access tokens in the JWT format. What the sample shows is that you can use the ITokenCreationService to create access tokens that are reference tokens instead. JWTs are not stored in identity server and are not revocable. Reference tokens are stored in the persisted grants store and are revocable.

**Comment by damikun** [comment]
Thx Joseph this realy is what i started to implment... One ore question zou said `ITokenCrateionService` but the sample use `ITokenService`

Thay both have method to obtain token.. Do they do equal think ?   

`ITokenCrateionService` =>` Task<string> CreateTokenAsync(Token token);`
 `ITokenCrateionService` => ` Task<string> CreateSecurityTokenAsync(Token token);`

https://github.com/DuendeSoftware/Samples/blob/9f69f81b5b07f9e93c933953faede0e25f270e7f/IdentityServer/v6/PAT/src/IdentityServer/Pages/PAT/Index.cshtml.cs

**Comment by josephdecock** [comment]
Oh, I meant the `ITokenService`. The `ITokenCreationService` is a lower level abstraction that you _could_ use, but the `ITokenService` is easier to work with here.

**Comment by damikun** [comment]
All question answered.. The Personal token integration is working! thx...
