### ISSUE TITLE
6.2.0 with Autofac

### ISSUE THREAD

**Issue by DevOnBike** [DuendeSoftware/Support#423]
**Which version of Duende IdentityServer are you using?**
6.2.0 (problem exists from version 6.1.8+)

**Which version of .NET are you using?**
.net 6

**Describe the bug**

app can't start due to reolving service as null in autofac - autofac not allow to resolve service as null by default

**To Reproduce**

update to given version of IS and use Autofac

**Expected behavior**

**Log output/exception with stacktrace**

```
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Duende.IdentityServer.Services.DefaultSessionCoordinationService -> λ:Duende.IdentityServer.Stores.IServerSideSessionStore.
 ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'Duende.IdentityServer.Stores.IServerSideSessionStore' returned null.
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)
   at lambda_method785(Closure , Object , HttpContext , IServiceProvider )
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<UseMiddleware>b__2(HttpContext context)
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Additional context**

.

**Comment by josephdecock** [comment]
If you call `AddServerSideSessions`, that should ensure that a default implementation of IServerSideSessionStore is registered.

**Comment by DevOnBike** [comment]
> If you call `AddServerSideSessions`, that should ensure that a default implementation of IServerSideSessionStore is registered.

Hmm, 
according to docs https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/ this is optional feature 

by default, the store for the server-side sessions will just be kept in-memory. For production scenarios you will want to configure a durable store either by using our [EntityFramework Core implementation]

so I want to use default approch - in memory ... 
so my current configuration should allow me to change nothing in code and it can still work with no issues

**Comment by DevOnBike** [comment]
I think the problem is in this line: 

https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Services/Default/DefaultSessionCoordinationService.cs#L59

according to best practices it's not the best pattern to be used in code - every service injected into ctor should be resolved to not null, must have implementation (can be some default implementation) ...

**Comment by DevOnBike** [comment]
> If you call `AddServerSideSessions`, that should ensure that a default implementation of IServerSideSessionStore is registered.

If this is a role of registering some default implementations then it should be added in some main IS service collection extension like 

`public static IIdentityServerBuilder AddIdentityServer(this IServiceCollection services, Action<IdentityServerOptions> setupAction)`

Others it may and it confuses developers that want to use it.

**Comment by josephdecock** [comment]
@DevOnBike thanks for getting in touch. I assumed you were using server side sessions, but registering its services in an unusual way. Looks like that isn't the case. Can you confirm, you're not using server side sessions at all?

**Comment by DevOnBike** [comment]
I can confirm that I migrated from 6.1.7 to 6.2.0 without changing any line of c# code - only changes were obvious in csproj files. From version 6.1.8 startup breaks as I pointed. I'm suggesting merge extension method which you pointed in the first place to main extension method for IS which configures basic implementations for identity server.

**Comment by josephdecock** [comment]
Thanks for clarifying and for your feedback. I'm sorry this was confusing for you. In general, we want IdentityServer to be as broadly useful as possible. 

As you point out, there's a great variety of containers that are designed in different ways. We develop and test IdentityServer using Microsoft's default service container and assume the service container will follow its design, which includes indicating optional dependencies in this way. If you want to use a different container, you'll need to configure it to allow nulls. I'm not an expert on autofac, but according to [this](https://stackoverflow.com/questions/28415227/how-to-make-an-optional-dependency-in-autofac) you can strong-arm it into accepting nulls:

```cs
builder.RegisterType<Target>().WithParameter(TypedParameter.From<IPerson>(null));
```

**Comment by DevOnBike** [comment]
I think that m$ ioc container doesn't follow best practices in some cases and have some big limitations that's why people use autofac and others. 

Optional parameters in ctor is bad design that autofac doesn't support out of the box. Better approach is to have some default no-op implementation rather ending with some nasty if syntax. 

Duende docs are  clear about addserversidesessions method which you describe as required but they say its optional. 

All in all identity server is very good product but there is some space for improvements.

**Comment by josephdecock** [comment]
Again, thanks for your feedback! I also want to be clear, I'm not saying that AddServerSideSessions is required - I made a bad assumption about how you were using and registering services, and that led me to suggest the call to AddServerSideSessions. You're right, the docs do say that ServerSideSessions are an optional feature, and they are. But, we don't support Autofac in the sense that we intend to keep using this pattern of nulls for optional dependencies, while AutoFac will try to prevent that. 

I'm closing this issue now, but feel free to open another one if you have any other questions. And once again, thanks!
