### ISSUE TITLE
Access Token issue - "Headers are read-only, response has already started" exception

### ISSUE THREAD

**Issue by FilipposAl** [DuendeSoftware/Support#425]
Hi,

I'm using Duende IdentityServer 6.1.7 and I have a .NET 6 Blazor Server app.

Alongside the client app, there's a .NET 6 API that is being used for data access.

The AccessTokenType is set to Reference and it's lifetime is left to it's default value.

After an hour has passed, the following exception is thrown:

> System.InvalidOperationException
  HResult=0x80131509
  Message=Headers are read-only, response has already started.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_SetCookie(StringValues value)
   at Microsoft.AspNetCore.Http.ResponseCookies.Append(String key, String value, CookieOptions options)
   at Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager.AppendResponseCookie(HttpContext context, String key, String value, CookieOptions options)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<HandleSignInAsync>d__26.MoveNext()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<SignInAsync>d__17.MoveNext()
   at IdentityModel.AspNetCore.AccessTokenManagement.AuthenticationSessionUserAccessTokenStore.<StoreTokenAsync>d__7.MoveNext()
   at IdentityModel.AspNetCore.AccessTokenManagement.UserAccessAccessTokenManagementService.<RefreshUserAccessTokenAsync>d__9.MoveNext()
   at IdentityModel.AspNetCore.AccessTokenManagement.UserAccessAccessTokenManagementService.<>c__DisplayClass7_0.<<GetUserAccessTokenAsync>b__1>d.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at Microsoft.AspNetCore.Authentication.TokenManagementHttpContextExtensions.<GetUserAccessTokenAsync>d__0.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at IdentityModel.AspNetCore.AccessTokenManagement.UserAccessTokenHandler.<SetTokenAsync>d__4.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at PSPv2.Shared.Helpers.ApiHandler.<Get>d__5`1.MoveNext() in C:\Users\filippos-alekou\source\repos\PSPv2\PSPv2.Shared\Helpers\ApiHandler.cs:line 61

The same exception appears in the browser's console as well. I've attached log [localhost-1671100564755.log](https://github.com/DuendeSoftware/Support/files/10343789/localhost-1671100564755.log)

After the exception is thrown, it becomes impossible to access the API and the only way round it is to log out and log back in again. 

Originally, I assumed it was a configuration issue, and the token is not being refreshed, but after digging a little, it looks like the Token Management middleware is unable to update the authorisation header on the Http calls.

Is there a solution or a workaround to this?

Following, a description of the configuration:

**Blazor Client - Program.cs**
```
builder.Services.AddAccessTokenManagement();

builder.Services.AddHttpClient(ConfigConstants.APIHttpClientName, client =>
{
    client.BaseAddress = new Uri(AppSettings.PSPv2APIUri);
    client.DefaultRequestHeaders.Clear();
    client.DefaultRequestHeaders.Add(HeaderNames.Accept, "application/json");
})
.AddUserAccessTokenHandler();
```
**IdentityServer - Client set-up**

```public static IEnumerable<Client> Clients =>
        new Client[]
            {
                new Client
                {
                    ClientName = ClientConfigValues.ClientName,
                    ClientId = ClientConfigValues.ClientId,
                    AllowedGrantTypes = GrantTypes.Code,
                    AccessTokenType = AccessTokenType.Reference, // instead of classic JWT
                    AllowOfflineAccess = true,
                    UpdateAccessTokenClaimsOnRefresh = true,
                    AbsoluteRefreshTokenLifetime = 1209600, // 14 days
                    SlidingRefreshTokenLifetime = 604800, // 7 days
                    RedirectUris =
                    {
                        "https://localhost:7198/signin-oidc"
                    },
                    PostLogoutRedirectUris =
                    {
                        "https://localhost:7198/signout-callback-oidc"
                    },
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "roles",
                        "pspv2api.fullaccess"
                    },
                    ClientSecrets =
                    {
                        new Secret(ClientConfigValues.ClientSecret.ToSha256())
                    }
                }
            };
```
**API - Program.cs**

```
private static void AddSecurity(this IServiceCollection services)
        {
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddOAuth2Introspection(options =>
                {
                    options.Authority = ClientSettings.Authority;
                    options.ClientId = ClientSettings.ClientId;
                    options.ClientSecret = ClientSettings.ClientSecret;
                    options.NameClaimType = "name";
                    options.RoleClaimType = "role";
                });
        }
```

**Comment by leastprivilege** [comment]
What type of Blazor application is this? Blazor Server or Blazor WASM with hosted backend?

**Comment by FilipposAl** [comment]
It is Blazor Server

**Comment by leastprivilege** [comment]
Duende.AccessTokenManagement does not work for Blazor Server as it is. That's because internally you are not allowed to touch the HttpContext there.

See here:
https://github.com/DuendeSoftware/Duende.AccessTokenManagement/wiki/blazor-server

**Comment by FilipposAl** [comment]
@leastprivilege thanks, I was not aware of this particular issue. I will try the workaround.

**Comment by FilipposAl** [comment]
I'm afraid the workaround is not solving the issue. I'm getting the exact same exception now thrown from this line:

`var token = await _tokenManagementService.GetAccessTokenAsync(state.User);`

**Comment by leastprivilege** [comment]
This is not possible, since there are no cookies involved anymore.

Since D.ATM is not really a supported product but an FOSS library, I am transferring this issue into its own repo.
