### ISSUE TITLE
IdentityServerMiddleware unhandled exception logging

### ISSUE THREAD

**Issue by dIeGoLi** [DuendeSoftware/Support#452]
**Which version of Duende IdentityServer are you using?**
v6

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

It's not a bug, rather an optimization. IdentityServerMiddleware logs all unhandled exceptions as Critical/Fatal.

**To Reproduce**

throw BadHttpRequestException

**Expected behavior**

A BadHttpRequestException I think is most likely a client problem. I would prefer that type of exception to be logged as warning.
I could ignore the message in my log monitoring, but i think it would be better to not log this non critical exception as critical.

**Log output/exception with stacktrace**
```
Unexpected end of request content.

Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Duende.IdentityServer.Validation.PostBodySecretParser.ParseAsync(HttpContext context) in /_/src/IdentityServer/Validation/Default/PostBodySecretParser.cs:line 107\n   at Duende.IdentityServer.Validation.SecretParser.ParseAsync(HttpContext context) in /_/src/IdentityServer/Validation/Default/SecretParser.cs:line 45
   at Duende.IdentityServer.Validation.ClientSecretValidator.ValidateAsync(HttpContext context) in /_/src/IdentityServer/Validation/Default/ClientSecretValidator.cs:line 110
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 116\n   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 82
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
```

**Comment by josephdecock** [comment]
We added a new option to filter exceptions before they are logged in version 6.2, called `UnhandledExceptionLoggingFilter`.

To quote our docs:

>This is a function that is called when the IdentityServer middleware detects an unhandled exception, and is used to determine if the exception is logged. The arguments to the function are the HttpContext and the Exception. It should return true to log the exception, and false to suppress. The default is to suppress TaskCanceledExceptions. Such exceptions are thrown when Http requests are canceled, which is an expected occurrence. Logging them creates unnecessary noise in the logs.

**Comment by dIeGoLi** [comment]
oh i should have figured that out myself. thanks for the hint!

**Comment by josephdecock** [comment]
No problem, happy to point you at our new features :)
