### ISSUE TITLE
PersistedGrant.Key length and System.Text.Json.JsonException when reading from persisted grant store

### ISSUE THREAD

**Issue by nhumby** [DuendeSoftware/Support#489]
**Which version of Duende IdentityServer are you using?**
6.1

**Which version of .NET are you using?**
7.0

**Describe the bug**

My first question is how long does the Key property on the PersistedGrant.cs class get? I can't use nvarchar(max) as a primary key for a table and if I set an arbitrary value (like 128) then it won't be efficient with space usage. 

My second question, I've implemented the IPersistedGrantStore and created the necessary infrastructure to store the data in a SQL table. When I sign in with my persisted grant store enabled it breaks down. I see this data in my new table though: 

Key                                                               Type                SubjectId                             SessionId                         ClientId  Description                  Expiration               ConsumedTime            Data
----------------------------------------------------------------- ------------------- ------------------------------------- --------------------------------- --------- ---------------------------- ------------------------ ----------------------- -----------------------------------------------------------------
E19948DE92E876DBE04B6282945F55BD6E365C796816B1DC298E386FB22FC09F  authorization_code  3912c686-341f-4928-b6c3-aa163d56696d  9177ED73CE93734951E286BE36DB4708  UX                                     2023-02-06 16:44:00.000  NULL                    E19948DE92E876DBE04B6282945F55BD6E365C796816B1DC298E386FB22FC09F

(1 row affected)

and I'm seeing the following in the Serilog file. Is one of the columns supposed to be in a JSON format? I left it to format the data contents itself and haven't seen anything in the reference documenation covering this:

[16:39:29 Debug] Duende.IdentityServer.Validation.TokenRequestValidator
Start token request validation

[16:39:29 Debug] Duende.IdentityServer.Validation.TokenRequestValidator
Start validation of authorization code token request

[16:39:29 Error] Duende.IdentityServer.Stores.DefaultAuthorizationCodeStore
Failed to deserialize JSON from grant store.
System.Text.Json.JsonException: 'E' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'E' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize[T](String json) in /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:line 93
   at Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemByHashedKeyAsync(String hashedKey) in /_/src/IdentityServer/Stores/Default/DefaultGrantStore.cs:line 137

[16:39:29 Debug] Duende.IdentityServer.Stores.DefaultAuthorizationCodeStore
authorization_code grant with value: 0B3751E2977FEEC2213A82FDAFC6E320C3DF6E2264C8C4848E712399B7C2E96D-1 not found in store.

[16:39:29 Error] Duende.IdentityServer.Validation.TokenRequestValidator
Invalid authorization code{"code":"0B3751E2977FEEC2213A82FDAFC6E320C3DF6E2264C8C4848E712399B7C2E96D-1"}, details: {"ClientId":"UX","ClientName":null,"GrantType":"authorization_code","Scopes":null,"AuthorizationCode":"****6D-1","RefreshToken":"********","UserName":null,"AuthenticationContextReferenceClasses":null,"Tenant":null,"IdP":null,"Raw":{"client_id":"UX","client_secret":"***REDACTED***","code":"0B3751E2977FEEC2213A82FDAFC6E320C3DF6E2264C8C4848E712399B7C2E96D-1","grant_type":"authorization_code","redirect_uri":"https://localhost/UX/Render","code_verifier":"rXXHWKCqjDJW8SL1h_aFWrglcFmZvbqHAAYDJ6nhfWo"},"$type":"TokenRequestValidationLog"}

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
Our implementation of the IPersistedGrantsStore uses a length of 200 for the key column and has an autoincremented integer id column separately from the key column used as the primary key.

IdentityServer 6.1 doesn't support .NET 7, but IdentityServer 6.2 does. Please make sure you're using compatible versions (either IdentityServer 6.2 with .NET 7, or IdentityServer 6.1 with .NET 6), and let us know if that resolves the second issue.

**Comment by nhumby** [comment]
Thanks, so the int Id field is only in the DB as a PK and not referenced in any of the C# classes that work on the data? Is your implementation published anywhere?

I upgraded but the same problem occurs, logs below:

[17:32:22 Information] Duende.IdentityServer.Startup
Starting Duende IdentityServer version 6.2.3+84bc142f65e28cf26ac3f96a70fe4722647acbc0 (.NET 7.0.1)

<snip>

[17:33:06 Debug] Duende.IdentityServer.Validation.TokenRequestValidator
Start token request validation

[17:33:06 Debug] Duende.IdentityServer.Validation.TokenRequestValidator
Start validation of authorization code token request

[17:33:06 Error] Duende.IdentityServer.Stores.DefaultAuthorizationCodeStore
Failed to deserialize JSON from grant store.
System.Text.Json.JsonException: 'F' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize[T](String json) in /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:line 94
   at Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemByHashedKeyAsync(String hashedKey) in /_/src/IdentityServer/Stores/Default/DefaultGrantStore.cs:line 137

[17:33:06 Debug] Duende.IdentityServer.Stores.DefaultAuthorizationCodeStore
authorization_code grant with value: 8277991E5D5F2F175B25A7AAA77083253935F57018C49FC1724B37BE67C946E3-1 not found in store.

[17:33:06 Error] Duende.IdentityServer.Validation.TokenRequestValidator
Invalid authorization code{"code":"8277991E5D5F2F175B25A7AAA77083253935F57018C49FC1724B37BE67C946E3-1"}, details: {"ClientId":"UX","ClientName":null,"GrantType":"authorization_code","Scopes":null,"AuthorizationCode":"****E3-1","RefreshToken":"********","UserName":null,"AuthenticationContextReferenceClasses":null,"Tenant":null,"IdP":null,"Raw":{"client_id":"UX","client_secret":"***REDACTED***","code":"8277991E5D5F2F175B25A7AAA77083253935F57018C49FC1724B37BE67C946E3-1","grant_type":"authorization_code","redirect_uri":"https://localhost/UX/Render","code_verifier":"yN2Y-BVyRTTJVIMCT8YpnmX_Z4kwXWLYAPfVWojADTs"},"$type":"TokenRequestValidationLog"}

[17:33:06 Information] Duende.IdentityServer.Events.DefaultEventService
{"ClientId":"UX","ClientName":null,"RedirectUri":null,"Endpoint":"Token","SubjectId":null,"Scopes":null,"GrantType":"authorization_code","Error":"invalid_grant","ErrorDescription":null,"Category":"Token","Name":"Token Issued Failure","EventType":"Failure","Id":2001,"Message":null,"ActivityId":"80000004-0004-eb00-b63f-84710c7967bb","TimeStamp":"2023-02-06T17:33:06.1819063Z","ProcessId":35372,"LocalIpAddress":"::1:443","RemoteIpAddress":"::1","$type":"TokenIssuedFailureEvent"}

[17:33:06 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP POST /identity/connect/token responded 400 in 146.0648 ms

**Comment by josephdecock** [comment]
Our implementation of the stores is written with EntityFramework and works with any database with an EF provider. We document it [here](https://docs.duendesoftware.com/identityserver/v6/data/ef/). The json deserialization errors look like you have some invalid data in the table, but the simplest thing is probably just to switch to our implementation of the stores, unless you have a compelling reason to build something custom.

**Comment by nhumby** [comment]
Unfortunately I'm having to use an existing database (we're upgrading from an Identity Server 3 implementation that looks like it wasn't done as well as it should have been). For technical reasons I'm stuck using the old database though I'm free to create new tables for this, as I've done. The table data I'm just passing straight through into the tables using stored procedures, I don't modify it anywhere so I'm a bit lost with how any of it could be wrong. It all worked fine for my Clients table. The only bit that looked weird in PersistedGrants table data was the Key and Data fields held the same values, is that incorrect? I remember the old Identity Server Tokens table had a JSON column, is one of the PersistedGrants table fields supposed to be in JSON format? I've looked at your implementation and while it contains the table structure there's no examples of the actual data contents to expect in the PersistedGrants table, can you paste some redacted examples from your table that may help me spot what's gone wrong with mine?
