### ISSUE TITLE
RequireResourceIndicator causes resource aud claim to be removed.

### ISSUE THREAD

**Issue by dorien-gray** [DuendeSoftware/Support#507]
I am using the latest version of identity server and .net core.

When I set RequireResourceIndicator to true on my API Resource by API no longer receives the aud claim and hence I cannot validate that aud claim.  If I change the RequireResourceIndicator to false every works as expected.  I have gone around the houses all weekend on this and their are not many examples that seem to use this.

**To Reproduce**
To reproduce simple set the RequireResourceIndicator to true and check the claims in the client.  The aud claim is missing.

**Expected behavior**

I expect to see the aud claim which is the name of my API Resource in the list of claims on the client.

**Log output/exception with stacktrace**

Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10206: Unable to validate audience. The 'audiences' parameter is empty.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken& signatureValidatedToken, ExceptionDispatchInfo& exceptionThrown)
--- End of stack trace from previous location ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

Here is how my api has been configured which works until I set the RequireResourceIndicator to true.

_ = services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
            {
                options.Authority = config.IdentityServerUrl;
                options.Audience = config.Audience;
                options.RequireHttpsMetadata = config.RequireHttpsMetadata ?? true;
                options.TokenValidationParameters.ValidateAudience = true;
                options.TokenValidationParameters.ValidTypes = new[] { "at+jwt" };
            });

Regards

**Comment by brockallen** [comment]
When your client makes the authorize and token requests, is it using the `resource` parameter, as per RFC8707?

https://www.rfc-editor.org/rfc/rfc8707

**Comment by dorien-gray** [comment]
My mistake.  This is working exactly as stated on the tin.  The problem is a swagger issue.
Sorry to have wasted your time on this.
