### ISSUE TITLE
Error in database connection duende development testing

### ISSUE THREAD

**Issue by Bayah97** [DuendeSoftware/Support#508]
**Which version of Duende BFF are you using?**
Duende IdentityServer version 6.2.1+bda14c367eb8a85f3dae614fa0ac1005bb13dfdc

**Which version of .NET are you using?**
(.NET 6.0.12)

**Question**
Im receiving error cannot connect with database on first run in development testing ? After i logout and login again, there are no problem. Is it because i dont have valid license ?

**Comment by brockallen** [comment]
> Im receiving error cannot connect with database on first run in development testing

Do you have any more details?

> Is it because i dont have valid license ?

No. Invalid license errors are simply surfaced as entries in the logging system: https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key/#license-validation-and-logging

**Comment by brockallen** [comment]
Any updates here?

**Comment by Bayah97** [comment]
Hi, 

I am using seriLog for Duende Identity Server. I found repeating error but in different places. When i run for first time, the error after GET connect/authorize. I stop and run again the identity server, the same error after found bearer token. But after GET connect/authorize log, no error like the first run.

The error Log is:
at Duende.IdentityServer.EntityFramework.Stores.ClientStore.FindClientByIdAsync(String clientId) in /_/src/EntityFramework.Storage/Stores/ClientStore.cs:line 78

**Comment by brockallen** [comment]
> The error Log is:
> at Duende.IdentityServer.EntityFramework.Stores.ClientStore.FindClientByIdAsync(String clientId) in /_/src/EntityFramework.Storage/Stores/ClientStore.cs:line 78

Is there more info here from the logs? I can't tell from this alone what the problem might be.

**Comment by Bayah97** [comment]
Hi

This is my code for identity server:
 
public static WebApplication ConfigureServices(this WebApplicationBuilder builder)
    {
        builder.Services.AddRazorPages();

        var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

        builder.Services.AddDbContext<ApplicationDbContext>(options =>
            options.UseSqlServer(connectionString));

        builder.Services.AddIdentity<ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>();

        builder.Services.AddIdentityServer(options =>
            {
                //to show events in serilog
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;

                //include an audience claim in the issued tokens
                options.EmitStaticAudienceClaim = true;

                //use key management to secure communication(Signing key)
                options.KeyManagement.Enabled = true;

                //digital signatures generated
                options.KeyManagement.SigningAlgorithms = new[]
                {
                    // RS256 for older clients (with additional X.509 wrapping)
                    new SigningAlgorithmOptions(SecurityAlgorithms.RsaSha256) { UseX509Certificate = true },
                };
            })
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = b => b.UseSqlServer(connectionString);
            })
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = b => b.UseSqlServer(connectionString);
            })
            .AddAspNetIdentity<ApplicationUser>();

        builder.Services.AddCors(options =>
        {
            options.AddPolicy("CorsPolicy",
            builder => builder.AllowAnyHeader()
            .AllowAnyOrigin()
            .AllowAnyMethod());
        });

            return builder.Build();
     }

**Comment by brockallen** [comment]
> Is there more info here from the logs? I can't tell from this alone what the problem might be.

We need error logs, I think. They should contain the message as to the problem.

**Comment by Bayah97** [comment]
Here the error log:

[11:15:23 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Duende.IdentityServer.EntityFramework.Stores.ClientStore.FindClientByIdAsync(String clientId) in /_/src/EntityFramework.Storage/Stores/ClientStore.cs:line 78
   at Duende.IdentityServer.Stores.ValidatingClientStore`1.FindClientByIdAsync(String clientId) in /_/src/IdentityServer/Stores/ValidatingClientStore.cs:line 54
   at Duende.IdentityServer.Stores.IClientStoreExtensions.FindEnabledClientByIdAsync(IClientStore store, String clientId) in /_/src/IdentityServer/Extensions/IClientStoreExtensions.cs:line 23
   at Duende.IdentityServer.Validation.TokenValidator.ValidateJwtAsync(String jwtString, IEnumerable`1 validationKeys, Boolean validateLifetime, String audience) in /_/src/IdentityServer/Validation/Default/TokenValidator.cs:line 335
   at Duende.IdentityServer.Validation.TokenValidator.ValidateAccessTokenAsync(String token, String expectedScope) in /_/src/IdentityServer/Validation/Default/TokenValidator.cs:line 154
   at Duende.IdentityServer.Validation.UserInfoRequestValidator.ValidateRequestAsync(String accessToken) in /_/src/IdentityServer/Validation/Default/UserInfoRequestValidator.cs:line 52
   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessUserInfoRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 81
   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 62
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 101
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>g__InvokeCoreAwaited|15_0(HttpContext context, Task`1 policyTask)
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by brockallen** [comment]
>  System.Threading.Tasks.TaskCanceledException: A task was canceled.

Ok, this is the exception. You can ignore this, as it's related to all of this: https://github.com/DuendeSoftware/IdentityServer/pull/1084

and this: https://github.com/DuendeSoftware/IdentityServer/issues/1040

The filter we added in the PR can help, so I'd suggest updating to that version (6.2.0).

**Comment by Bayah97** [comment]
My duende version is this:
Duende IdentityServer version 6.2.1

Do i need to downgrade it to 6.2.0 ? 
and will this solve the issue of multiple insert data in database ?

**Comment by brockallen** [comment]
> My duende version is this: Duende IdentityServer version 6.2.1

Oh I'm sorry -- I misread it from above. You should be on the correct version that filters the exceptions.

So looking more at your call stack, it looks like the DeveloperExceptionPageMiddleware is catching it and logging (and maybe re-throwing the exception). In short, this is something you should catch and decide if you allow it to be logged and/or re-thrown. Also, do you enable DeveloperExceptionPageMiddleware in production? If not, then maybe this is something you only see at dev time.

This scenario is caused by the browser closing the connection, which is not really a bug and also not something you can really do much about. Just manage it the best you can in the way you want to.

**Comment by josephdecock** [comment]
Any further update here? Can we close this issue?

**Comment by Bayah97** [comment]
Yup, Thank you @brockallen
