### ISSUE TITLE
IClientCredentialsTokenManagementService not injectable into HostedService

### ISSUE THREAD

**Issue by demdh** [DuendeSoftware/Support#516]
**Which version of Duende IdentityServer are you using?**

1.0.0

**Which version of .NET are you using?**

.NET 7.0

**Describe the bug**

`IClientCredentialsTokenManagementService` can't be injected properly into `HostedService` instances (or any other singleton) 
 due to the scoped registration of ``Microsoft.Extensions.Options.IOptionsSnapshot`1[Duende.AccessTokenManagement.ClientCredentialsClient]``.

An exception is thrown when [Scope validation](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-7.0#scope-validation) is enabled (which is the default for WebHostApplication).

**To Reproduce**

Repro:

Program.cs
```c#
using Duende.AccessTokenManagement;

var builder = WebApplication.CreateBuilder(args);
builder.Host.UseDefaultServiceProvider((_, options) => options.ValidateScopes = true);
builder.Services.AddHostedService<FooService>()
    .AddDistributedMemoryCache()
    .AddClientCredentialsTokenManagement();
builder.Build().Run();

class FooService : BackgroundService
{
    public FooService(IClientCredentialsTokenManagementService _) { }
    protected override Task ExecuteAsync(CancellationToken stoppingToken) => Task.CompletedTask;
}
```

.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Duende.AccessTokenManagement" Version="1.0.0" />
  </ItemGroup>
</Project>
```

**Expected behavior**

An instance of type `IClientCredentialsTokenManagementService` should be able to be injected into instances of type `IHostedService`.

**Log output/exception with stacktrace**

```Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll: 'Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Duende.AccessTokenManagement.ClientCredentialsClient]' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.'
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args)
   ```

**Comment by leastprivilege** [comment]
We will have a look

**Comment by tleblanc159** [comment]
@demdh @leastprivilege 

Both this issue and #519 should be able to be addressed by changing the ClientCredentialsTokenEndpointService implementation to accept IOptionsMonitor instead of IOptionsSnapshot.

IOptionsSnapshot has a scoped lifetime so it cannot be properly resolved in a singleton service.

IOptionsMonitor, however, has a singleton lifetime so it can be resolved in transient, scoped, **and** singleton services. ([reference](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0#options-interfaces))

**Comment by leastprivilege** [comment]
Thanks! Do you want to propose a PR?

**Comment by leastprivilege** [comment]
pushing v1.1 right now
