### ISSUE TITLE
Authorize Endpoint AmbiguousMatchException

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#521]
**Which version of Duende IdentityServer are you using?**
Community
**Which version of .NET are you using?**
7.0.102
**Describe the bug**
Tried to follow https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/authorize/ and `curl`ing / postman GET request to `https://localhost:5001/connect/authorize?...` gets the following error response:

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

/Account/Login/Index
/Account/Login
/_Host
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware.InvokeInternal(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
How is `/connect/authorize` endpoint configured?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
If you look at the error, it's telling you that your login page is the problem (not the authorize endpoint).
