### ISSUE TITLE
Next-auth client receives "unauthorized_client" error

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#523]
**Which version of Duende BFF are you using?**
Community
**Which version of .NET are you using?**
7.0.102
**Describe the bug**
Using this example before switching my production application your library https://github.com/nextauthjs/next-auth-example with the following config:

```
{
    "SECRET": "whatever",
    "NEXTAUTH_URL": "http://localhost:3000",
    "IdentityServer4_Issuer": "https://iam.kyberlife.io",
    "IdentityServer4_CLIENT_ID": "buyerportal",
    "IdentityServer4_CLIENT_SECRET": "sorry, can't share this"
}
```
and in `[...nextauth].ts`:
```
export const authOptions: NextAuthOptions = {
  // https://next-auth.js.org/configuration/providers/oauth
  providers: [
    IdentityServer4Provider({
      id: "buyerportal",
      name: "buyerportal",
      authorization: {
        params: { scope: "buyerportal" },
      },
      issuer: process.env.IdentityServer4_Issuer || config.get('IdentityServer4_Issuer'),
      clientId: process.env.IdentityServer4_CLIENT_ID || config.get('IdentityServer4_CLIENT_ID'),
      clientSecret: sha512(process.env.IdentityServer4_CLIENT_SECRET || config.get('IdentityServer4_CLIENT_SECRET')),
    }),
```
results in the following error:
```
Error
Sorry, there was an error : unauthorized_client
Request Id: 0HMOI7RIJ6JLF:00000001
```
I don't see this error in postman. What could go wrong?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by khteh** [comment]
https://github.com/DuendeSoftware/Support/issues/505

**Comment by josephdecock** [comment]
You shouldn't hash the secret in the client. Identity Server stores hashes of secrets, rather than the secrets themselves, but expects the clients to send secrets as plaintext.

**Comment by khteh** [comment]
Still no luck but I see this in the log:
```
{
	ClientId: "buyerportal",
	ClientName: null,
	RedirectUri: "http://localhost:3000/api/auth/callback/buyerportal",
	AllowedRedirectUris: ["https://www.kyberlife.io/api/auth/callback/buyerportal", "http://localhost:3000/api/auth/callback/buyerportal"],
	SubjectId: "anonymous",
	ResponseType: "code",
	ResponseMode: "query",
	GrantType: "authorization_code",
	RequestedScopes: "buyerportal",
	State: "GhaXrwbrom1LJjMgGI1J3kjGopJynexgn_8kp-kGn6g",
	UiLocales: null,
	Nonce: null,
	AuthenticationContextReferenceClasses: null,
	DisplayMode: null,
	PromptMode: "",
	MaxAge: null,
	LoginHint: null,
	SessionId: null,
	Raw: [("client_id": "buyerportal"), ("scope": "buyerportal"), ("response_type": "code"), ("redirect_uri": "http://localhost:3000/api/auth/callback/buyerportal"), ("protection": "pkce"), ("state": "GhaXrwbrom1LJjMgGI1J3kjGopJynexgn_8kp-kGn6g"), ("code_challenge": "Hcg-Jft8JUQYS4-4jVRqN0m5Zl4NwKrew4y6Jouc1Mw"), ("code_challenge_method": "S256")]
}
```
What's missing?

**Comment by josephdecock** [comment]
Is there a "buyerportal" [ApiScope ](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_scopes/) defined?

**Comment by khteh** [comment]
I used multiple `scopes` in the client. Using single `buyerportal` works. However, after successfully logged in and redirected back to the client, I see this error at the client console:
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error id_token not present in TokenSet {
  error: TypeError: id_token not present in TokenSet
      at Client.validateIdToken (/usr/src/next-auth-example/node_modules/openid-client/lib/client.js:737:15)
      at Client.callback (/usr/src/next-auth-example/node_modules/openid-client/lib/client.js:488:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async oAuthCallback (/usr/src/next-auth-example/node_modules/next-auth/core/lib/oauth/callback.js:129:16)
      at async Object.callback (/usr/src/next-auth-example/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/usr/src/next-auth-example/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/usr/src/next-auth-example/node_modules/next-auth/next/index.js:24:19)
      at async /usr/src/next-auth-example/node_modules/next-auth/next/index.js:60:32
      at async Object.apiResolver (/usr/src/next-auth-example/node_modules/next/dist/server/api-utils/node.js:372:9)
      at async NextNodeServer.runApi (/usr/src/next-auth-example/node_modules/next/dist/server/next-server.js:488:9) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'buyerportal',
  message: 'id_token not present in TokenSet'
}
```

**Comment by khteh** [comment]
I have the following config:
```
    public static IEnumerable<ApiScope> ApiScopes =>
        new ApiScope[]
        {
            new ApiScope(name: "buyerportal", displayName: "Buyer Identity"),
            new ApiScope(name: "sellerportal", displayName: "Seller Identity"),
            new ApiScope(name: "adminportal", displayName: "Admin Identity"),
        };
    public static IEnumerable<Client> Clients =>
        new Client[]
        {
            // m2m client credentials flow client
            new Client
            {
                ClientId = "m2m.client",
                ClientName = "Client Credentials Client",
                AllowedGrantTypes = GrantTypes.ClientCredentials,
                ClientSecrets = { new Secret("whatever".Sha512()) },
                AllowedScopes = { "kyberlife-m2m" }
            },

            // interactive client using code flow + pkce
            new Client
            {
                ClientId = "buyerportal",
                ClientSecrets = { new Secret("whatever1".Sha512()) },
                AllowedGrantTypes = new [] { GrantType.AuthorizationCode, GrantType.ResourceOwnerPassword },
                RedirectUris = new [] {"https://www.kyberlife.io/api/auth/callback/buyerportal", "http://localhost:3000/api/auth/callback/buyerportal"} ,
                FrontChannelLogoutUri = "https://iam.kyberlife.io/signout-oidc",
                PostLogoutRedirectUris = { "https://www.kyberlife.io" },
                //This feature refresh token
                AllowOfflineAccess = true,
                AllowedScopes = {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    "buyerportal"
                },
                //Access token life time is  3600 seconds (1 hour)
                AccessTokenLifetime = 3600,
                //Identity token life time is 3600 seconds (1 hour)
                IdentityTokenLifetime = 3600
            },
```
And the following scope in `next-auth` client app:
```
export const authOptions: NextAuthOptions = {
  // https://next-auth.js.org/configuration/providers/oauth
  providers: [
    IdentityServer4Provider({
      id: "buyerportal",
      name: "buyerportal",
      authorization: {
        params: { scope: "openid profile buyerportal", protection: "pkce" },
      },
      issuer: process.env.IdentityServer4_Issuer || config.get('IdentityServer4_Issuer'),
      clientId: process.env.IdentityServer4_CLIENT_ID || config.get('IdentityServer4_CLIENT_ID'),
      clientSecret: process.env.IdentityServer4_CLIENT_SECRET || config.get('IdentityServer4_CLIENT_SECRET'),
    }),
```
This results in `invalid_scope` error. Using single `buyerportal` works. What's the issue?

**Comment by khteh** [comment]
Works now after adding all the scopes.
