### ISSUE TITLE
IdentityServer sometimes returns 500 for google and microsoft authentication

### ISSUE THREAD

**Issue by beyondnagatani** [DuendeSoftware/Support#539]
**Which version of Duende IdentityServer are you using?**
6

**Which version of .NET are you using?**
6

**Describe the bug**
Sometimes google and microsoft authentication returns 500 on IdentityServer. Specifically, /signin-google and /signin-microsoft are returning 500 errors, and the situation is as follows

・About 3,000 requests per minute. ・About 40 of them return 500 errors. ・The rest return 301.

Do you know the cause? Is there a problem with the number of accesses or the external authentication side?

**Log output/exception with stacktrace**

```
Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
SpanId: cb0b1fd3fb5ab07b
TraceId: 0c9278ac8befb1653de7e2113b2167b4
ParentId: 0000000000000000
RequestId: 8000ecf3-0001-f900-b63f-84710c7967bb
RequestPath: /signin-google

An unhandled exception has occurred while executing the request.

Exception: 
System.Exception: An error was encountered while handling the remote login.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|45_0()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.ExchangeCodeAsync(OAuthCodeExchangeContext context)
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 52
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Here is the code**
■ Startup.cs

```
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
        AppSettings.Configuration = configuration;
    }

    public IConfiguration Configuration { get; }
    
    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {

        services.AddIdentityServer(options =>
            {
                options.Caching.ClientStoreExpiration = TimeSpan.FromMinutes(60);
                options.Caching.ResourceStoreExpiration = TimeSpan.FromMinutes(60);
                options.Caching.CorsExpiration = TimeSpan.FromMinutes(60);
            })
                .AddRedirectUriValidator<RedirectUriValidator>()
                .AddInMemoryCaching()
                .AddInMemoryIdentityResources(new IdentityResource[]
                {
                    new IdentityResources.OpenId(), 
                    new IdentityResources.Profile(),
                })
                .AddInMemoryApiScopes(new ApiScope[]
                {
                    new ApiScope(IdentityServerConstants.LocalApi.ScopeName),
                })
                .AddInMemoryPersistedGrants()
                .AddInMemoryCaching()
                .AddInMemoryClients(Configuration.GetSection("Clients"))
                .AddDeveloperSigningCredential()
                .AddAspNetIdentity<User>();

        services.ConfigureApplicationCookie(config =>
        {
            config.LoginPath = "/Web/User/Login";
            config.LogoutPath = "/Web/User/Logout";
            config.ExpireTimeSpan = TimeSpan.FromSeconds(Common.LoginTimeoutSeconds);
        });

        services.AddAuthentication(options =>
        {
            options.DefaultScheme = IdentityConstants.ApplicationScheme;
            options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
        })
        .AddJwtBearer(options =>
        {
            options.SaveToken = true;
            options.RequireHttpsMetadata = false;
            options.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuer = false,
                ValidateAudience = false,
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Common.TokenCreateKey)),
                ClockSkew = TimeSpan.Zero,
            };
        }).AddGoogle(options =>
        {
            options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
            options.ClientId = Configuration.GetValue<string>("GoogleClient:ClientId");
            options.ClientSecret = Configuration.GetValue<string>("GoogleClient:ClientSecret");
        }).AddMicrosoftAccount(options =>
        {
            options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
            options.ClientId = Configuration.GetValue<string>("MicrosoftClient:ClientId");
            options.ClientSecret = Configuration.GetValue<string>("MicrosoftClient:ClientSecret");
        });

        services.AddLocalApiAuthentication();
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseRouting();
            app.UseAuthorization();
            app.UseAuthentication(); 
            app.UseIdentityServer();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
    }
}
```

**Comment by josephdecock** [comment]
This looks similar to issues we've seen where http requests that are  canceled end up in the logs as errors. In some cases, Http request cancellation is actually not unexpected and doesn't deserve to be treated as an error. Where we've seen this in the past, entity framework has been involved - it logs these cancellations at a very high severity and then throws, even though all that happened was that a front end request was cancelled. We made some changes in 6.2 to filter some of this noise out.

Your case might be different, so I would investigate a bit more. Is the cancellation happening when the incoming http request to signin-google was cancelled? If so, these are also safe to ignore. Is this cancellation occurring on the backchannel request to Google for tokens? If so, you probably need to work with your external provider to figure out why they fail about 1% of the time. Since this is happening with multiple external providers, my guess is that the cancellation is on the front channel though.

**Comment by beyondnagatani** [comment]
Thanks for the reply.
I have checked the version you are using, and since you are using 6.1.0, I will upgrade to 6.2 or higher and see how it goes.

As for whether the problem is occurring in the front or back channel, I am not sure how to identify the cause in the first place, but would it be possible for you to tell us how to identify the cause?

**Comment by josephdecock** [comment]
If you handle the error event in the OIDC handler, you should be able to look at the context passed to that event for the http context and see if the request was canceled.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
