### ISSUE TITLE
 Upgrade IdentityServer4 (version 3.0.1.0) to Duende Identity Server 6.0

### ISSUE THREAD

**Issue by imharry4u** [DuendeSoftware/Support#600]
We created a new IdentityServer6 project with the EntityFramework integration already added by ‘dotnet new isef’

1.     Tested with client and we did got AccessToken. Works Perfectly.
2.     We restore our existing_IdentityServer_DB on DEV server.
3.     Used SQLServer reference, change the connection string to existing_IdentityServer_DB.
4.     Updated the schema changes including the new tables as required for ID6.
5.     Welcome screen and discovery document shows up successfully connecting to existing_IdentityServer_DB.
6.     We are able to login successfully and application is working, but logs the following error in Seq.

Error unprotecting key with kid 6188E560C706C2A4B6FDFB5027DB1F07.
SourceContext : Duende.IdentityServer.Services.KeyManagement.KeyManager
System.Security.Cryptography.CryptographicException: The key {c5fcae48-9c73-4f9e-8447-a93922c62b70} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435

**Comment by josephdecock** [comment]
Automatic Key Management is enabled by default, so the code you added shouldn't have an effect. Since you've just upgraded, you probably have both automatic keys and manual keys, which is a combination that we deliberately allow to allow for a smooth transition from manual to automatic signing keys.

**Comment by imharry4u** [comment]
Are you configuring Data Protection explicitly? No
Do you have multiple load balanced instances? No
Also user is able to login successfully, but error is still log in Seq.

**Comment by imharry4u** [comment]
![image](https://user-images.githubusercontent.com/18617947/229788894-3eea4606-f664-43e5-8b8a-de5befd26881.png)

**Comment by imharry4u** [comment]
Attached is whole trace if that's help.

![image](https://user-images.githubusercontent.com/18617947/229893637-ae89a29b-04a5-41af-b2ea-9d79c89b7b90.png)

**Comment by josephdecock** [comment]
You have signing keys that were data protected in such a way that your running application cannot decrypt. My guess is, you may have created those keys during development (and thus protected them with your dev machine's data protection keys). Do you have the keys directory included in source control? If so, delete the keys and add the directory to .gitignore.

**Comment by josephdecock** [comment]
Is this resolved? Can we close this issue?

**Comment by josephdecock** [comment]
Okay, no problem. Did you not end up  having keys in source control then?

**Comment by josephdecock** [comment]
Are you running in IIS? If so, at startup I'm guessing you're seeing a log message saying that you're using an ephemeral data protection key. That would indicate that your IIS isn't able to persist data protection keys, so every time you start up, you get a new data protection key. That key can't decrypt your signing keys in your database, so IdentityServer fails to read any of them and generates a new signing key, protected by the new data protection key. This happens every time you restart the site, resulting in the dozen+ keys that you now have.

You'll need to configure IIS to be able to persist data protection keys. Microsoft has good docs on how to do so [here](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-7.0#data-protection).

**Comment by imharry4u** [comment]
I will get back to this next week, as i am working on some other high
priority task for this week.
--

*Thanks & Regards,*

*Harish Patel*
********************************************************************************************
This e-mail and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom it is addressed.  If
you are not the intended recipient or the person responsible for delivering
the e-mail to the intended recipient, then you are hereby advised that you
have received this e-mail in error and that any use, dissemination,
forwarding, printing or copying of this e-mail is strictly prohibited. If
you have received this e-mail in error please notify me.
