### ISSUE TITLE
Okta sub claim is missing

### ISSUE THREAD

**Issue by dxblum** [DuendeSoftware/Support#601]
**Which version of Duende IdentityServer are you using?**
V6

**Which version of .NET are you using?**
.Net 6.0

**Describe the bug**
I'm using Duende Server without ASPNet Identity
I have my own  customer UserRole and UserStore that works well with my database logins and with Google Login.  When I log in with my Otka credentials on their portal I get back the "InvalidOperationException: sub claim is missing".  I never goes back to Callback OnGet();

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

If it went back to the Callback OnGet() like google does, I can get the email and Okta ID and verify it against the database and create a new Login User 

**Log output/exception with stacktrace**

An unhandled exception has occurred while executing the request.
System.InvalidOperationException: sub claim is missing
   at Duende.IdentityServer.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal) in /_/src/IdentityServer/Hosting/IdentityServerAuthenticationService.cs:line 106
   at Duende.IdentityServer.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal) in /_/src/IdentityServer/Hosting/IdentityServerAuthenticationService.cs:line 69
   at Duende.IdentityServer.Hosting.IdentityServerAuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties) in /_/src/IdentityServer/Hosting/IdentityServerAuthenticationService.cs:line 56
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Additional context**

Add any other context about the problem here.

**Comment by josephdecock** [comment]
This sounds like you may an incorrect or missing SignInScheme option in your okta auth handler. You should set the SignInScheme to `IdentityServerConstants.ExternalCookieAuthenticationScheme`.

**Comment by dxblum** [comment]
Joseph, You are a lifesaver... I didn't have one at all and that totally fixed my issue.  Thank you so much!
