### ISSUE TITLE
Error unprotecting key with kid FEA05FCA050A2327D1EF57A16F36E261

### ISSUE THREAD

**Issue by Steveowonder** [DuendeSoftware/Support#604]
Dear Duende-Team,

I used your IdentityServer 4 with a license (for small companies < 1Mio$).
Unfortunately I just noticed my app does not work any more due to following error:

2023-04-01 11:36:13,837 ERROR Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0 [426] - MESSAGE: Error unprotecting key with kid FEA05FCA050A2327D1EF57A16F36E261.
System.Security.Cryptography.CryptographicException: The key {14a3b757-865f-4948-b947-c3dbe05a2b5d} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 75
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 438

What can I do now?
Do I need a new license key? Is it expired? 
Do I need to upgrade to your latest version?

Many thanks in advance for your support!

Best regards
Stefan

**Comment by josephdecock** [comment]
You do need to update your license annually, however the exception you're seeing is not caused by your license's expiration. Licensing problems are logged but do not otherwise change the behavior of IdentityServer. Please [contact us](https://duendesoftware.com/contact) to renew your license.

The exception here means that you have a problem with your ASP.NET data protection keys. There are several ways this can go wrong, so I have a few questions: 
- Are you configuring data protection explicitly?
- Is your IdentityServer host load balanced?
- Have you recently changed the load balancing - especially have you recently changed from a single instance to multiple instances?
- What version of .NET are you using?
- What version of IdentityServer are you using?
- Have either of those versions changed recently?
- Are you specifying a signing credential manually?

**Comment by josephdecock** [comment]
Any update here? Should we close this issue?

**Comment by Steveowonder** [comment]
Hi Joe, 

 

sorry, I’ve been on Easter holidays…

Will reply next week!


Stefan

 

M.Sc. Erneuerbare Energien | Diplom-Betriebswirt (FH) | Softwareentwickler .NET 

Lindenfeld 16 | 86647 Buttenwiesen | eMail:  ***@***.***> ***@***.***

Mobil: +49 (0)172 1 33 22 20 | Internet:  <http://www.sw-entwickler.net/> www.sw-entwickler.net 

 

Von: Joe DeCock ***@***.***> 
Gesendet: Mittwoch, 12. April 2023 00:26
An: DuendeSoftware/Support ***@***.***>
Cc: Steveowonder ***@***.***>; Author ***@***.***>
Betreff: Re: [DuendeSoftware/Support] Error unprotecting key with kid FEA05FCA050A2327D1EF57A16F36E261 (Issue #604)

 

Any update here? Should we close this issue?

**Comment by josephdecock** [comment]
Haven't heard any follow up here, so closing the issue. Feel free to reopen if necessary!
