### ISSUE TITLE
After adding AddOidcStateDataFormatterCache, getting a corrupted state throws a CryptographicException

### ISSUE THREAD

**Issue by gekiss** [DuendeSoftware/Support#620]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
net6.0

**Describe the bug**
After adding _AddOidcStateDataFormatterCache_ when a corrupted state is received _CryptographicException_ is thrown

**To Reproduce**
Send OIDC response with corrupted _state_ parameter value

**Expected behavior**
Expected authentication failure, as it was before adding _AddOidcStateDataFormatterCache_.

**Log output/exception with stacktrace**
```
System.Security.Cryptography.CryptographicException: An error occurred during a cryptographic operation.
 ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at Microsoft.Extensions.Internal.WebEncoders.Base64UrlDecode(String input, Int32 offset, Char[] buffer, Int32 bufferOffset, Int32 count)
   at Microsoft.Extensions.Internal.WebEncoders.Base64UrlDecode(String input, Int32 offset, Int32 count)
   at Microsoft.Extensions.Internal.WebEncoders.Base64UrlDecode(String input)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect(String protectedText, String purpose) in /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:line 100
   at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect(String protectedText) in /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:line 83
```

**Additional context**
Perhaps you need to catch the exception in 
https://github.com/DuendeSoftware/IdentityServer/blob/e5e46d2bbac29fcbb8d77911350e20706bed91f8/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs#L100

at is in the code
https://github.com/dotnet/aspnetcore/blob/e21ecb3dc51338f4d8288a844cb8491f550e4cd1/src/Security/Authentication/Core/src/SecureDataFormat.cs#L58-L89

Thanks for your work.

**Comment by josephdecock** [comment]
Thanks for this bug report! What happens after the cryptographic exception is thrown?

**Comment by gekiss** [comment]
In the case when _AddOidcStateDataFormatterCache_ is used the authentication and sign out process will break with exception.
The invalid state must not to stop authentication process, we can see it in the code: 

https://github.com/dotnet/aspnetcore/blob/509ba52b636ea3945bccfdcadb8abeae54b46418/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L820
https://github.com/dotnet/aspnetcore/blob/509ba52b636ea3945bccfdcadb8abeae54b46418/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L320

I think the _DistributedCacheStateDataFormatter_ should return _null_ if can't be decode state.

**Comment by brockallen** [comment]
Is there anything else needed here on this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
