### ISSUE TITLE
Issue when trying to connect to duende after docker container deployment -- System.UriFormatException: Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by mo7amedtaher** [DuendeSoftware/Support#648]
**Which version of Duende IdentityServer are you using?**
version 6.x Business License
**Which version of .NET are you using?**
6
**Describe the bug**
exception when try to connect for the client, the same scenario works in dev environemnt
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Tameeni.STS.Identity.Services.LocalizationQueryProvider.DetermineProviderCultureResult(HttpContext httpContext) in /src/Tameeni.IDP/src/Tameeni.STS.Identity/Services/LocalizationQueryProvider.cs:line 26
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
**To Reproduce**
deploy dudende Identity server on docker container and try to connect from a client
Steps to reproduce the behavior.

**Expected behavior**
successful login

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
This sounds like there is a missing configuration value in that environment that your code in LocalizationQueryProvider.cs:line 26 is trying to use.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
