### ISSUE TITLE
Unable to unprotect signing key

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#65]
**Which version of Duende IdentityServer are you using?**
6.0.4

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
I am not really sure if this is bug, but I am not able to figure out why do I have this issue. 
When I start Identity Server from Visual Studio it will create signing key in the database.
Then, I create publish profile and start Identity Server from there and I get error when Identity Server tries to unprotect the key. After that Identity Server creates new key.

I know that the DPAPI is involved in the background, but I can not figure out why I have this issue, since its the same user.

**To Reproduce**
1. Run Duende Identity Server in Visual Studio
2. Publish on file stream
3. Run Duende Identity Server from publish directory

**Expected behavior**
Identity Server should be able to unprotect the key.

**Log output/exception with stacktrace**
2022-05-20 15:57:50 [ERR] [5] [Duende.IdentityServer.Services.KeyManagement.KeyManager] Error unprotecting key with kid "7CA93DFF62A82D050BBFB9722DED5979".
System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
```
data
```

**Additional context**

**Comment by brockallen** [comment]
This is related to the data protection config across the two environments. 
https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/
