### ISSUE TITLE
Identity Server Upgradation and Database Migration Issue

### ISSUE THREAD

**Issue by arnab6399** [DuendeSoftware/Support#669]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
.Net 6.0

**Describe the bug**
Data seed for SQLite : 
After generating the migration file for update from Identity server 4 to Duende Identity Server when applying the migration It is executing the auto generated db migration file and throws error.

**To Reproduce**

1. Run the command prompt in administrator mode and execute "IdentityComponent.exe /SeedData=Yes" in the root directory path for IdentityServer 4 and .net core 3.1 .
3. Run the below two command : 
    i. dotnet ef migrations add UpdateToDuende_v6_0 -c PersistedGrantDbContext -o 
                      Data/Migrations/IdentityServer/PersistedGrantDb
   ii. dotnet ef migrations add UpdateToDuende_v6_0 -c ConfigurationDbContext -o 
                      Data/Migrations/IdentityServer/ConfigurationDb
4. Two files will be generated.
5. Run the below command two update the schema of the DB : 
    i. dotnet ef database update -c PersistedGrantDbContext
   ii. dotnet ef database update -c ConfigurationDbContext 
6. DB Schema will be updated.
7. Publish the Identity component application.
8. Run the  "IdentityComponent.exe /SeedData=Yes" command  for SQLite DB.

N.B. : When we are running the SeedData command then the below code is executing : 

public void EnsureSeedData(IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();
                serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>().Database.Migrate();
                using (var context = serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>())
                {
                    //context.Database.Migrate();
                    EnsureSeedData(context);
                }
                serviceScope.ServiceProvider.GetRequiredService<ApplicationDbContext>().Database.Migrate();

                using (var context = serviceScope.ServiceProvider.GetRequiredService<CustomConfigurationDbContext>())
                {
                    context.Database.Migrate();
                    SeedCustomConfigurationData(context);
                }
                serviceScope.ServiceProvider.GetRequiredService<DistributedCachingDBContext>().Database.Migrate();
                serviceScope.ServiceProvider.GetRequiredService<DataProtectionDbContext>().Database.Migrate();
                serviceScope.ServiceProvider.GetRequiredService<DataCleanupDBContext>().Database.Migrate();
            }
        }

private void EnsureSeedData(ConfigurationDbContext context)
        {
            _logger.LogInformation("Populating data after schema migration.");

            if (!context.IdentityResources.Any())
            {
                _logger.LogInformation("IdentityResources from IdSrvResources Class is being populated.");
                foreach (var resource in IdSrvResources.GetIdentityResources())
                {
                    context.IdentityResources.Add(resource.ToEntity());
                }
                context.SaveChanges();
            }
            else
            {
                _logger.LogInformation("IdentityResources data is already populated.");
            }

            bool apiScopeAdded = false;
            if (_identityComponentConfiguration.AllApiScopes != null)
            {
                foreach (var apiScope in _identityComponentConfiguration.AllApiScopes)
                {
                    _logger.LogInformation("ApiScopes from Settings.json is being populated.");
                    if (context.ApiScopes.FirstOrDefault(x => x.Name == apiScope.Name) == null)
                    {
                        context.ApiScopes.Add(apiScope.ToEntity());
                        apiScopeAdded = true;
                    }
                }
            }

            if ((_exportedData != null) && (_exportedData.AllApiScopes != null))
            {
                foreach (var apiScope in _exportedData.AllApiScopes)
                {
                    if (!_identityComponentConfiguration.AllApiScopes.Exists(x => x.Name == apiScope.Name))
                    {
                        _logger.LogInformation("ApiScopes from from Migrated Data is being populated.");
                        if (context.ApiScopes.FirstOrDefault(x => x.Name == apiScope.Name) == null)
                        {
                            context.ApiScopes.Add(apiScope.ToEntity());
                            apiScopeAdded = true;
                        }
                    }
                }
            }

            if (apiScopeAdded)
            {
                context.SaveChanges();
            }
            else
            {
                _logger.LogInformation("No ApiScopes data populated.");
            }

            bool apiResourceAdded = false;
            if (_identityComponentConfiguration.AllApiResources != null)
            {
                _logger.LogInformation("ApiResources from Settings.json is being populated.");
                foreach (var apiResource in _identityComponentConfiguration.AllApiResources)
                {
                    if (context.ApiResources.FirstOrDefault(x => x.Name == apiResource.Name) == null)
                    {
                        context.ApiResources.Add(apiResource.ToEntity());
                        apiResourceAdded = true;
                    }
                }
            }

            if ((_exportedData != null) && (_exportedData.AllApiResources != null))
            {
                _logger.LogInformation("ApiResources from from Migrated Data is being populated.");
                foreach (var apiRes in _exportedData.AllApiResources)
                {
                    if (!_identityComponentConfiguration.AllApiResources.Exists(x => x.Name == apiRes.Name))
                    {
                        if (context.ApiResources.FirstOrDefault(x => x.Name == apiRes.Name) == null)
                        {
                            context.ApiResources.Add(apiRes.ToEntity());
                            apiResourceAdded = true;
                        }
                    }
                }
            }
            if (apiResourceAdded)
            {
                context.SaveChanges();
            }
            else
            {
                _logger.LogInformation("No ApiResources data populated.");
            }

            bool clientAdded = false;
            if (_identityComponentConfiguration.AllClients != null)
            {
                _logger.LogInformation("Clients from Settings.json is being populated.");
                foreach (var client in _identityComponentConfiguration.AllClients)
                {
                    if (context.Clients.FirstOrDefault(x => x.ClientId == client.ClientId) == null)
                    {
                        context.Clients.Add(client.ToEntity());
                        clientAdded = true;
                    }
                }
            }

            if ((_exportedData != null) && (_exportedData.AllClients != null))
            {
                _logger.LogInformation("Clients from from Migrated Data is being populated.");
                foreach (var client in _exportedData.AllClients)
                {
                    if (!_identityComponentConfiguration.AllClients.Exists(x => x.ClientId == client.ClientId))
                    {
                        if (context.Clients.FirstOrDefault(x => x.ClientId == client.ClientId) == null)
                        {
                            context.Clients.Add(client.ToEntity());
                            clientAdded = true;
                        }
                    }
                }
            }

            if (clientAdded)
            {
                context.SaveChanges();
            }
            else
            {
                _logger.LogInformation("No new Client data populated.");
            }

            _logger.LogInformation("Completed population of database with configuration data.");
        }

**Expected behavior**

When updating through the migration file execution the DB schema is getting updated and the new db contains the new table also.
When running the SeedData command, the new db with the new schema should get generated, but it is throwing error of "Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'near "MAX": syntax error'".

**Log output/exception with stacktrace**
"Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'near "MAX": syntax error'"

Application startup exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "max": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at IdentityComponent.SeedData.EnsureSeedData(IApplicationBuilder app) in D:\CliniSysProjects\SSO\IdentityComponent\IdentityComponent\App_Data\SeedData.cs:line 39
   at IdentityComponent.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime) in D:\CliniSysProjects\SSO\IdentityComponent\IdentityComponent\Startup.cs:line 260
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "max": syntax error'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
         at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
         at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
         at IdentityComponent.SeedData.EnsureSeedData(IApplicationBuilder app) in D:\CliniSysProjects\SSO\IdentityComponent\IdentityComponent\App_Data\SeedData.cs:line 39
         at IdentityComponent.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime) in D:\CliniSysProjects\SSO\IdentityComponent\IdentityComponent\Startup.cs:line 260
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
         at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
         at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "max": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at IdentityComponent.SeedData.EnsureSeedData(IApplicationBuilder app) in D:\CliniSysProjects\SSO\IdentityComponent\IdentityComponent\App_Data\SeedData.cs:line 39
   at IdentityComponent.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime) in D:\CliniSysProjects\SSO\IdentityComponent\IdentityComponent\Startup.cs:line 260
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at IdentityComponent.Program.Main(String[] args) in D:\CliniSysProjects\SSO\IdentityComponent\IdentityComponent\Program.cs:line 34
```
data
Blank DB

**Additional context**

Also when generation for SQL Server it is working properly. After publishing the file when we run the command for data seed it is getting generated with the new schema.

**Comment by josephdecock** [comment]
Since this is working with Sql Server, this sounds like a bug in the SQLite EF provider. You probably can work around it by using the ef migrations to generate a sql script to start from and then manually updating the script to work properly with that database.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?
