### ISSUE TITLE
Migration to v6.3 error

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#691]
**Which version of Duende IdentityServer are you using?**
Community
**Which version of .NET are you using?**
7.0.105
**Describe the bug**
```
$ dotnet-ef database update -c ConfigurationDbContext
Build started...
Build succeeded.
[08:45:53 INF] Using 1000 threads
[08:45:53 INF] Using PathBase: 
{"@timestamp":"2023-05-25T08:45:53.2131440+08:00","level":"Information","messageTemplate":"Shut down complete","message":"Shut down complete"}

08:45:53 [Information] () Shut down complete
Npgsql.PostgresException (0x80004005): 42P07: relation "ApiResources" already exists
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "ApiResources" already exists
    File: heap.c
    Line: 1162
    Routine: heap_create_with_catalog
42P07: relation "ApiResources" already exists
```

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
This error means that the migration is trying to create tables that are already in the database. This indicates that your EF snapshot wasn't correct when the migration Jim was generated - the snapshot didn't know that this table existed, so it generated the entire table. But it really did exist, so trying to create it failed. 

I recommend that you back up in your upgrade process and make sure that when you are using the 6.2 package, you have a good snapshot of your database. On 6.2, you'd expect that generating migrations would result in an empty migration. Get to that state first, and then change the package version to 6.3 and generate a new migration. That migration should just add 4 new columns to the clients table.

**Comment by khteh** [comment]
I try to generate migrations for 6.2.3. Both `PersistedGrantDbContext` and `ConfigurationDbContext` are not empty at all. What should I do now?
![image](https://github.com/DuendeSoftware/Support/assets/3871483/d88820d2-682d-4590-8deb-fa729260e694)
