### ISSUE TITLE
CanUseDPoP NullReferenceException

### ISSUE THREAD

**Issue by aguacongas** [DuendeSoftware/Support#699]
**Which version of Duende IdentityServer are you using?**
6.3.1

**Which version of .NET are you using?**
7.0.5

**Describe the bug**

When trying to use to login with the DPoP WebClient sample a `NullReferenceException` is thrown. I guess because I don't have license.

**To Reproduce**

Login with the DPoP WebClient sample

**Expected behavior**

No exception.

**Log output/exception with stacktrace**

Unhandled exception: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duende.IdentityServer.Validation.LicenseValidator.CanUseDPoP() in /_/src/IdentityServer/Validation/Default/LicenseValidator.cs:line 185
   at Duende.IdentityServer.Validation.TokenRequestValidator.ValidateProofToken(TokenRequestValidationContext context) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 228
   at Duende.IdentityServer.Validation.TokenRequestValidator.ValidateRequestAsync(TokenRequestValidationContext context) in /_/src/IdentityServer/Validation/Default/TokenRequestValidator.cs:line 174
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 117
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 81
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121

```
data
```

**Additional context**

I don't have license

**Comment by brockallen** [comment]
Hmm... I'm not sure how a NRE gets thrown there when you don't have a license. Here's the code for the `CanUseDPoP` check:

https://github.com/DuendeSoftware/IdentityServer/blob/6.3.1/src/IdentityServer/Validation/Default/LicenseValidator.cs#L180

And I just tested that version without a license key and I got this written into my logs:

```
[09:21:44 Debug] Duende.IdentityServer.Validation.TokenRequestValidator
Start token request validation

[09:21:44 Information] Duende.License
A request was made using DPoP, but you do not have a license. This feature requires the Enterprise Edition tier of license.

[09:21:44 Debug] Duende.IdentityServer.Validation.DefaultDPoPProofValidator
Adding proof token with jti TYOFXBnN_Mnp_FC37nK-RDMtOTZl74BfqMNze9UhRYI to replay cache for duration 00:11:00
```

So... maybe you have some NuGet version mismatches?

**Comment by aguacongas** [comment]
I guess not, all Duende.* library have the same version in my bin dir : 

![image](https://github.com/DuendeSoftware/Support/assets/3294829/dd6b9938-2dff-45cd-9fc0-ef551d9b73cd)

**Comment by aguacongas** [comment]
I found where my issue was. It's because I didn't validate the license because I didn't use the `UseIdentityServer` extension method because I didn't want to use the `DynamicSchemeAuthenticationMiddleware` as I implemented mine.  

So can you add an option to choose if we want to use `DynamicSchemeAuthenticationMiddleware` or make internal `Validate` method public please ?

**Comment by brockallen** [comment]
> I found where my issue was. It's because I didn't validate the license because I didn't use the UseIdentityServer extension method because I didn't want to use the DynamicSchemeAuthenticationMiddleware as I implemented mine.

Can you elaborate on why you needed to do your own? Also, if you needed your own, I'd almost have expected that done as a custom middleware before the IdentityServer middleware in your pipeline (so in addition to, rather than instead of).

Thanks

**Comment by aguacongas** [comment]
Actually I implemented my Dynamic Authentication Scheme mechanism before you did then I don't want to change it because its too much work and will introduce breaking changes. So I don't need this middleware. I guess come other people don't need it as well. It should be optional in my opinion.

**Comment by brockallen** [comment]
But you need IdentityServer for all the other endpoints, yes?

**Comment by aguacongas** [comment]
Yes, except client registration

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
