### ISSUE TITLE
Unhandled exception in  TokenValidator

### ISSUE THREAD

**Issue by ademargoncalves** [DuendeSoftware/Support#7]
**Which version of Duende IdentityServer are you using?**

Duende 6.0.1

**Which version of .NET are you using?**

.NET 6.0

**Describe the bug**

In the TokenValidator class (line 316) when a client does not exist, an InvalidOperationException is being thrown. In previous versions before Duende this code was inside a try catch, but with Duende this was removed and now this exception is caught in the IdentityServerMiddleware as an unhandled exception. Additionally this exception is being logged as a fatal. Was this intentional?

**To Reproduce**

Call the userinfo endpoint with a client that does not exist.

**Expected behavior**

I expected a similar behavior as in previous versions where an unhandled exception was not being catch and a fatal error was not being logged.

**Log output/exception with stacktrace**

```
System.InvalidOperationException: Client does not exist anymore.
   at Duende.IdentityServer.Validation.TokenValidator.ValidateJwtAsync(String jwtString, IEnumerable`1 validationKeys, Boolean validateLifetime, String audience) in /_/src/IdentityServer/Validation/Default/TokenValidator.cs:line 310
   at Duende.IdentityServer.Validation.TokenValidator.ValidateAccessTokenAsync(String token, String expectedScope) in /_/src/IdentityServer/Validation/Default/TokenValidator.cs:line 147
   at Duende.IdentityServer.Validation.UserInfoRequestValidator.ValidateRequestAsync(String accessToken) in /_/src/IdentityServer/Validation/Default/UserInfoRequestValidator.cs:line 50
   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessUserInfoRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 79
   at Duende.IdentityServer.Endpoints.UserInfoEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/UserInfoEndpoint.cs:line 60
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 84
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 99
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
```

**Additional context**

https://github.com/DuendeSoftware/IdentityServer/commit/5525147b4c7c7eeda2f43fecb1b51c0a64afd481

**Comment by brockallen** [comment]
We can look into that. Thanks for the report.

**Comment by ademargoncalves** [comment]
I think so. Thanks for the quick response.

**Comment by brockallen** [comment]
Ok, we'll be merging that PR for 6.1. Thanks!
