### ISSUE TITLE
Cannot use table 'Identity.AspNetUserRoles' for entity type 'IdentityUserRole<string>' since it is being used for entity type 'AspNetUserRoles (Dictionary<string, object>)'

### ISSUE THREAD

**Issue by Karbust** [DuendeSoftware/Support#701]
**Which version of Duende IdentityServer are you using?** v6

**Which version of .NET are you using?** 7.0

**Describe the bug**

An exception is thrown when trying to query the `AspNetUsers` table.
```
System.InvalidOperationException: Cannot use table 'Identity.AspNetUserRoles' for entity type 'IdentityUserRole<string>' since it is being used for entity type 'AspNetUserRoles (Dictionary<string, object>)' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'IdentityUserRole<string>' on the primary key properties and pointing to the primary key on another entity type mapped to 'Identity.AspNetUserRoles'.
```

**To Reproduce**

I added the code I'm using on additional context.

**Expected behavior**

Being able to query the database, more specifically, the `AspNetUsers` table.

**Log output/exception with stacktrace**

```
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Cannot use table 'Identity.AspNetUserRoles' for entity type 'IdentityUserRole<string>' since it is being used for entity type 'AspNetUserRoles (Dictionary<string, object>)' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'IdentityUserRole<string>' on the primary key properties and pointing to the primary key on another entity type mapped to 'Identity.AspNetUserRoles'.
         at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IReadOnlyList`1 mappedTypes, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
         at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
         at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal.NpgsqlModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
         at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
         at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
         at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
         at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
         at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
         at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
         at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
         at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
         at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
         at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
         at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
         at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
         at Microsoft.EntityFrameworkCore.DbContext.get_Model()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
         at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
         at Application.Services.User.UserService.AuthenticateAsync(UserAuthenticateModel request) in E:\Projetos\metin2_admin_panel_backend\Application\Services\User\UserService.cs:line 49
         at Web.Backend.Controllers.AuthController.Authenticate(UserAuthenticateModel request) in E:\Projetos\metin2_admin_panel_backend\Web.Backend\Controllers\AuthController.cs:line 53
         at lambda_method5(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Additional context**

Generating the context using:
```
dotnet ef dbcontext scaffold "Host=localhost;Database=postgres;Username=postgres;Password=123;" Npgsql.EntityFrameworkCore.PostgreSQL --output-dir ..\Domain\GeneratedEntities --namespace Domain.GeneratedEntities --context GeneratedContext --context-dir ../Persistence/GeneratedContexts --project Persistence.Tooling --startup-project Persistence.Tooling --no-onconfiguring --no-pluralize --force
```

I'm also using this for certain automations: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars

AspNetUsers:
```csharp
public partial class AspNetUsers 
    : IdentityUser<string>
{
    public AspNetUsers()
    {
        Role = new HashSet<AspNetRoles>();
    }

    public DateTime CreatedOn { get; set; }
    public string CreatedBy { get; set; } = default!;
    public DateTime ModifiedOn { get; set; }
    public string ModifiedBy { get; set; } = default!;

    public virtual ICollection<AspNetRoles> Role { get; set; } = default!;
}
```

AspNetRoles:
```csharp
public partial class AspNetRoles 
    : IdentityRole<string>
{
    public AspNetRoles()
    {
        User = new HashSet<AspNetUsers>();
    }


    public virtual ICollection<AspNetUsers> User { get; set; } = default!;
}
```

AspNetUserRoles is not being generated.

Generated Context:
```csharp
public partial class GeneratedContext : ApplicationIdentityDbContext
{
    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; } = default!;
    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; } = default!;
    public virtual DbSet<IdentityProviders> IdentityProviders { get; set; } = default!;
    public virtual DbSet<Keys> Keys { get; set; } = default!;
    public virtual DbSet<ServerSideSessions> ServerSideSessions { get; set; } = default!;

    public GeneratedContext(
        DbContextOptions<ApplicationIdentityDbContext> options,
        IOptions<OperationalStoreOptions> operationalStoreOptions,
        IOptions<ConfigurationStoreOptions> configurationStoreOptions,
        ICurrentSessionService currentSessionService,
        IDateTime dateTime)
        : base(options, operationalStoreOptions, configurationStoreOptions, currentSessionService, dateTime)
    {
    }
```

Generated Context for `AspNetUsers` and `AspNetRoles`:
```csharp
            builder.Entity<AspNetRoles>(entity =>
            {
                entity.ToTable("AspNetRoles", "Identity");

                entity.HasAnnotation("Scaffolding:DbSetName", "AspNetRoles");

                entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnOrder(0);

                entity.Property(e => e.ConcurrencyStamp).HasColumnOrder(3);

                entity.Property(e => e.Name)
                    .HasMaxLength(256)
                    .HasColumnOrder(1);

                entity.Property(e => e.NormalizedName)
                    .HasMaxLength(256)
                    .HasColumnOrder(2);
            });

            builder.Entity<AspNetUsers>(entity =>
            {
                entity.ToTable("AspNetUsers", "Identity");

                entity.HasAnnotation("Scaffolding:DbSetName", "AspNetUsers");

                entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

                entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnOrder(0);

                entity.Property(e => e.AccessFailedCount)
                    .HasDefaultValue(0)
                    .HasColumnOrder(14);

                entity.Property(e => e.ConcurrencyStamp).HasColumnOrder(8);

                entity.Property(e => e.CreatedBy).HasColumnOrder(16);

                entity.Property(e => e.CreatedOn)
                    .HasPrecision(6)
                    .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                    .HasColumnOrder(15);

                entity.Property(e => e.Email)
                    .HasMaxLength(256)
                    .HasColumnOrder(3);

                entity.Property(e => e.EmailConfirmed)
                    .HasDefaultValue(false)
                    .HasColumnOrder(5);

                entity.Property(e => e.LockoutEnabled)
                    .HasDefaultValue(false)
                    .HasColumnOrder(13);

                entity.Property(e => e.LockoutEnd).HasColumnOrder(12);

                entity.Property(e => e.ModifiedBy).HasColumnOrder(18);

                entity.Property(e => e.ModifiedOn)
                    .HasPrecision(6)
                    .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                    .HasColumnOrder(17);

                entity.Property(e => e.NormalizedEmail)
                    .HasMaxLength(256)
                    .HasColumnOrder(4);

                entity.Property(e => e.NormalizedUserName)
                    .HasMaxLength(256)
                    .HasColumnOrder(2);

                entity.Property(e => e.PasswordHash).HasColumnOrder(6);

                entity.Property(e => e.PhoneNumber).HasColumnOrder(9);

                entity.Property(e => e.PhoneNumberConfirmed)
                    .HasDefaultValue(false)
                    .HasColumnOrder(10);

                entity.Property(e => e.SecurityStamp).HasColumnOrder(7);

                entity.Property(e => e.TwoFactorEnabled)
                    .HasDefaultValue(false)
                    .HasColumnOrder(11);

                entity.Property(e => e.UserName)
                    .HasMaxLength(256)
                    .HasColumnOrder(1);

                entity.HasMany(d => d.Role)
                    .WithMany(p => p.User)
                    .UsingEntity<Dictionary<string, object>>(
                        "AspNetUserRoles",
                        l => l.HasOne<AspNetRoles>().WithMany().HasForeignKey("RoleId"),
                        r => r.HasOne<AspNetUsers>().WithMany().HasForeignKey("UserId"),
                        j =>
                        {
                            j.HasKey("UserId", "RoleId");

                            j.ToTable("AspNetUserRoles", "Identity").HasAnnotation("Scaffolding:DbSetName", "AspNetUserRoles");

                            j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                        });
            });
```

ApplicationDbContext:
```csharp
public class ApplicationDbContext : GeneratedContext, IApplicationDbContext
{
    private IDbContextTransaction _dbContextTransaction;
    private readonly ILogger<ApplicationDbContext> _logger;
    private readonly ICurrentSessionService _currentSessionService;
    private readonly IDateTime _dateTime;
    private readonly IMapper _mapper;
    
    public ApplicationDbContext(
        DbContextOptions<ApplicationIdentityDbContext> options,
        IOptions<OperationalStoreOptions> operationalStoreOptions,
        IOptions<ConfigurationStoreOptions> configurationStoreOptions,
        ILogger<ApplicationDbContext> logger,
        ICurrentSessionService currentSessionService,
        IDateTime dateTime,
        IMapper mapper)
        : base(options, operationalStoreOptions, configurationStoreOptions, currentSessionService, dateTime)
    {
        _logger = logger;
        _currentSessionService = currentSessionService;
        _dateTime = dateTime;
        _mapper = mapper;

        //Database.SetCommandTimeout(TimeSpan.FromMinutes(1));
    }
}
```

With this line uncommented `Database.SetCommandTimeout(TimeSpan.FromMinutes(1));` the error is thrown there when making the request.

ApplicationIdentityDbContext:
```csharp
public class ApplicationIdentityDbContext : IdentityDbContext<AspNetUsers, AspNetRoles, string>, IApplicationIdentityDbContext
{
    private readonly IOptions<OperationalStoreOptions> _operationalStoreOptions;
    private readonly IOptions<ConfigurationStoreOptions> _configurationStoreOptions;
    private readonly ICurrentSessionService _currentSessionService;
    private readonly IDateTime _dateTime;

    public ApplicationIdentityDbContext(
        DbContextOptions<ApplicationIdentityDbContext> options,
        IOptions<OperationalStoreOptions> operationalStoreOptions,
        IOptions<ConfigurationStoreOptions> configurationStoreOptions,
        ICurrentSessionService currentSessionService,
        IDateTime dateTime) : base(options)
    {
        _operationalStoreOptions = operationalStoreOptions;
        _configurationStoreOptions = configurationStoreOptions;
        _currentSessionService = currentSessionService;
        _dateTime = dateTime;
    }

    public DbSet<PersistedGrant> PersistedGrants { get; set; }
    public DbSet<DeviceFlowCodes> DeviceFlowCodes { get; set; }
    public DbSet<Key> Keys { get; set; }
    public DbSet<ServerSideSession> ServerSideSessions { get; set; }
    public DbSet<Client> Clients { get; set; }
    public DbSet<ClientCorsOrigin> ClientCorsOrigins { get; set; }
    public DbSet<IdentityResource> IdentityResources { get; set; }
    public DbSet<ApiResource> ApiResources { get; set; }
    public DbSet<ApiScope> ApiScopes { get; set; }
    public DbSet<IdentityProvider> IdentityProviders { get; set; }

    public virtual Task<int> SaveChangesAsync()
    {
        foreach (var entry in ChangeTracker.Entries<AspNetUsers>())
        {
            switch (entry.State)
            {
                case EntityState.Added:
                    entry.Entity.CreatedBy = _currentSessionService.UserId;
                    entry.Entity.CreatedOn = _dateTime.Now;
                    entry.Entity.ModifiedBy = _currentSessionService.UserId;
                    entry.Entity.ModifiedOn = _dateTime.Now;
                    break;

                case EntityState.Modified:
                    entry.Entity.ModifiedBy = _currentSessionService.UserId;
                    entry.Entity.ModifiedOn = _dateTime.Now;
                    break;
            }
        }

        return base.SaveChangesAsync();
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        
        _operationalStoreOptions.Value.DefaultSchema = "Identity";
        builder.ConfigurePersistedGrantContext(_operationalStoreOptions.Value);

        _configurationStoreOptions.Value.DefaultSchema = "Identity";
        builder.ConfigureClientContext(_configurationStoreOptions.Value);
        builder.ConfigureResourcesContext(_configurationStoreOptions.Value);
    }
}
```

![image](https://github.com/DuendeSoftware/Support/assets/20361229/55b77458-9948-4ecd-8d26-a5e02f3ec2ea)

**Comment by josephdecock** [comment]
Hi @Karbust  - you've provided a lot of detail in this issue, but this error looks to me like it is entirely coming from ASP.NET identity, and I suspect you would have it even if you weren't using IdentityServer. A couple of suggestions for you:

1. I would try to simplify what you have to make sure that the DbContext for just ASP.NET Identity is working on its own.
2. You could try [using our templates ](https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/) to start a new project and compare with what you have to get some more ideas.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by Karbust** [comment]
I ended up being able to fix it, wasn't even using Duende. First time using, got a bit lost.

**Comment by khanhLovehang** [comment]
@Karbust how do you fix it? i have the same problem like you
