### ISSUE TITLE
Dynamic Providers for Facebook

### ISSUE THREAD

**Issue by vivaladan** [DuendeSoftware/Support#704]
**Which version of Duende IdentityServer are you using?**
6.3.1

**Which version of .NET are you using?**
7.0.101

**Describe the bug**
Looking to switch to dynamic providers feature instead of static providers, initially with Facebook. Used the standard ASP.NET Core AddFacebook() up to this point. Trying to coerce OidcProvider/OpenIdConnectOptions into working for Facebook as a starting point. 
Will later want to switch to dynamic providers for various provider types (Azure B2C/Azure AD/Apple/Google/Microsoft/Facebook) which are configured across many tenants/brands.

**To Reproduce**

```
    public static IEnumerable<OidcProvider> OidcProviders =>
        new OidcProvider[]
        {
            new OidcProvider
            {
                Scheme = "facebook",
                DisplayName = "Facebook",
                Enabled = true,
                Type = "oidc",
                Authority = "https://www.facebook.com",
                ResponseType = "code",
                ClientId = "***",
                ClientSecret = "***",
                Scope = "email",
                GetClaimsFromUserInfoEndpoint = false,
                UsePkce = false,
            }
        };
```

**Log output/exception with stacktrace**

```
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```

**Additional context**

Looks like there is no token url provided by the Facebook metadata
https://www.facebook.com/.well-known/openid-configuration

Facebook docs say code exchange should use https://graph.facebook.com/v17.0/oauth/access_token 
So I've tried to forcibly set it.

```
public class CustomConfig : IConfigureNamedOptions<OpenIdConnectOptions>
{
    public void Configure(OpenIdConnectOptions options)
    {
        
    }

    public void Configure(string name, OpenIdConnectOptions options)
    {
        if (name == "facebook")
        {
            options.Configuration ??= new OpenIdConnectConfiguration();
            if (options.Configuration is not null)
                options.Configuration.TokenEndpoint = "https://graph.facebook.com/v17.0/oauth/access_token";

            // var existingHandler = options.Events.OnAuthorizationCodeReceived;
            // options.Events.OnAuthorizationCodeReceived += async context =>
            // {
            //     context.ProtocolMessage.TokenEndpoint = "https://graph.facebook.com/v17.0/oauth/access_token";
            //     await existingHandler(context);
            // };
        }
    }
}
```

But this creates an error even before the redirect. options.Configuration is always null, and by setting a new instance it apparently doesn't apply the rest of the metadata info.

The commented out code to try and set it before code exchange doesn't seem to do anything.

```
System.InvalidOperationException: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 120
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 50
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
