### ISSUE TITLE
IdentityServer v6.1 Trace level log issue

### ISSUE THREAD

**Issue by josepulidocastillo** [DuendeSoftware/Support#76]
**Which version of Duende IdentityServer are you using?**
6.1.0
**Which version of .NET are you using?**
6.0.300
**Describe the bug**
When the application is configured with loglevel Default : "Trace" generates an exception. Any other loglevel works as expected.

Default : "Trace" generates an exception

**To Reproduce**

Steps to reproduce the behavior.
Setup Default : "Trace" in your appsettings.json

**Expected behavior**
No exceptions.

**Log output/exception with stacktrace**
 System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Extensions.Logging.LogValuesFormatter.Format(Object[] values)
   at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(FormattedLogValues state, Exception error)
   at Microsoft.Extensions.Logging.Console.SimpleConsoleFormatter.Write[TState](LogEntry`1& logEntry, IExternalScopeProvider scopeProvider, TextWriter textWriter)
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId Eventis, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogTrace(ILogger logger, String message, Object[] args)
   at Duende.IdentityServer.ILoggerDevExtensions.LogTrace[T0](ILogger logger, String message, T0 arg0) in /_/src/IdentityServer/Logging/ILoggerExtensions.cs:line 23
   at Duende.IdentityServer.Validation.LicenseValidator.ValidateLicense() in /_/src/IdentityServer/Validation/Default/LicenseValidator.cs:line 75
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.Validate(IApplicationBuilder app) in /_/src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs:line 74
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app, IdentityServerMiddlewareOptions options) in /_/src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs:line 35
   at ArchestrA.IdentityManager.Host.WebHostBuilderExtensions.<>c__DisplayClass5_0.<AddIdentityManager>b__1(WebHostBuilderContext context, IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass18_2.<Configure>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Extensions.Logging.LogValuesFormatter.Format(Object[] values)
   at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(FormattedLogValues state, Exception error)
   at Myapplication.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
```
data
```

**Additional context**

**Comment by leastprivilege** [comment]
Do you have a license key? If yes - which Edition?

**Comment by josepulidocastillo** [comment]
Hi Dominick,

Our license is the ISV license
Do you need our key license? it is okay to paste on the ticket or to your email?

cheers

**Comment by leastprivilege** [comment]
Hi, 

could you please send that key to priority@duendesoftware.com - do not post it here ;)

**Comment by leastprivilege** [comment]
Hi, 

we can confirm the problem.

This issue only occurs with Microsoft's logger - we use Serilog where this is not an issue.

We will discuss internally the best way to fix that and publish a patch. Does this block you right now?

**Comment by josepulidocastillo** [comment]
Hi,

At the moment we downgrade to version 6.0.4 but Once we have the patch please let us know to do the upgrade.

Cheers

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by leastprivilege** [comment]
tracked here: 

https://github.com/DuendeSoftware/IdentityServer/pull/913

will go into the next patch release.

**Comment by leastprivilege** [comment]
Hey,

could you try the preview to see if it works as expected?

v6.1.1-preview.1

See here to setup the dev feed:
https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds

**Comment by josepulidocastillo** [comment]
Thank you. I will let you know the results once the test is done.

**Comment by josepulidocastillo** [comment]
Hi Dominick, 
I did try to get the preview version but only shows 6.2.0-alpha.0.10 those changes are in this release?
or how do I get the v6.1.1-preview.1 version

**Comment by leastprivilege** [comment]
I pushed the patch to regular Nuget - v6.1.1
