### ISSUE TITLE
Test Collection Cleanup Failure

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#789]
**Which version of Duende IdentityServer are you using?**
Community
**Which version of .NET are you using?**
7.0.304
**Describe the bug**
```
[Collection("Tests Collection")]
public class AuthorizeEndpointIntegrationTests
{
    private readonly HttpClient _client;
    public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory) => _client = factory.CreateClient();
    [Fact]
    public async Task ValidParametersShouldPassTest()
    {
        RequestUrl ru = new RequestUrl("https://localhost:5001/connect/authorize");
        string url = ru.CreateAuthorizeUrl(
            clientId: "sellerportal",
            responseType: "code",
            redirectUri: "https://app.com/callback",
            scope: IdentityServerConstants.StandardScopes.Profile);
        HttpResponseMessage response = await _client.GetAsync(url);
        response.EnsureSuccessStatusCode();
    }
}
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup>, IDisposable where TStartup : class
{
    public void Dispose()
    {
        using (var scope = Services.CreateScope())
        {
            var scopedServices = scope.ServiceProvider;
            var myDb = scopedServices.GetRequiredService<MyDbContext>();
            SeedData.CleanUpTestData(myDb);
        }
        base.Dispose(); // XXX Throws
        GC.SuppressFinalize(this);
    }
}
```
Sometime it passes, sometime it fails.
```
      Message: 
        [Test Collection Cleanup Failure (Tests Collection)]: System.AggregateException : One or more hosted services failed to stop. (Object reference not set to an instance of an object.) (Not started. Call Start first.)
        ---- System.NullReferenceException : Object reference not set to an instance of an object.
        ---- System.InvalidOperationException : Not started. Call Start first.

      Stack Trace: 
        Host.StopAsync(CancellationToken cancellationToken)
        WebApplicationFactory`1.DisposeAsync()
        WebApplicationFactory`1.Dispose(Boolean disposing)
        WebApplicationFactory`1.Dispose()
        CustomWebApplicationFactory`1.Dispose() line 77
        ----- Inner Stack Trace #1 (System.NullReferenceException) -----
        ServerSideSessionCleanupHost.StopAsync(CancellationToken cancellationToken) line 70
        Host.StopAsync(CancellationToken cancellationToken)
        ----- Inner Stack Trace #2 (System.InvalidOperationException) -----
        TokenCleanupHost.StopAsync(CancellationToken cancellationToken) line 67
        Host.StopAsync(CancellationToken cancellationToken)
```
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
Can you please describe, in words, what you are testing, what's happening, and what you expect? Code all by itself does not include any context or your expectations. Thank you.

**Comment by khteh** [comment]
Just trying to do an E2E integration tests to see if the OAuth endpoints are reachable. The problem is NOT with the test but with the test setup which throws exception sometimes and I wonder if it is due to your IdentityServer not properly setup.

https://github.com/dotnet/aspnetcore/issues/49615

**Comment by khteh** [comment]
> It looks like your test code is creating a `TokenCleanupHost`
How do you know that? I don't find this symbol reference in my code at all.

> disable the configuration option ServerSideSessions.RemoveExpiredSessions
How to do that?

**Comment by josephdecock** [comment]
You can see that the cleanup host is throwing the error from the call stack. Your code indirectly creates the cleanup host by starting up identity server. When you start IdentityServer, you can pass a lambda expression in that configured its options:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddIdentityServer(options =>
    {
        options.ServerSideSessions.RemoveExpiredSessions = false;
    });
```

**Comment by khteh** [comment]
I still see this error intermittently sometimes:
```
13:53:09 [Debug] () Hosting shutdown exception
System.AggregateException: One or more hosted services failed to stop. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.DependencyInjection.TokenCleanupHost.StopAsync(CancellationToken cancellationToken) in /_/src/EntityFramework/TokenCleanupHost.cs:line 71
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
[xUnit.net 00:00:17.07]     [Test Collection Cleanup Failure (Tests Collection)] System.AggregateException
  Failed KyberlifeIAM.IntegrationTests.AuthorizeEndpointIntegrationTests.ValidParametersShouldPassTest [1 ms]
  Error Message:
   [Test Collection Cleanup Failure (Tests Collection)]: System.AggregateException : One or more hosted services failed to stop. (Object reference not set to an instance of an object.)
---- System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
   at KyberlifeIAM.IntegrationTests.CustomWebApplicationFactory`1.Dispose() in /root/workspace/test/KyberlifeIAM.IntegrationTests/CustomWebApplicationFactory.cs:line 77
----- Inner Stack Trace -----
   at Microsoft.Extensions.DependencyInjection.TokenCleanupHost.StopAsync(CancellationToken cancellationToken) in /_/src/EntityFramework/TokenCleanupHost.cs:line 71
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
  Failed KyberlifeIAM.IntegrationTests.EmailConfirmationCodeTests.EmailConfirmationTokenShoudMatchTest [1 ms]
  Error Message:
   [Test Collection Cleanup Failure (Tests Collection)]: System.AggregateException : One or more hosted services failed to stop. (Object reference not set to an instance of an object.)
---- System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
   at KyberlifeIAM.IntegrationTests.CustomWebApplicationFactory`1.Dispose() in /root/workspace/test/KyberlifeIAM.IntegrationTests/CustomWebApplicationFactory.cs:line 77
----- Inner Stack Trace -----
   at Microsoft.Extensions.DependencyInjection.TokenCleanupHost.StopAsync(CancellationToken cancellationToken) in /_/src/EntityFramework/TokenCleanupHost.cs:line 71
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
  Failed KyberlifeIAM.IntegrationTests.EmailConfirmationCodeTests.EmailConfirmationTokenShoudNOTMatchTest [1 ms]
  Error Message:
   [Test Collection Cleanup Failure (Tests Collection)]: System.AggregateException : One or more hosted services failed to stop. (Object reference not set to an instance of an object.)
---- System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
   at KyberlifeIAM.IntegrationTests.CustomWebApplicationFactory`1.Dispose() in /root/workspace/test/KyberlifeIAM.IntegrationTests/CustomWebApplicationFactory.cs:line 77
----- Inner Stack Trace -----
   at Microsoft.Extensions.DependencyInjection.TokenCleanupHost.StopAsync(CancellationToken cancellationToken) in /_/src/EntityFramework/TokenCleanupHost.cs:line 71
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
```

**Comment by josephdecock** [comment]
It still looks like your test is creating but not starting the cleanup job. Can you provide more context about what you've tried?

**Comment by khteh** [comment]
```
service.AddIdentityServer(options => options.ServerSideSessions.RemoveExpiredSessions = env.IsProduction());
```

**Comment by josephdecock** [comment]
Ahh, this looks like the other cleanup job is failing now. I think you also need to disable it:

```
service.AddIdentityServer(options => options.ServerSideSessions.RemoveExpiredSessions = env.IsProduction())
  .AddOperationalStore(options => options.EnableTokenCleanup = false);
```

**Comment by khteh** [comment]
I will observe if this happens again.
