### ISSUE TITLE
Regular DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by sipsorcery** [DuendeSoftware/Support#865]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
7

**Describe the bug**

An `Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException` exception is regularly appearing in our logs. It's not doing any harm but it does mean we're constantly checking it.

**To Reproduce**

No special steps. Just leave our identity server running.

**Expected behavior**

No exception

**Log output/exception with stacktrace**

```
 An exception occurred in the database while saving changes for context type 'Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext'. Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions. at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Update.Reade…
```

**Additional context**

Our identity server is running in a kubernetes cluser with multiple instances.

**Comment by josephdecock** [comment]
Thanks for the bug report @sipsorcery! Can you provide a stack trace or other contextual information about where the exception is coming from? Thanks.

**Comment by sipsorcery** [comment]
````
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Duende.IdentityServer.EntityFramework.Extensions.DbContextExtensions.SaveChangesWithConcurrencyCheckAsync[T](IPersistedGrantDbContext context, ILogger logger, CancellationToken cancellationToken) in /_/src/EntityFramework.Storage/Extensions/DbContextExtensions.cs:line 33
````

**Comment by josephdecock** [comment]
Hmm, I was hoping to see more in the stack trace after Duende.IdentityServer.EntityFramework.Extensions.DbContextExtensions.SaveChangesWithConcurrencyCheckAsync to try to narrow down which part of IdentityServer this is coming from. 

There's two places that we use that - ServerSideSessions and the Token Cleanup Job. Are you using either of those features? If so, which one(s)?

**Comment by sipsorcery** [comment]
This info message appears in the log just prior:

`Duende.IdentityServer.EntityFramework.TokenCleanupService`

That seems to narrow it down and I don't believe we're using server side sesssions either.

**Comment by josephdecock** [comment]
Okay, perfect thanks. We have seen a few reports of the token cleanup service having concurrency issues, and we have an [issue on our backlog](https://github.com/DuendeSoftware/IdentityServer/issues/1351) to make our EF stores use some relatively new EF features that should help alleviate that. We hope to include that in our next big release near the end of the year.

**Comment by sipsorcery** [comment]
Ok, thx for the update.
