### ISSUE TITLE
Correlation Failed on Customer Environment but not in our own Development

### ISSUE THREAD

**Issue by andrewna3** [DuendeSoftware/Support#872]
**Which version of Duende IdentityServer are you using?**
v6.0.0

**Which version of .NET are you using?**
.NET 6.0.9

**Describe the bug**
Correlation failed when redirecting to ClientApp/signin-oidc

**To Reproduce**

1. Open Client WebApplication in browser. It will redirect to IdentityServer Login
2. Enter correct username and password in the IdentityServer login page
3. Click Login
4. It redirects to ClientApp/signin-oidc however, the page shows HTTP 500. Upon checking the logs it shows Correlations Failed:

**Expected behavior**
1. Open Client WebApplication in browser. It will redirect to IdentityServer Login
2. Enter correct username and password in the IdentityServer login page
3. Click Login
4. It redirects to ClientApp/signin-oidc and then redirects to ClientApp/ home page

**Log output/exception with stacktrace**

[2023-Aug-23 13:55:15.148][Error][Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware]An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Yokogawa.IA.RPO.RpoOm.Web.RpoOmWebApp.Util.Middleware.OmUrlCleaner.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[2023-Aug-23 13:55:15.151][Error][Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer]Connection ID "17437937763084140586", Request ID "8000002b-0001-f200-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
 ---> System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Yokogawa.IA.RPO.RpoOm.Web.RpoOmWebApp.Util.Middleware.OmUrlCleaner.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
data
```

**Additional context**

It is reproducible every time and occurring on customer environment. In our own environment with clean windows server 2019 this does not happen. Somehow when it Identity Server posts to signin-oidc the Correlation cookie is not being set. Occurs on all browsers Edge, Chrome, Secure and Samesite flags are set.

Here is how it works on our environment:
![workingFlow](https://github.com/DuendeSoftware/Support/assets/4578110/4e0b2d88-aa8f-449e-890f-4ee47faba52d)

**Comment by AndersAbel** [comment]
When correlation fails, it's typically caused by problems with the state cookie maintained in the client across the redirect to IdentityServer. In your screen dump from the call to `RpoOmWebApp/signin-oidc` you can see that the cookie is cleared on a successful login. Is it possible to validate the cookies in the browser for the environment where it fails? Please note that the cookies are tied to the `RpoOmWebApp/signin-oidc` path. To make the appear in the browser dev tools you need to open `RpoOmWebApp/signin-oidc` in the browser. It will give you an error message, but staying on that page will allow you to inspect all the cookies configured for that path.

**Comment by andrewna3** [comment]
Thank you, Anders for your comment. It turns out that I could reproduce this error by:
1. Setting the server date to future time e.g 1 hour faster. 
2. Logging in from browser 
3. Setting the server date back to correct time
4. Logging in from browser again

The cause of this is IIS response header date is stuck in the future causing the correlation cookie to be already expired as the response date is in the future. Because of this the signin-oidc cannot retrieve the correlation cookie from the browser and it says correlation failed.

Resetting IIS does not resolve the issue only restarting the server will cause IIS to return the correct Date in the HTTP Response header.

**Comment by AndersAbel** [comment]
If you change the server date a full hour, all sorts of things do break.

To be able to troubleshoot the problem for normal users we need to get information on a reproduced event under normal circumstances, i.e. without changing the server date.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
