### ISSUE TITLE
Task out exception when calls /connect/endsession

### ISSUE THREAD

**Issue by sakthi-alleva** [DuendeSoftware/Support#883]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
6.0
**Describe the bug**

More frequently getting

GET /connect/endsession

System.Threading.Tasks.TaskCanceledException

When Logout from application, it calls  /connect/endsession which is failing with "System.Threading.Tasks.TaskCanceledException" exception.  This is happening more frequent.

**To Reproduce**

Logout from the app

**Expected behavior**

An endsession should get executed without any errors.

An exception occurred while iterating over the results of a query for context type 'Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

**Comment by AndersAbel** [comment]
Where is the request to /connect/endsession comingfrom? From the browser? From a server using back channel logout? Is the request cancelled before IdentityServer has a chance to run it to completion?

**Comment by AndersAbel** [comment]
Closing due to inactivity, please reopen if needed.
