### ISSUE TITLE
Invalid_grant

### ISSUE THREAD

**Issue by MertGuney** [DuendeSoftware/Support#944]
**Which version of Duende IdentityServer are you using?**
6.3.5

**Which version of .NET are you using?**
.Net7

When I send a refresh token request a few hours after the access token expires, I get an invalid_grant error

1. Send token request using password grant type
2. Get access and refresh token
3. Get a access token with the refresh token when you return to the app after a certain period of time

**Log output/exception with stacktrace**

```
2023-10-12 08:06:26.5839|4|DEBUG|Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory|Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC. |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Microsoft.Extensions.Logging.LoggingExtensions.OpeningCNGAlgorithmFromProviderWithChainingModeCBC
2023-10-12 08:06:26.5839|3|DEBUG|Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory|Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC. |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Microsoft.Extensions.Logging.LoggingExtensions.OpeningCNGAlgorithmFromProviderWithHMAC
2023-10-12 08:06:26.5839|2|DEBUG|Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider|Using key {6915187b-f4db-416a-8782-e5a006c73b2b} as the default key. |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCoreStep2
2023-10-12 08:06:26.5839|6|TRACE|Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector|Key {3d38f391-74a8-42ae-a45f-a0280770e382} was not found in the key ring. Unprotect operation cannot proceed. |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Microsoft.Extensions.Logging.LoggingExtensions.KeyWasNotFoundInTheKeyRingUnprotectOperationCannotProceed
2023-10-12 08:06:26.5839|0|ERROR|Duende.IdentityServer.Stores.DefaultRefreshTokenStore|Failed to deserialize JSON from grant store. System.Security.Cryptography.CryptographicException: The key {3d38f391-74a8-42ae-a45f-a0280770e382} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize[T](String json) in /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:line 102
   at Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemByHashedKeyAsync(String hashedKey) in /_/src/IdentityServer/Stores/Default/DefaultGrantStore.cs:line 137|url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemByHashedKeyAsync
2023-10-12 08:06:26.5839|0|DEBUG|Duende.IdentityServer.Stores.DefaultRefreshTokenStore|refresh_token grant with value: D1A515C51DABB5401A1839624B3BEED7B0E21001C0DE8AD7DA3420DBC1105AC2-1 not found in store. |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.ILoggerDevExtensions.LogDebug
2023-10-12 08:06:26.5839|0|WARN|Duende.IdentityServer.Services.DefaultRefreshTokenService|Invalid refresh token |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Services.DefaultRefreshTokenService.ValidateRefreshTokenAsync
2023-10-12 08:06:26.5839|0|WARN|Duende.IdentityServer.Validation.TokenRequestValidator|Refresh token validation failed. aborting, {"ClientId":"IzmirimCardMobileUserClient", "ClientName":"Izmirimkart mobile kullanıcıları", "GrantType":"refresh_token", "AuthorizationCode":"********", "RefreshToken":"********", "Raw":{"client_id":"IzmirimCardMobileUserClient","client_secret":"***REDACTED***","grant_type":"refresh_token","refresh_token":"***REDACTED***"}} |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Validation.TokenRequestValidator.LogWithRequestDetails
2023-10-12 08:07:30.6337|0|ERROR|Duende.IdentityServer.Services.KeyManagement.KeyManager|Error unprotecting the IdentityServer signing key with kid 32888F5F4FB0EC93CA8DF102796B0030. This is likely due to the ASP.NET Core data protection key that was used to protect it is not available. This could occur because data protection has not been configured properly for your load balanced environment, or the IdentityServer signing key store was populated with keys from a different environment with different ASP.NET Core data protection keys. Once you have corrected the problem and if you keep getting this error then it is safe to delete the specific IdentityServer signing key with that kid. System.Security.Cryptography.CryptographicException: The key {e439e803-da86-4f0b-a2bf-0cd21d57f837} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 436|url: https://izk0001.izmirimkart.com.tr/api/v1/Auth/Register|action: Register|Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysFromStoreAsync2023-10-12 08:08:13.2505|0|INFO|Duende.IdentityServer.Validation.TokenRequestValidator|User authentication failed:  "phone_not_verified", details: {"ClientId":"IzmirimCardWebUserClient", "ClientName":"Izmirimkart Web Users", "GrantType":"password", "Scopes":"card_application_fullpermission card_fullpermission email IdentityServerApi instruction_fullpermission offline_access openid profile roles topup_fullpermission web_gateway_fullpermission", "AuthorizationCode":"********", "RefreshToken":"********", "UserName":"905354511357", "Raw":{"client_id":"IzmirimCardWebUserClient","client_secret":"***REDACTED***","grant_type":"password","username":"905354511357","password":"***REDACTED***"}} |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Validation.TokenRequestValidator.LogWithRequestDetails
2023-10-12 08:08:13.2505|0|INFO|Duende.IdentityServer.Events.DefaultEventService|{"Username":"905354511357", "Endpoint":"Token", "ClientId":"IzmirimCardWebUserClient", "Category":"Authentication", "Name":"User Login Failure", "EventType":"Failure", "Id":1001, "Message":"phone_not_verified", "ActivityId":"4000009b-0006-fd00-b63f-84710c7967bb", "TimeStamp":"2023-10-12T05:08:13.2531573Z", "ProcessId":5296, "LocalIpAddress":"10.45.10.23:443", "RemoteIpAddress":"31.142.85.175"} |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Services.DefaultEventSink.PersistAsync
2023-10-12 08:08:13.2505|0|INFO|Duende.IdentityServer.Events.DefaultEventService|{"ClientId":"IzmirimCardWebUserClient", "ClientName":"Izmirimkart Web Users", "Endpoint":"Token", "Scopes":"card_application_fullpermission card_fullpermission email IdentityServerApi instruction_fullpermission offline_access openid profile roles topup_fullpermission web_gateway_fullpermission", "GrantType":"password", "Error":"invalid_grant", "ErrorDescription":"phone_not_verified", "Category":"Token", "Name":"Token Issued Failure", "EventType":"Failure", "Id":2001, "ActivityId":"4000009b-0006-fd00-b63f-84710c7967bb", "TimeStamp":"2023-10-12T05:08:13.2576115Z", "ProcessId":5296, "LocalIpAddress":"10.45.10.23:443", "RemoteIpAddress":"31.142.85.175"} |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Services.DefaultEventSink.PersistAsync
2023-10-12 08:08:13.2505|0|TRACE|Duende.IdentityServer.Hosting.IdentityServerMiddleware|Invoking result: Duende.IdentityServer.Endpoints.Results.TokenErrorResult |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke
2023-10-12 08:06:26.5839|0|WARN|Duende.IdentityServer.Services.DefaultRefreshTokenService|Invalid refresh token |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Services.DefaultRefreshTokenService.ValidateRefreshTokenAsync
2023-10-12 08:06:26.5839|0|WARN|Duende.IdentityServer.Validation.TokenRequestValidator|Refresh token validation failed. aborting, {"ClientId":"IzmirimCardMobileUserClient", "ClientName":"Izmirimkart mobile kullanıcıları", "GrantType":"refresh_token", "AuthorizationCode":"********", "RefreshToken":"********", "Raw":{"client_id":"IzmirimCardMobileUserClient","client_secret":"***REDACTED***","grant_type":"refresh_token","refresh_token":"***REDACTED***"}} |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Validation.TokenRequestValidator.LogWithRequestDetails
2023-10-12 08:06:26.5839|0|INFO|Duende.IdentityServer.Events.DefaultEventService|{"ClientId":"IzmirimCardMobileUserClient", "ClientName":"Izmirimkart mobile kullanıcıları", "Endpoint":"Token", "GrantType":"refresh_token", "Error":"invalid_grant", "Category":"Token", "Name":"Token Issued Failure", "EventType":"Failure", "Id":2001, "ActivityId":"400000fd-0002-f600-b63f-84710c7967bb", "TimeStamp":"2023-10-12T05:06:26.5947818Z", "ProcessId":5296, "LocalIpAddress":"10.45.10.23:443", "RemoteIpAddress":"176.219.175.177"} |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.Services.DefaultEventSink.PersistAsync
2023-10-12 08:06:26.5994|0|TRACE|Duende.IdentityServer.Hosting.IdentityServerMiddleware|Invoking result: Duende.IdentityServer.Endpoints.Results.TokenErrorResult |url: https://izk0001.izmirimkart.com.tr/connect/token|action: |Duende.IdentityServer.ILoggerDevExtensions.LogTrace
```

![Screenshot 2023-10-12 094956](https://github.com/DuendeSoftware/Support/assets/52934069/3933dd3c-7979-4f67-9484-c7ac52e9853a)
![Screenshot 2023-10-12 095201](https://github.com/DuendeSoftware/Support/assets/52934069/9aa2816f-9caa-402b-9bb4-797dd40e47ac)

**Comment by AndersAbel** [comment]
The scenario described is a common and correct way to use IdentityServer, so it should work.

The problem here is that when the information about the refresh token is stored to the operational store the data is encrypted using Asp.Net Core Data Protection. When the data is read back later, the encryption key used cannot be found. This results in the data not being available, which results in the `invalid_grant` error message.

Data Protection is a basic building block for security solutions in Asp.Net Core, including session cookies, anti forgery tokens, encrypted state in OpenID Connect etc. We have a [dedicated page](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/) in our documentation that describes more about how we use Data Protection as well as links to Microsoft's documentation about configuration of Data Protection for various hosting scenarios.

**Comment by AndersAbel** [comment]
Do you have any more questions or can we go ahead and close this issue?
