### ISSUE TITLE
Why are we getting RemoteCertificateNameMismatch error?

### ISSUE THREAD

**Issue by geetmenon** [DuendeSoftware/Support#962]
We are getting RemoteCertificateNameMismatch in our production environment. We have spent quite a bit to time and read up several links and blogs but we are not able to determine the root cause. Any help on this would be greatly appreciated. Please let us know if you need any additional information

Steps to replicate
-------------------
1) We created a code signing certificate on another machine. Exported it out (including private key), using the following powershell command:
New-SelfsignedCertificate -KeyExportPolicy Exportable -Type CodeSigningCert -DnsName localhost, webapi.mycomp.com, authserver.mycomp.com -Subject "CN=MyWebAPI" -KeySpec Signature -KeyAlgorithm RSA -KeyLength 2048 -HashAlgorithm SHA256 -CertStoreLocation "cert:\LocalMachine\My"

2) We imported it into our prod Server ( Windows 2008 R2)  under Local Computer/Trusted Root. We also copied it to Local Computer/Personal (just in case to see if it helps)

3) IdentityServer4 is running on is running on IIS 7.5 on say prod Server with the following bindings:
	hostname localhost on port https 5001 with our SSL certificate
	hostname authserver.mycomp.com on port https 443 with our valid SSL certificate
We are making use of client credentials workflow
We have specified the correct certificate name in Startup.cs:  builder.AddSigningCredential("CN=MyWebAPI");

4) Web API is running on IIS 7.5 on the same Server with the following bindings 
	hostname webapi.mycomp.com on port https 443 with our SSL certificate
In the Web API solution, for Bearer Token authentication, AuthorityURL is set to https://localhost:5001/

5) We are able to connect to token endpoint https://authserver.mycomp.com/connect/token and successfully get an access token (by passing in the correct grant type, client id, client secret and scope).

6) However when we make a call to the webapi at https://webapi.mycomp.com
	via swagger in Chrome, (after specifying the access token after clicking the Authorize button): it prompts for user id & password when we click on the Execute button
	via postman (after specifying the access token the Bearer Token in Authorization tab): we get 401 unauthorized error

In both cases, we see the following exception in our stdout log:
 IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

**Comment by AndersAbel** [comment]
The Web API should have the same authority URL as the clients are using. That is probably what is causing the issue. The web api opens a connection to `https://localhost:5001` and finds a certificate for `webapi.mycomp.com`. Even if you got that to succeed, there would probably be other issues because of issuer mismatch.

Would it be possible to set `IdentityModelEventSource.ShowPII = true` (it's a static property) to get some more information?

And IdentityServer4 is out of support. You should upgrade to a supported version of Duende IdentityServer, both to get support and to get on a version where patches are available.

**Comment by geetmenon** [comment]
Here is the log file after setting IdentityModelEventSource.ShowPII = true:

_fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
      IDX20803: Unable to obtain configuration from: 'https://localhost:5001/.well-known/openid-configuration'.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:5001/.well-known/openid-configuration'.
       ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://localhost:5001/.well-known/openid-configuration'.
       ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()_

**Comment by AndersAbel** [comment]
The problem is caused by the usage of `localhost` for the authority setting in the API. It should be the public facing URL.

IdentityServer4 is out of support, so we cannot provide further help on this here. When you have upgraded to a supported version of Duende IdentityServer you are welcome back and we will help you with any further issues. Please get in touch with us at contact@duendesoftware.com to purchase a license.
