### ISSUE TITLE
Azure Entra ID as IdP and Refresh Token Revocation

### ISSUE THREAD

**Issue by tylersouthard** [DuendeSoftware/Support#988]
**Which version of Duende BFF are you using?**

Duende.BFF 2.0.0

**Which version of .NET are you using?**

.NET 7.0

**Describe the bug**

When using Azure Entra ID as IdP, if I have a refresh token and attempt to sign out, a `System.InvalidOperationException: Revocation endpoint not configured` exception is thrown.

**To Reproduce**

One option would be to set up a web app and an associated registered application via Azure Entra ID in order to do the typical auth process.

More clearly, however, you can observe the output from https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration. This configuration lacks the `revocation_endpoint` item, which means the `OpenIdConnectClientConfiguration.RevocationEndpoint` member will be null.

**Expected behavior**

`revocation_endpoint` doesn't appear to be a required item in the OpenID config, so I wouldn't expect Duende.BFF to require it in order to support refresh tokens.

Obviously I could set the behavior to not automatically revoke the refresh token on logout and manually revoke it, but I would have thought this would be a pretty common use case. Maybe I'm missing something?

**Log output/exception with stacktrace**

```
System.InvalidOperationException: Revocation endpoint not configured
   at Duende.AccessTokenManagement.OpenIdConnect.UserTokenEndpointService.RevokeRefreshTokenAsync(String refreshToken, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/UserTokenEndpointService.cs:line 120
   at Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService.RevokeRefreshTokenAsync(ClaimsPrincipal user, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/UserAccessTokenManagementService.cs:line 126
   at Microsoft.AspNetCore.Authentication.TokenManagementHttpContextExtensions.RevokeRefreshTokenAsync(HttpContext httpContext, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/TokenManagementHttpContextExtensions.cs:line 51
   at Duende.Bff.PostConfigureApplicationCookieRevokeRefreshToken.<>c__DisplayClass5_0.<<CreateCallback>g__Callback|0>d.MoveNext() in /_/src/Duende.Bff/SessionManagement/Configuration/PostConfigureApplicationCookieRevokeRefreshToken.cs:line 50
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleSignOutAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignOutAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Duende.Bff.DefaultLogoutService.ProcessRequestAsync(HttpContext context) in /_/src/Duende.Bff/EndpointServices/Logout/DefaultLogoutService.cs:line 93
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Duende.Bff.Endpoints.BffMiddleware.Invoke(HttpContext context) in /_/src/Duende.Bff/EndpointProcessing/BffMiddleware.cs:line 71
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Additional context**

I'm not sure what should be expected:
1) That Azure Entra ID would provide `revocation_endpoint` in their configuration
2) That I shouldn't be using Azure Entra ID as an IdP if I'm using Duende.BFF
3) That Duende.BFF should have an alternate method for determining the revocation endpoint

**Comment by AndersAbel** [comment]
The revocation endpoint is not required neither by OAuth2 nor OpenID Connect so Entra Id is spec compliant even without it. As fars as I know Entra Id dosn't offer any revocation endpoint at all, it's not just that it's absent from the discovery document.

We've designed Duende.BFF to be used together with Duende.IdentityServer. Please note that using BFF requires a license and is included in Duende.IdentityServer business and enterprise, so any standalone usage would be rare. For the BFF to work with Entra Id we would have to ignore token revocation if there is no configured endpoint. It might make sense to make the BFF compatible with other OIDC Providers than IdentityServer, but it's not a high priority item for us.
