### ISSUE TITLE
ServerSideSession int -> long migrations fails

### ISSUE THREAD

**Issue by alsami** [DuendeSoftware/Support#993]
**Which version of Duende IdentityServer are you using?**

`7.0.0-preview.2`

**Which version of .NET are you using?**

`8.0.100`

**Describe the bug**

I was trying to update our solution to .NET 8 and include the latest preview of `Duende.IdentityServer.*` packages. Those updates required me to create two new migrations. One of the persisted-grants context and one for the configuration-context. The one for the persisted-grant context cannot be applied on a running microsoft sql-server with data (all other previous migrations applied). 

**To Reproduce**

1. Create a solution targeting the latest stable version
2. Add persisted-grant and configuration-store using the EF extensions library and apply all migrations
3. Now update to the latest preview
4. Create migration for configuration-store
5. Create migration for persisted-grant-store
6. Apply configuration-store migration
7. Apply persisted-grant-store -> this will fail with the error above (probably with and without data, haven't tested w/o data though)

**Expected behavior**

The migration completes without errors

**Log output/exception with stacktrace**

```sql
DECLARE @var0 sysname;
SELECT @var0 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[ServerSideSessions]') AND [c].[name] = N'Id');
IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [ServerSideSessions] DROP CONSTRAINT [' + @var0 + '];');
ALTER TABLE [ServerSideSessions] ALTER COLUMN [Id] bigint NOT NULL;

Microsoft.Data.SqlClient.SqlException (0x80131904): The object 'PK_ServerSideSessions' is dependent on column 'Id'.
ALTER TABLE ALTER COLUMN Id failed because one or more objects access this column.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:c5dd9b55-bed7-40d5-9e8b-2a31933be10f
Error Number:5074,State:1,Class:16
The object 'PK_ServerSideSessions' is dependent on column 'Id'.
ALTER TABLE ALTER COLUMN Id failed because one or more objects access this column.
```

**Additional context**

1. Running ubuntu-22.04
2. Using MsSqlServer docker container (2019)
3. Rider as an IDE
4. Latest SDK: 8.0.100
5. dotnet-ef also on the currently latest version

Relates to [Issue-1387](https://github.com/DuendeSoftware/IdentityServer/issues/1387)

**Comment by AndersAbel** [comment]
The problem is that Entity Framework Core migrations [doesn't support altering the data type of the primary key](https://github.com/dotnet/efcore/issues/30570). To do that, the PK must be dropped, data type changed and PK recreated.

I'll add docs to the upgrade guide that this must be handled manually.

**Comment by AndersAbel** [comment]
Please see the updated docs in https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/380 for a guide on how to handle this.

**Comment by AndersAbel** [comment]
Did the updated docs help? Is there anything more needed here or can we go ahead and close this issue?

**Comment by alsami** [comment]
Hey, sorry for the late reply. Been busy. Will try now and give you feedback ASAP. Thanks again for the quick support!

**Comment by alsami** [comment]
Worked fine. Thanks a lot!

**Comment by alsami** [comment]
Just as a side note: would add the same logic in the "Down" part of the migration. Might want to add that to the migration if it isn't there yet :)
